// Etiquetas de interfaz de «Persona» (réplica del estilo Arcade). Todo lo que es dato del portafolio (nombre, cargos,
// obras, cifras, FAQ) sale de useV5(); aquí solo las palabras de la interfaz. `ja` cae a `en`.
export const es = {
  saltar: 'Saltar al contenido',
  idioma: 'Idioma',
  nav: { inicio: 'Inicio', obra: 'Obra', trayectoria: 'Trayectoria', contacto: 'Contacto' },
  navAria: 'Navegación principal',
  sonido: 'Efectos de sonido',
  sonidoOn: 'Sonido activado',
  sonidoOff: 'Sonido apagado',
  copiarCorreo: 'Copiar el correo',
  correoCopiado: 'Correo copiado',
  volverArriba: 'Volver arriba',
  hora: 'Medellín',
  construidas: 'tiendas construidas',
  inicio: {
    titulo: 'Inicio',
    menuAria: 'Elige una pantalla',
    hint: ['elegir', 'confirmar', 'toca para entrar'],
    menu: {
      obra: 'Tiendas, apps y proyectos con sus capturas',
      trayectoria: 'Cargos, del más reciente al más antiguo',
      contacto: 'Revisión gratis de 20 minutos',
    },
    cinta: 'Algunas de las tiendas',
    numeros: 'El trabajo, en números',
    numerosPrimer: 'Primer cargo',
    modelos: 'Tres formas de empezar',
    cierre: 'Cuéntame de tu tienda',
    verObra: 'Ver la obra',
    numerosEyebrow: 'Cifras con su fuente',
    fuente: 'Fuente',
    destacadas: {
      eyebrow: 'Obra destacada',
      masTiendas: 'Más tiendas',
      verCaso: 'Ver el caso completo',
      verTodo: 'Ver toda la obra',
      lead: 'Kits con descuento calculado al pagar, un diseño de Framer portado 1:1, medición propia y un catálogo que se sincroniza solo. Abre una y ves lo que se pidió, lo que se hizo, sus capturas y el enlace.',
    },
    disponibleEn: 'Desde',
  },
  obra: {
    titulo: 'Obra',
    eyebrow: 'Selecciona un nivel',
    lead: 'Tiendas, apps y proyectos. Abre uno para ver sus capturas y sus datos.',
    filtros: { todo: 'Todo', store: 'Tiendas', product: 'Apps y plataforma', personal: 'Proyectos personales', role: 'Entregables de cargo' },
    filtrosAria: 'Filtrar la obra por tipo',
    tipo: { store: 'Tienda', product: 'Producto', personal: 'Proyecto personal', role: 'Entregable de cargo' },
    sinCaptura: 'Sin captura',
    capturaHome: 'Captura de la home de {name}',
    abrir: 'Abrir {name}',
    cuenta: 'Mostrando {n} obras',
    cuentaUna: 'Mostrando 1 obra',
    archivo: 'Más trabajo',
    archivoLead: 'Proyectos y entregables sin captura pública, cada uno con su historia en una línea.',
    verCargo: 'Ver el cargo de {name}',
    pila: 'Pila',
  },
  ficha: {
    volver: 'Obra',
    volverAria: 'Volver al índice de obra',
    anterior: 'Anterior',
    siguiente: 'Siguiente',
    vistas: { home: 'Home', pdp: 'Página de producto' },
    vistasAria: 'Elegir la vista de la captura',
    escritorio: 'Escritorio',
    movil: 'Móvil',
    capturaDe: 'Captura de {name}, {vista}, {vp}',
    sinCaptura: 'Esta obra no tiene captura pública.',
    datos: 'Datos',
    sector: 'Sector',
    anio: 'Año',
    periodo: 'Periodo',
    rol: 'Alcance',
    stack: 'Construida con',
    visitar: 'Visitar sitio',
    medidas: 'Mediciones con fecha',
    commits: 'commits',
    gitRango: 'Del {first} al {last}',
    gitMedido: 'Medido el {fecha}',
    productos: 'productos',
    catalogoColecciones: '{n} colecciones',
    catalogoMedido: 'Leído el {fecha}',
    lhEtiqueta: 'Lighthouse móvil / escritorio',
    lhNota: 'Medición local, mejor de 3 · {fecha}',
    noExiste: 'No encontré esa obra',
    noExisteLead: 'El enlace no coincide con ninguna obra del archivo.',
    caso: 'El caso',
    casoEyebrow: 'Qué se pidió, qué se hizo',
    casoCompleto: 'El caso, de principio a fin',
    historial: 'Historial de git',
    historialLinea: '{n} commits, del {first} al {last} (medido el {fecha})',
    estado: 'Estado',
  },
  trayectoria: {
    titulo: 'Trayectoria',
    eyebrow: 'Cada cargo, en orden',
    hoy: 'Hoy',
    cargos: 'Cargos',
    actual: 'Actual',
    anios: 'Obra por año',
    aniosLead: 'Cuántas obras del archivo llevan cada año.',
    aniosAria: 'Obra por año',
    obras: 'obras',
    obra: 'obra',
    indice: 'Ir a un cargo',
    cifrasCv: 'Cifras de mi CV; sin medición pública',
    entregable: 'Entregable del cargo',
    anioRoles: 'roles',
    anioTiendas: 'tiendas',
    anioProductos: 'productos',
    anioPropios: 'proyectos propios',
    anioEn: 'En {y}',
    usoNota: 'El número es cuántas tiendas, productos y entregables de cargo lo nombran en su pila.',
    herramientas: 'herramientas',
    grupos: 'Grupos de habilidades',
  },
  contacto: {
    titulo: 'Contacto',
    formulario: 'Formulario',
    correo: 'Tu correo',
    correoPlaceholder: 'tu@correo.com',
    motivo: 'Motivo',
    mensaje: 'Mensaje',
    opcional: 'opcional',
    enlace: 'Enlace',
    enviar: 'Enviar',
    enviando: 'Enviando',
    ok: 'Mensaje enviado. Gracias por escribir.',
    error: 'No pude enviarlo desde aquí; se abrió tu correo para que lo mandes directo.',
    placeholders: {
      revision: 'Qué parte de la tienda quieres que mire primero',
      proyecto: 'Qué quieres construir y para cuándo lo necesitas',
      continuo: 'Qué necesitas que se mantenga o mejore',
      empleo: 'Cuéntame del equipo y del puesto',
    },
    canales: 'Canales directos',
    whatsapp: 'WhatsApp',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    cv: 'Descargar CV',
    faq: 'Antes de escribir',
    paso: 'Paso',
    elegir: 'Elegir esta forma',
    elegida: 'Elegida',
  },
  footer: 'Reconstruido para elegir',
} as const

type Widen<T> = T extends string ? string : T extends readonly (infer U)[] ? readonly Widen<U>[] : T extends object ? { [K in keyof T]: Widen<T[K]> } : T
export type Copy = Widen<typeof es>

export const en: Copy = {
  saltar: 'Skip to content',
  idioma: 'Language',
  nav: { inicio: 'Home', obra: 'Work', trayectoria: 'Career', contacto: 'Contact' },
  navAria: 'Main navigation',
  sonido: 'Sound effects',
  sonidoOn: 'Sound on',
  sonidoOff: 'Sound off',
  copiarCorreo: 'Copy the email',
  correoCopiado: 'Email copied',
  volverArriba: 'Back to top',
  hora: 'Medellín',
  construidas: 'stores built',
  inicio: {
    titulo: 'Home',
    menuAria: 'Choose a screen',
    hint: ['select', 'confirm', 'tap to enter'],
    menu: {
      obra: 'Stores, apps and projects with their screenshots',
      trayectoria: 'Roles, newest first',
      contacto: 'Free 20-minute review',
    },
    cinta: 'Some of the stores',
    numeros: 'The work, in numbers',
    numerosPrimer: 'First role',
    modelos: 'Three ways to start',
    cierre: 'Tell me about your store',
    verObra: 'See the work',
    numerosEyebrow: 'Figures, with their source',
    fuente: 'Source',
    destacadas: {
      eyebrow: 'Featured work',
      masTiendas: 'More stores',
      verCaso: 'See the full case',
      verTodo: 'See all the work',
      lead: 'Kits with a discount priced at checkout, a Framer design ported 1:1, first-party measurement and a catalog that syncs itself. Open one to see what was asked, what was done, its screenshots and the link.',
    },
    disponibleEn: 'From',
  },
  obra: {
    titulo: 'Work',
    eyebrow: 'Select a stage',
    lead: 'Stores, apps and projects. Open one to see its screenshots and its data.',
    filtros: { todo: 'All', store: 'Stores', product: 'Apps and platform', personal: 'Personal projects', role: 'Role deliverables' },
    filtrosAria: 'Filter the work by type',
    tipo: { store: 'Store', product: 'Product', personal: 'Personal project', role: 'Role deliverable' },
    sinCaptura: 'No screenshot',
    capturaHome: 'Home page screenshot of {name}',
    abrir: 'Open {name}',
    cuenta: 'Showing {n} works',
    cuentaUna: 'Showing 1 work',
    archivo: 'More work',
    archivoLead: 'Projects and deliverables without a public screenshot, each with its story in one line.',
    verCargo: 'See the role at {name}',
    pila: 'Stack',
  },
  ficha: {
    volver: 'Work',
    volverAria: 'Back to the work index',
    anterior: 'Previous',
    siguiente: 'Next',
    vistas: { home: 'Home', pdp: 'Product page' },
    vistasAria: 'Choose the screenshot view',
    escritorio: 'Desktop',
    movil: 'Mobile',
    capturaDe: 'Screenshot of {name}, {vista}, {vp}',
    sinCaptura: 'This work has no public screenshot.',
    datos: 'Data',
    sector: 'Industry',
    anio: 'Year',
    periodo: 'Period',
    rol: 'Scope',
    stack: 'Built with',
    visitar: 'Visit site',
    medidas: 'Dated measurements',
    commits: 'commits',
    gitRango: 'From {first} to {last}',
    gitMedido: 'Measured on {fecha}',
    productos: 'products',
    catalogoColecciones: '{n} collections',
    catalogoMedido: 'Read on {fecha}',
    lhEtiqueta: 'Lighthouse mobile / desktop',
    lhNota: 'Local measurement, best of 3 · {fecha}',
    noExiste: 'I could not find that work',
    noExisteLead: 'The link does not match any work in the archive.',
    caso: 'The case',
    casoEyebrow: 'What was asked, what was done',
    casoCompleto: 'The case, start to finish',
    historial: 'Git history',
    historialLinea: '{n} commits, from {first} to {last} (measured on {fecha})',
    estado: 'Status',
  },
  trayectoria: {
    titulo: 'Career',
    eyebrow: 'Every role, in order',
    hoy: 'Today',
    cargos: 'Roles',
    actual: 'Current',
    anios: 'Work per year',
    aniosLead: 'How many works in the archive carry each year.',
    aniosAria: 'Work per year',
    obras: 'works',
    obra: 'work',
    indice: 'Jump to a role',
    cifrasCv: 'Figures from my CV; not publicly measured',
    entregable: 'Deliverable of the role',
    anioRoles: 'roles',
    anioTiendas: 'stores',
    anioProductos: 'products',
    anioPropios: 'own projects',
    anioEn: 'In {y}',
    usoNota: 'The number is how many stores, products and role deliverables name it in their stack.',
    herramientas: 'tools',
    grupos: 'Skill groups',
  },
  contacto: {
    titulo: 'Contact',
    formulario: 'Form',
    correo: 'Your email',
    correoPlaceholder: 'you@email.com',
    motivo: 'Reason',
    mensaje: 'Message',
    opcional: 'optional',
    enlace: 'Link',
    enviar: 'Send',
    enviando: 'Sending',
    ok: 'Message sent. Thanks for writing.',
    error: 'I could not send it from here; your mail app opened so you can send it directly.',
    placeholders: {
      revision: 'Which part of the store you want me to look at first',
      proyecto: 'What you want built and when you need it',
      continuo: 'What you need kept running or improved',
      empleo: 'Tell me about the team and the role',
    },
    canales: 'Direct channels',
    whatsapp: 'WhatsApp',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    cv: 'Download CV',
    faq: 'Before you write',
    paso: 'Step',
    elegir: 'Choose this way',
    elegida: 'Chosen',
  },
  footer: 'Rebuilt to choose from',
}

export const COPY = { es, en } as const
export const copyFor = (locale: string): Copy => (locale === 'es' ? es : en)
