import { useLanguage } from '../../context/LanguageContext'
import type { ObraKind } from '../data'
import { MOTIVOS, type Motivo } from '../shared/contacto'

// Interfaz de la dirección Ingeniería en es y en (ja usa en). Los textos de contenido (hero, cargos, FAQ, proceso, manifiesto,
// resumen del cargo) vienen de useV5() y no se repiten aquí; lo que sí vive aquí es lo que la dirección añade: la presentación de
// Max en primera persona, las cuatro cifras con su cargo y su periodo, el rótulo de las figuras y las etiquetas de interfaz.
// Cada afirmación sale del CV, del registro o de una medición con fecha. Nada de «CTO desde 2024», «800+ pruebas» ni conteos sin
// fuente (CONTENIDO-VERDAD §4 y §8).
const motivos = (l: 'es' | 'en') => Object.fromEntries(Object.entries(MOTIVOS).map(([k, v]) => [k, v[l]])) as Record<Motivo, string>

const es = {
  saltar: 'Saltar al contenido',
  principal: 'Principal',
  nav: { inicio: 'Inicio', obra: 'Obra', trayectoria: 'Trayectoria', contacto: 'Contacto' },
  idioma: 'Idioma',
  menu: { abrir: 'Abrir el menú', cerrar: 'Cerrar el menú' },
  revision: 'Revisión gratis',
  cv: 'Descargar CV',
  repetir: 'Repetir',
  tiendasConstruidas: (n: string) => `${n} tiendas construidas`,
  kinds: { store: 'Tienda', product: 'Producto', role: 'Entregable', personal: 'Proyecto personal' } satisfies Record<ObraKind, string>,
  hero: {
    medellin: (h: string) => `Medellín · ${h}`,
    chipEtq: 'Escritorio · Lighthouse',
    chipLcp: 'LCP',
    chipFuente: (n: string, f: string) => `${n} · medición local · ${f}`,
    ventana: 'The Gummy Box · Home',
    movil: 'NOS Café · Home en móvil',
  },
  persona: {
    etq: 'Quién hay detrás',
    titulo: 'Construyo tiendas que venden,',
    acento: 'y el sistema que las entrega',
    equipo: 'Dirijo a un desarrollador y a equipos de agentes de IA: así un equipo de dos entrega a escala de agencia.',
    hechos: [
      { k: '2022 → hoy', v: 'De componentes React a una flota de tiendas Shopify y la plataforma detrás.' },
      { k: 'Medellín', v: 'Español nativo e inglés C1 (IELTS), para marcas de EE. UU. y Latinoamérica.' },
      { k: 'EAFIT', v: 'Ingeniería de Software, desde 2023.' },
    ],
    fuente: 'Según el CV y el perfil de LinkedIn',
    mas: 'Ver la trayectoria completa',
    retrato: 'Monograma MB dibujado con las hebras de la cinta',
  },
  cifras: {
    etq: 'Lo que hice',
    titulo: 'Cuatro cifras,',
    acento: 'y de dónde sale cada una',
    items: [
      { id: 'digitdeck-cto', v: '33', e: 'componentes y tokens de diseño compartidos por 14 marcas' },
      { id: 'digitdeck-cto', v: '70', e: 'patrones de conversión, salidos de investigar 59 marcas DTC' },
      { id: 'digitdeck-cto', v: '11.000', e: 'líneas de Liquid replataformadas a islas React, con paridad visual verificada' },
      { id: 'abidata', v: '−40 %', e: 'de tiempo por campaña con el editor de correo en React que construí' },
    ],
  },
  obraHome: { etq: 'Obra', titulo: 'Más obra,', acento: 'cada una con su historia', verTodo: 'Ver toda la obra' },
  sistema: {
    etq: 'Cómo trabajo',
    titulo: 'Liquid para lo estático.',
    acento: 'React solo donde se mueve',
    texto: 'El front son islas de React montadas en Liquid, solo donde la interacción lo justifica. El resto de la página es Liquid que el cliente edita sin desplegar.',
    fig1: {
      etq: 'FIG 0.1 · Una página real, anotada',
      pie: 'NOS Café · armador de cajas · captura del 2026-09-07',
      leyenda: [
        { n: 1, t: 'Anuncio y encabezado', d: 'Liquid · se edita en el tema', isla: false },
        { n: 2, t: 'Titular y texto', d: 'Liquid · se edita en el tema', isla: false },
        { n: 3, t: 'Armador de cajas y su barra de descuento', d: 'Isla React · se mueve', isla: true },
      ],
    },
    fig2: {
      etq: 'FIG 0.2 · La suite de apps',
      titulo: 'Una instalación, cinco módulos.',
      acento: 'Multi-tenant sobre el stack oficial de Remix',
      texto: 'Pruebas A/B, reseñas, bundles, referidos y aviso de stock, más un motor de facturación de suscripciones. Dos Shopify Functions compiladas a WASM, un Web Pixel con consentimiento y una Theme App Extension.',
      modulos: ['Pruebas A/B', 'Reseñas', 'Bundles', 'Referidos', 'Aviso de stock'],
      hub: { n: 'Digitdeck Apps', d: 'Hub multi-tenant · Remix', pila: 'Prisma · PostgreSQL · BullMQ' },
      superficies: [
        { n: '2 Shopify Functions', d: 'compiladas a WASM' },
        { n: 'Web Pixel', d: 'con consentimiento' },
        { n: 'Theme App Extension', d: 'bloques del editor' },
      ],
      modulosEtq: 'Módulos',
      superficiesEtq: 'Superficies de Shopify',
    },
  },
  cierre: { etq: 'Hablemos' },
  obra: {
    h1: 'Obra',
    acento: 'Tiendas, apps y proyectos, cada uno con su historia',
    filtrar: 'Filtrar por tipo',
    tipos: { todo: 'Todo', store: 'Tiendas', product: 'Productos', mas: 'Más' },
    historias: 'Historias',
    masTiendas: 'Más tiendas',
    proyectos: 'Otros proyectos',
    leer: 'Leer el caso',
  },
  ficha: {
    volver: 'Obra',
    visitar: 'Visitar el sitio',
    sitioDe: (n: string) => `Sitio de ${n}`,
    codigo: 'Ver el código',
    home: 'Home',
    pdp: 'Producto',
    vista: 'Vista',
    piezas: 'Piezas usadas',
    queHice: 'Qué hice',
    tipo: 'Tipo de trabajo',
    periodo: 'Periodo',
    anio: 'Año',
    rubro: 'Rubro',
    empleo: 'Empleo',
    historia: 'La historia',
    medido: 'Medido',
    metricas: 'En cifras',
    secciones: 'secciones propias en el tema',
    gitFuente: (f: string) => `Git de la tienda · a ${f}`,
    productosCat: 'productos en el catálogo',
    coleccionesCat: 'colecciones',
    catalogoFuente: (f: string) => `Catálogo público · a ${f}`,
    medidoT: 'Lighthouse,',
    medidoAcento: 'con su fuente y su fecha',
    lighthouse: 'Lighthouse',
    movil: 'Móvil',
    escritorio: 'Escritorio',
    rend: 'Rendimiento',
    acc: 'Accesibilidad',
    seo: 'SEO',
    lhFuente: (f: string) => `Medición local · mejor de 3 · ${f}`,
    lhNota: 'Medición de laboratorio, no datos de usuarios reales. La puntuación móvil usa el perfil móvil de Lighthouse, que es el más exigente.',
    segunCv: 'Según el CV de Max',
    siguiente: 'Siguiente caso',
    noExiste: 'Esa obra no existe',
    volverObra: 'Volver a la obra',
    capturaPie: (n: string, v: string, f: string) => `${n} · ${v} · ${f}`,
    registro: 'Registro del proyecto',
  },
  tray: {
    h1: 'Trayectoria',
    hoy: 'Hoy',
    mapa: 'Los cargos en el tiempo',
    mapaAria: 'Cargos de 2022 a hoy en una línea de tiempo',
    actual: 'Cargo actual',
    antes: 'Antes',
    resultados: 'Qué se entregó',
    construye: 'Lo que construye hoy',
    pila: 'Stack',
    segun: (c: string, p: string) => `Según el CV · ${c}, ${p}`,
    entregable: 'Entregable',
    fuenteAntes: 'Cargos, resultados y cifras según el CV de Max.',
    empleo: 'Escríbeme por un cargo',
  },
  contacto: {
    tienda: 'La URL de tu tienda',
    tiendaEj: 'tutienda.com',
    correo: 'Tu correo',
    correoEj: 'tu@tienda.com',
    motivos: motivos('es'),
    motivo: 'Motivo',
    enviar: { revision: 'Pedir la revisión', proyecto: 'Contar el proyecto', continuo: 'Hablar del trabajo continuo', empleo: 'Escribir por la vacante' },
    enviando: 'Enviando',
    ok: 'Recibido. Te escribiré al correo que dejaste.',
    error: 'No se pudo enviar. Se abrió tu correo con el mensaje listo.',
    falta: 'Escribe un correo válido.',
    faltaTienda: 'Escribe la URL de tu tienda.',
    elegir: 'Elegir este modelo',
    canales: 'Canales directos',
    correoC: 'Correo',
    copiar: 'Copiar',
    copiado: 'Copiado',
    whatsapp: 'WhatsApp',
    waTexto: 'Hola Max, quiero la revisión gratis de 20 minutos de mi tienda.',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    cvC: 'CV en PDF',
    faq: 'Preguntas frecuentes',
    form: 'Escríbeme',
    escribir: { etq: 'Otra vía', titulo: 'Si prefieres escribir,', acento: 'deja tu tienda y tu correo' },
  },
  pie: { medellin: 'Medellín, Colombia', arriba: 'Volver arriba', nav: 'Navegar', sitio: 'Mapa' },
}

const en: typeof es = {
  saltar: 'Skip to content',
  principal: 'Main',
  nav: { inicio: 'Home', obra: 'Work', trayectoria: 'Career', contacto: 'Contact' },
  idioma: 'Language',
  menu: { abrir: 'Open the menu', cerrar: 'Close the menu' },
  revision: 'Free review',
  cv: 'Download CV',
  repetir: 'Replay',
  tiendasConstruidas: (n: string) => `${n} stores built`,
  kinds: { store: 'Store', product: 'Product', role: 'Deliverable', personal: 'Personal project' },
  hero: {
    medellin: (h: string) => `Medellín · ${h}`,
    chipEtq: 'Desktop · Lighthouse',
    chipLcp: 'LCP',
    chipFuente: (n: string, f: string) => `${n} · local measurement · ${f}`,
    ventana: 'The Gummy Box · Home',
    movil: 'NOS Café · Home on mobile',
  },
  persona: {
    etq: "Who's behind it",
    titulo: 'I build Shopify stores that sell,',
    acento: 'and the system that ships them',
    equipo: 'I lead one developer and teams of AI agents, so a team of two delivers at agency scale.',
    hechos: [
      { k: '2022 → today', v: 'From React components to a fleet of Shopify stores and the platform behind them.' },
      { k: 'Medellín', v: 'Native Spanish and C1 English (IELTS), for US and Latin American brands.' },
      { k: 'EAFIT', v: 'Software Engineering, since 2023.' },
    ],
    fuente: "Per Max's CV and LinkedIn profile",
    mas: 'See the full career',
    retrato: 'The MB monogram drawn with the strands of the ribbon',
  },
  cifras: {
    etq: 'What I did',
    titulo: 'Four numbers,',
    acento: 'and where each one comes from',
    items: [
      { id: 'digitdeck-cto', v: '33', e: 'shared components and design tokens across 14 brands' },
      { id: 'digitdeck-cto', v: '70', e: 'conversion patterns, from researching 59 DTC brands' },
      { id: 'digitdeck-cto', v: '11,000', e: 'lines of Liquid re-platformed to React islands, with verified visual parity' },
      { id: 'abidata', v: '−40%', e: 'campaign time with the React email editor I built' },
    ],
  },
  obraHome: { etq: 'Work', titulo: 'More work,', acento: 'each with its story', verTodo: 'See all the work' },
  sistema: {
    etq: 'How I work',
    titulo: 'Liquid for what stays still.',
    acento: 'React only where it moves',
    texto: 'The front end is React islands mounted in Liquid, only where the interaction justifies it. The rest of the page is Liquid the client edits without deploying.',
    fig1: {
      etq: 'FIG 0.1 · A real page, annotated',
      pie: 'NOS Café · box builder · captured 2026-09-07',
      leyenda: [
        { n: 1, t: 'Announcements and header', d: 'Liquid · edited in the theme', isla: false },
        { n: 2, t: 'Headline and text', d: 'Liquid · edited in the theme', isla: false },
        { n: 3, t: 'Box builder and its discount bar', d: 'React island · moves', isla: true },
      ],
    },
    fig2: {
      etq: 'FIG 0.2 · The app suite',
      titulo: 'One install, five modules.',
      acento: 'Multi-tenant on the official Remix stack',
      texto: 'A/B tests, reviews, bundles, referrals and back-in-stock alerts, plus a subscription billing engine. Two Shopify Functions compiled to WASM, a consent-aware Web Pixel and a Theme App Extension.',
      modulos: ['A/B tests', 'Reviews', 'Bundles', 'Referrals', 'Back-in-stock'],
      hub: { n: 'Digitdeck Apps', d: 'Multi-tenant hub · Remix', pila: 'Prisma · PostgreSQL · BullMQ' },
      superficies: [
        { n: '2 Shopify Functions', d: 'compiled to WASM' },
        { n: 'Web Pixel', d: 'with consent' },
        { n: 'Theme App Extension', d: 'editor blocks' },
      ],
      modulosEtq: 'Modules',
      superficiesEtq: 'Shopify surfaces',
    },
  },
  cierre: { etq: "Let's talk" },
  obra: {
    h1: 'Work',
    acento: 'Stores, apps and projects, each with its story',
    filtrar: 'Filter by type',
    tipos: { todo: 'All', store: 'Stores', product: 'Products', mas: 'More' },
    historias: 'Stories',
    masTiendas: 'More stores',
    proyectos: 'Other projects',
    leer: 'Read the case',
  },
  ficha: {
    volver: 'Work',
    visitar: 'Visit the site',
    sitioDe: (n: string) => `${n} website`,
    codigo: 'See the code',
    home: 'Home',
    pdp: 'Product',
    vista: 'View',
    piezas: 'Pieces used',
    queHice: 'What I did',
    tipo: 'Type of work',
    periodo: 'Period',
    anio: 'Year',
    rubro: 'Industry',
    empleo: 'Employer',
    historia: 'The story',
    medido: 'Measured',
    metricas: 'In numbers',
    secciones: 'custom sections in the theme',
    gitFuente: (f: string) => `Store git history · as of ${f}`,
    productosCat: 'products in the catalog',
    coleccionesCat: 'collections',
    catalogoFuente: (f: string) => `Public catalog · as of ${f}`,
    medidoT: 'Lighthouse,',
    medidoAcento: 'with its source and date',
    lighthouse: 'Lighthouse',
    movil: 'Mobile',
    escritorio: 'Desktop',
    rend: 'Performance',
    acc: 'Accessibility',
    seo: 'SEO',
    lhFuente: (f: string) => `Local measurement · best of 3 · ${f}`,
    lhNota: "Lab measurement, not real-user data. The mobile score uses Lighthouse's mobile profile, the harsher one.",
    segunCv: "According to Max's CV",
    siguiente: 'Next case',
    noExiste: 'That work does not exist',
    volverObra: 'Back to the work',
    capturaPie: (n: string, v: string, f: string) => `${n} · ${v} · ${f}`,
    registro: 'Project record',
  },
  tray: {
    h1: 'Career',
    hoy: 'Today',
    mapa: 'The roles over time',
    mapaAria: 'Roles from 2022 to today on a timeline',
    actual: 'Current role',
    antes: 'Before',
    resultados: 'What was delivered',
    construye: 'What I am building now',
    pila: 'Stack',
    segun: (c: string, p: string) => `Per the CV · ${c}, ${p}`,
    entregable: 'Deliverable',
    fuenteAntes: "Roles, results and figures per Max's CV.",
    empleo: 'Write to me about a role',
  },
  contacto: {
    tienda: 'Your store URL',
    tiendaEj: 'yourstore.com',
    correo: 'Your email',
    correoEj: 'you@store.com',
    motivos: motivos('en'),
    motivo: 'Reason',
    enviar: { revision: 'Ask for the review', proyecto: 'Tell me about the project', continuo: 'Talk about ongoing work', empleo: 'Write about the role' },
    enviando: 'Sending',
    ok: "Received. I'll write back to the email you left.",
    error: 'It could not be sent. Your email app opened with the message ready.',
    falta: 'Enter a valid email.',
    faltaTienda: 'Enter your store URL.',
    elegir: 'Choose this model',
    canales: 'Direct channels',
    correoC: 'Email',
    copiar: 'Copy',
    copiado: 'Copied',
    whatsapp: 'WhatsApp',
    waTexto: 'Hi Max, I want the free 20-minute review of my store.',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    cvC: 'CV as PDF',
    faq: 'Frequently asked questions',
    form: 'Write to me',
    escribir: { etq: 'Another route', titulo: 'If you would rather write,', acento: 'leave your store and email' },
  },
  pie: { medellin: 'Medellín, Colombia', arriba: 'Back to top', nav: 'Navigate', sitio: 'Map' },
}

export type Copy = typeof es
const DICCIONARIOS: Record<'es' | 'en' | 'ja', Copy> = { es, en, ja: en }
export const useCopy = (): Copy => DICCIONARIOS[useLanguage().locale]
