import { useLanguage } from '../../context/LanguageContext'
import type { ObraKind } from '../data'
import { MOTIVOS, type Motivo } from '../shared/contacto'

// Etiquetas de interfaz de la dirección Apple en los tres idiomas. Los textos de contenido (obras, cargos, FAQ,
// hero) vienen de useV5(); aquí solo vive la interfaz. El asunto del correo que llega a Max va siempre en inglés (shared/contacto).
const motivos = (l: 'es' | 'en') => Object.fromEntries(Object.entries(MOTIVOS).map(([k, v]) => [k, v[l]])) as Record<Motivo, string>
const es = {
  saltar: 'Saltar al contenido',
  principal: 'Principal',
  nav: { inicio: 'Inicio', obra: 'Obra', trayectoria: 'Trayectoria', contacto: 'Contacto' },
  idioma: 'Idioma',
  tema: { aClaro: 'Cambiar al tema claro', aOscuro: 'Cambiar al tema oscuro' },
  menu: { abrir: 'Abrir el menú', cerrar: 'Cerrar el menú' },
  escribeme: 'Escríbeme',
  tiendasConstruidas: (n: string) => `${n} tiendas construidas`,
  banda: 'Tiendas construidas',
  verObra: 'Ver la obra',
  verFicha: 'Ver la ficha',
  verTodaObra: 'Ver toda la obra',
  cvLabel: 'Descargar CV',
  escena: { escritorio: 'Escritorio', movil: 'Móvil' },
  obra: {
    h1: 'Obra',
    tipos: { todo: 'Todo', store: 'Tiendas', product: 'Productos', mas: 'Más' },
    filtrar: 'Filtrar por tipo',
    entregables: 'Entregables dentro de los cargos',
  },
  kinds: { store: 'Tienda', product: 'Producto', role: 'Entregable', personal: 'Proyecto personal' } satisfies Record<ObraKind, string>,
  ficha: {
    volver: 'Obra',
    visitar: 'Visitar el sitio',
    sitioDe: (n: string) => `Sitio de ${n}`,
    home: 'Home',
    pdp: 'Página de producto',
    vista: 'Vista',
    datos: 'Datos',
    rubro: 'Rubro',
    rol: 'Rol',
    anio: 'Año',
    periodo: 'Periodo',
    empleo: 'Empleo',
    pila: 'Pila',
    git: 'Git',
    commits: 'commits',
    secciones: 'secciones',
    primerCommit: 'primer commit',
    gitNota: (f: string) => `Del repositorio de la tienda, a ${f}.`,
    catalogo: 'Catálogo',
    catalogoNota: (f: string) => `Catálogo público de la tienda, a ${f}.`,
    repo: 'Código',
    medido: 'Medido',
    lighthouse: 'Lighthouse',
    movil: 'Móvil',
    escritorio: 'Escritorio',
    rend: 'Rendimiento',
    acc: 'Accesibilidad',
    seo: 'SEO',
    lhNota: (f: string) => `Medición local del ${f}, mejor de 3.`,
    siguiente: 'Siguiente',
    noExiste: 'Esa obra no existe',
    volverObra: 'Volver a la obra',
  },
  tray: {
    h1: 'Trayectoria',
    hoy: 'Hoy',
    segunCv: 'Según el CV de Max',
    cargos: 'Cargos',
    flotaNota: (f: string) => `Del git de las tiendas, a ${f}.`,
  },
  contacto: {
    tienda: 'La URL de tu tienda',
    tiendaEj: 'tutienda.com',
    correo: 'Tu correo',
    correoEj: 'tu@tienda.com',
    motivos: motivos('es'),
    motivo: 'Motivo',
    enviar: { revision: 'Pedir la revisión', proyecto: 'Contar el proyecto', continuo: 'Hablar del trabajo continuo', empleo: 'Escribir por la vacante' },
    enviando: 'Enviando',
    ok: 'Recibido. Te escribiré al correo que dejaste.',
    error: 'No se pudo enviar. Se abrió tu correo con el mensaje listo.',
    falta: 'Escribe un correo válido.',
    faltaTienda: 'Escribe la URL de tu tienda.',
    elegir: 'Elegir este modelo',
    canalCorreo: 'Correo',
    copiar: 'Copiar',
    copiado: 'Copiado',
    whatsapp: 'WhatsApp',
    waTexto: 'Hola Max, quiero la revisión gratis de 20 minutos de mi tienda.',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    cv: 'CV en PDF',
    faq: 'Antes de escribir',
  },
  pie: { medellin: 'Medellín, Colombia', arriba: 'Volver arriba' },
}

const en: typeof es = {
  saltar: 'Skip to content',
  principal: 'Main',
  nav: { inicio: 'Home', obra: 'Work', trayectoria: 'Career', contacto: 'Contact' },
  idioma: 'Language',
  tema: { aClaro: 'Switch to light theme', aOscuro: 'Switch to dark theme' },
  menu: { abrir: 'Open the menu', cerrar: 'Close the menu' },
  escribeme: 'Write to me',
  tiendasConstruidas: (n: string) => `${n} stores built`,
  banda: 'Stores built',
  verObra: 'See the work',
  verFicha: 'See the case',
  verTodaObra: 'See all the work',
  cvLabel: 'Download CV',
  escena: { escritorio: 'Desktop', movil: 'Mobile' },
  obra: {
    h1: 'Work',
    tipos: { todo: 'All', store: 'Stores', product: 'Products', mas: 'More' },
    filtrar: 'Filter by type',
    entregables: 'Deliverables inside the roles',
  },
  kinds: { store: 'Store', product: 'Product', role: 'Deliverable', personal: 'Personal project' },
  ficha: {
    volver: 'Work',
    visitar: 'Visit the site',
    sitioDe: (n: string) => `${n} website`,
    home: 'Home',
    pdp: 'Product page',
    vista: 'View',
    datos: 'Facts',
    rubro: 'Industry',
    rol: 'Role',
    anio: 'Year',
    periodo: 'Period',
    empleo: 'Employer',
    pila: 'Stack',
    git: 'Git',
    commits: 'commits',
    secciones: 'sections',
    primerCommit: 'first commit',
    gitNota: (f: string) => `From the store repository, as of ${f}.`,
    catalogo: 'Catalog',
    catalogoNota: (f: string) => `Public store catalog, as of ${f}.`,
    repo: 'Code',
    medido: 'Measured',
    lighthouse: 'Lighthouse',
    movil: 'Mobile',
    escritorio: 'Desktop',
    rend: 'Performance',
    acc: 'Accessibility',
    seo: 'SEO',
    lhNota: (f: string) => `Local measurement from ${f}, best of 3.`,
    siguiente: 'Next',
    noExiste: 'That work does not exist',
    volverObra: 'Back to the work',
  },
  tray: {
    h1: 'Career',
    hoy: 'Today',
    segunCv: "According to Max's CV",
    cargos: 'Roles',
    flotaNota: (f: string) => `From the stores' git history, as of ${f}.`,
  },
  contacto: {
    tienda: 'Your store URL',
    tiendaEj: 'yourstore.com',
    correo: 'Your email',
    correoEj: 'you@store.com',
    motivos: motivos('en'),
    motivo: 'Reason',
    enviar: { revision: 'Ask for the review', proyecto: 'Tell me about the project', continuo: 'Talk about ongoing work', empleo: 'Write about the role' },
    enviando: 'Sending',
    ok: "Received. I'll write back to the email you left.",
    error: 'It could not be sent. Your email app opened with the message ready.',
    falta: 'Enter a valid email.',
    faltaTienda: 'Enter your store URL.',
    elegir: 'Choose this model',
    canalCorreo: 'Email',
    copiar: 'Copy',
    copiado: 'Copied',
    whatsapp: 'WhatsApp',
    waTexto: 'Hi Max, I want the free 20-minute review of my store.',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    cv: 'CV as PDF',
    faq: 'Before you write',
  },
  pie: { medellin: 'Medellín, Colombia', arriba: 'Back to top' },
}

const ja: typeof es = {
  saltar: 'コンテンツへ移動',
  principal: 'メイン',
  nav: { inicio: 'ホーム', obra: '実績', trayectoria: '経歴', contacto: 'お問い合わせ' },
  idioma: '言語',
  tema: { aClaro: 'ライトテーマに切り替え', aOscuro: 'ダークテーマに切り替え' },
  menu: { abrir: 'メニューを開く', cerrar: 'メニューを閉じる' },
  escribeme: 'ご連絡はこちら',
  tiendasConstruidas: (n: string) => `${n} 店舗を構築`,
  banda: '構築したストア',
  verObra: '実績を見る',
  verFicha: '詳細を見る',
  verTodaObra: 'すべての実績を見る',
  cvLabel: '履歴書をダウンロード',
  escena: { escritorio: 'デスクトップ', movil: 'モバイル' },
  obra: {
    h1: '実績',
    tipos: { todo: 'すべて', store: 'ストア', product: 'プロダクト', mas: 'その他' },
    filtrar: '種類で絞り込む',
    entregables: '各職務のなかの成果物',
  },
  kinds: { store: 'ストア', product: 'プロダクト', role: '成果物', personal: '個人プロジェクト' },
  ficha: {
    volver: '実績',
    visitar: 'サイトを見る',
    sitioDe: (n: string) => `${n}のサイト`,
    home: 'ホーム',
    pdp: '商品ページ',
    vista: '表示',
    datos: 'データ',
    rubro: '業種',
    rol: '役割',
    anio: '年',
    periodo: '期間',
    empleo: '勤務先',
    pila: '技術スタック',
    git: 'Git',
    commits: 'コミット',
    secciones: 'セクション',
    primerCommit: '最初のコミット',
    gitNota: (f: string) => `ストアのリポジトリより、${f} 時点。`,
    catalogo: 'カタログ',
    catalogoNota: (f: string) => `ストアの公開カタログ、${f} 時点。`,
    repo: 'コード',
    medido: '計測',
    lighthouse: 'Lighthouse',
    movil: 'モバイル',
    escritorio: 'デスクトップ',
    rend: 'パフォーマンス',
    acc: 'アクセシビリティ',
    seo: 'SEO',
    lhNota: (f: string) => `${f} のローカル計測、3回中の最良値。`,
    siguiente: '次の実績',
    noExiste: 'その実績は存在しません',
    volverObra: '実績に戻る',
  },
  tray: {
    h1: '経歴',
    hoy: '現在',
    segunCv: 'Max の履歴書より',
    cargos: '職歴',
    flotaNota: (f: string) => `各ストアの git 履歴より、${f} 時点。`,
  },
  contacto: {
    tienda: 'ストアのURL',
    tiendaEj: 'yourstore.com',
    correo: 'メールアドレス',
    correoEj: 'you@store.com',
    motivos: { revision: '20分の無料レビュー', proyecto: 'プロジェクトの構築', continuo: '継続的な業務', empleo: '採用' },
    motivo: 'ご用件',
    enviar: { revision: 'レビューを依頼する', proyecto: 'プロジェクトを相談する', continuo: '継続的な業務を相談する', empleo: '求人について連絡する' },
    enviando: '送信中',
    ok: '受け付けました。ご記入のメールアドレスに返信します。',
    error: '送信できませんでした。メールアプリが開き、メッセージが入力済みです。',
    falta: '有効なメールアドレスを入力してください。',
    faltaTienda: 'ストアのURLを入力してください。',
    elegir: 'このモデルを選ぶ',
    canalCorreo: 'メール',
    copiar: 'コピー',
    copiado: 'コピーしました',
    whatsapp: 'WhatsApp',
    waTexto: en.contacto.waTexto, // el mensaje llega a Max: se queda en inglés
    linkedin: 'LinkedIn',
    github: 'GitHub',
    cv: '履歴書 (PDF)',
    faq: 'ご連絡の前に',
  },
  pie: { medellin: 'コロンビア・メデジン', arriba: 'ページの先頭へ' },
}

export type Copy = typeof es
const DICCIONARIOS = { es, en, ja }
export const useCopy = (): Copy => DICCIONARIOS[useLanguage().locale]
