import { useLanguage } from '../../context/LanguageContext'
import type { ObraKind } from '../data'
import type { Motivo } from '../shared/contacto'

// Etiquetas de interfaz de la dirección «A la manera de Digitdeck» (es y en). El japonés cae a inglés hasta que Max elija
// dirección; las obras, cargos, FAQ y el héroe ya vienen en los tres idiomas desde useV5(). Nada de cifras aquí.
const es = {
  saltar: 'Saltar al contenido',
  marca: 'Max Bustamante',
  marcaAria: 'Max Bustamante, inicio',
  nav: { principal: 'Principal', inicio: 'Inicio', obra: 'Obra', trayectoria: 'Trayectoria', contacto: 'Contacto', menu: 'Menú', cerrar: 'Cerrar', cerrarMenu: 'Cerrar menú' },
  idioma: 'Idioma',
  flecha: 'a',
  medellin: (hora: string) => `Medellín, ${hora}`,
  cursorVer: 'Ver obra',
  volverArriba: 'Volver arriba',
  whatsapp: 'Escríbeme por WhatsApp (abre una pestaña nueva)',
  hero: {
    pausar: 'Pausar el movimiento',
    reanudar: 'Reanudar el movimiento',
    cinta: 'Tiendas construidas: capturas reales',
    abrir: (nombre: string) => `Abrir la ficha de ${nombre}`,
  },
  obra: {
    titulo: 'Obra',
    verTodo: 'Ver toda la obra',
    lede: 'Tiendas, productos y proyectos. Cada uno con su historia, lo que se hizo y, cuando existe, su captura real.',
    ledeInicio: 'Una selección. Cada obra tiene su historia, lo que se construyó y su captura real.',
    filtros: 'Filtrar por tipo',
    todo: 'Todo',
    tiendas: 'Tiendas',
    productos: 'Productos',
    mas: 'Proyectos',
    cuenta: (i: number, n: number) => `${String(i).padStart(2, '0')}/${String(n).padStart(2, '0')}`,
    vacio: 'Nada con ese filtro',
    sinCaptura: 'Sin captura',
    abrirCaso: 'Abrir el caso',
    nombreDe: (n: number) => `Nº ${String(n).padStart(2, '0')}`,
    fechaCapturas: (f: string) => `Capturas reales del ${f}.`,
    escenario: 'Vista previa de la obra enfocada',
    tipos: { store: 'Tienda', product: 'Producto', role: 'Entregable', personal: 'Proyecto propio' } satisfies Record<ObraKind, string>,
  },
  proceso: {
    titulo: 'Cómo trabajo',
    paso: (i: number, n: number) => `Paso ${i} de ${n}`,
    recibes: 'Recibes',
    ejemplo: (nombre: string) => `Ejemplo real: ${nombre}`,
  },
  cierre: { titulo: 'Cuéntame de tu tienda' },
  cargos: { ver: 'Ver la trayectoria completa', actual: 'Actual' },
  ficha: {
    volver: 'Volver a la obra',
    visitar: 'Visitar el sitio',
    vistas: 'Vista de la captura',
    home: 'Home',
    pdp: 'Producto',
    escritorio: 'Escritorio',
    movil: 'Móvil',
    ficha: 'Ficha',
    rubro: 'Rubro',
    rol: 'Trabajo',
    periodo: 'Periodo',
    pila: 'Pila',
    hechos: 'Hechos',
    historia: 'La historia',
    medido: 'Medido',
    cifrasCv: (empresa: string, periodo: string) => `Cifras del CV de Max · ${empresa}, ${periodo}`,
    catalogo: 'Catálogo',
    catalogoValor: (p: number, c: number | null) => `${p} productos${c != null ? ` · ${c} colecciones` : ''}`,
    productosU: 'productos',
    coleccionesU: 'colecciones',
    catalogoNota: (f: string) => `endpoints públicos, ${f}`,
    lighthouse: 'Lighthouse',
    lhNota: (f: string) => `medición local del ${f}, mejor de 3`,
    lhMovil: 'Móvil',
    lhEscritorio: 'Escritorio',
    rend: 'Rendimiento',
    acc: 'Accesibilidad',
    seo: 'SEO',
    anterior: 'Anterior',
    siguiente: 'Siguiente',
    noExiste: 'Esa obra no está en la lista',
    ver: 'Ver toda la obra',
  },
  trayectoria: {
    titulo: 'Trayectoria',
    hoy: 'Hoy',
    cargos: 'Cargos',
    porAnio: 'Por año',
    segunCv: 'Cifras según el CV de Max, atribuidas al cargo y al periodo.',
    cv: 'Descargar CV',
    stack: 'Stack',
    queSeEntrego: 'Qué se entregó',
  },
  contacto: {
    titulo: 'Escríbeme',
    tienda: 'URL de tu tienda',
    tiendaEjemplo: 'tutienda.com',
    correo: 'Tu correo',
    motivo: 'Motivo',
    mensaje: 'Mensaje',
    enviar: 'Enviar',
    enviando: 'Enviando…',
    ok: 'Recibí tu mensaje. Te respondo por correo.',
    error: 'No se pudo enviar: se abrió tu correo con el mensaje listo.',
    correoInvalido: 'Revisa el correo.',
    canales: 'Canales directos',
    copiar: 'Copiar correo',
    copiado: 'Correo copiado',
    whatsapp: 'WhatsApp',
    linkedin: 'LinkedIn',
    cv: 'Descargar CV',
    preguntas: 'Preguntas frecuentes',
    elegir: 'Escribir sobre esto',
    motivos: { revision: 'Revisión gratis de 20 minutos', proyecto: 'Construir un proyecto', continuo: 'Trabajo continuo', empleo: 'Empleo' } satisfies Record<Motivo, string>,
    preset: {
      revision: 'Quiero la revisión gratis de 20 minutos de mi tienda.',
      proyecto: 'Quiero construir un proyecto en Shopify. Esto es lo que necesito: ',
      continuo: 'Busco trabajo continuo sobre mi tienda. Esto es lo que quiero mejorar: ',
      empleo: 'Te escribo por una oportunidad de empleo: ',
    } satisfies Record<Motivo, string>,
  },
  noEncontrada: { titulo: 'No encontré esa página', volver: 'Volver al inicio' },
}

export type Copy = typeof es

const en: Copy = {
  saltar: 'Skip to content',
  marca: 'Max Bustamante',
  marcaAria: 'Max Bustamante, home',
  nav: { principal: 'Main', inicio: 'Home', obra: 'Work', trayectoria: 'Career', contacto: 'Contact', menu: 'Menu', cerrar: 'Close', cerrarMenu: 'Close menu' },
  idioma: 'Language',
  flecha: 'to',
  medellin: (hora) => `Medellín, ${hora}`,
  cursorVer: 'View work',
  volverArriba: 'Back to top',
  whatsapp: 'Message me on WhatsApp (opens a new tab)',
  hero: {
    pausar: 'Pause the motion',
    reanudar: 'Resume the motion',
    cinta: 'Built storefronts: real captures',
    abrir: (nombre) => `Open the page for ${nombre}`,
  },
  obra: {
    titulo: 'Work',
    verTodo: 'See all work',
    lede: 'Storefronts, products and projects. Each with its story, what was done and, where one exists, its real capture.',
    ledeInicio: 'A selection. Each work has its story, what was built and its real capture.',
    filtros: 'Filter by type',
    todo: 'All',
    tiendas: 'Storefronts',
    productos: 'Products',
    mas: 'Projects',
    cuenta: (i, n) => `${String(i).padStart(2, '0')}/${String(n).padStart(2, '0')}`,
    vacio: 'Nothing under that filter',
    sinCaptura: 'No capture',
    abrirCaso: 'Open the case',
    nombreDe: (n) => `No. ${String(n).padStart(2, '0')}`,
    fechaCapturas: (f) => `Real captures from ${f}.`,
    escenario: 'Preview of the focused work',
    tipos: { store: 'Storefront', product: 'Product', role: 'Deliverable', personal: 'Own project' },
  },
  proceso: {
    titulo: 'How I work',
    paso: (i, n) => `Step ${i} of ${n}`,
    recibes: 'You get',
    ejemplo: (nombre) => `Real example: ${nombre}`,
  },
  cierre: { titulo: 'Tell me about your store' },
  cargos: { ver: 'See the full career', actual: 'Current' },
  ficha: {
    volver: 'Back to the work',
    visitar: 'Visit the site',
    vistas: 'Capture view',
    home: 'Home',
    pdp: 'Product',
    escritorio: 'Desktop',
    movil: 'Mobile',
    ficha: 'Sheet',
    rubro: 'Industry',
    rol: 'Work',
    periodo: 'Period',
    pila: 'Stack',
    hechos: 'Facts',
    historia: 'The story',
    medido: 'Measured',
    cifrasCv: (empresa, periodo) => `Figures from Max’s CV · ${empresa}, ${periodo}`,
    catalogo: 'Catalog',
    catalogoValor: (p, c) => `${p} products${c != null ? ` · ${c} collections` : ''}`,
    productosU: 'products',
    coleccionesU: 'collections',
    catalogoNota: (f) => `public endpoints, ${f}`,
    lighthouse: 'Lighthouse',
    lhNota: (f) => `local run on ${f}, best of 3`,
    lhMovil: 'Mobile',
    lhEscritorio: 'Desktop',
    rend: 'Performance',
    acc: 'Accessibility',
    seo: 'SEO',
    anterior: 'Previous',
    siguiente: 'Next',
    noExiste: 'That work is not in the list',
    ver: 'See all work',
  },
  trayectoria: {
    titulo: 'Career',
    hoy: 'Today',
    cargos: 'Roles',
    porAnio: 'By year',
    segunCv: 'Figures from Max’s CV, attributed to the role and the period.',
    cv: 'Download CV',
    stack: 'Stack',
    queSeEntrego: 'What shipped',
  },
  contacto: {
    titulo: 'Get in touch',
    tienda: 'Your store URL',
    tiendaEjemplo: 'yourstore.com',
    correo: 'Your email',
    motivo: 'Reason',
    mensaje: 'Message',
    enviar: 'Send',
    enviando: 'Sending…',
    ok: 'I got your message. I will reply by email.',
    error: 'It could not be sent: your email app opened with the message ready.',
    correoInvalido: 'Check the email.',
    canales: 'Direct channels',
    copiar: 'Copy email',
    copiado: 'Email copied',
    whatsapp: 'WhatsApp',
    linkedin: 'LinkedIn',
    cv: 'Download CV',
    preguntas: 'Frequently asked questions',
    elegir: 'Write about this',
    motivos: { revision: 'Free 20-minute review', proyecto: 'Build a project', continuo: 'Ongoing work', empleo: 'Hiring' },
    preset: {
      revision: 'I would like the free 20-minute review of my store.',
      proyecto: 'I want to build a project on Shopify. This is what I need: ',
      continuo: 'I am looking for ongoing work on my store. This is what I want to improve: ',
      empleo: 'I am writing about a job opportunity: ',
    },
  },
  noEncontrada: { titulo: 'I could not find that page', volver: 'Back to home' },
}

export function useCopy(): Copy {
  const { locale } = useLanguage()
  return locale === 'es' ? es : en
}
