import { useLanguage } from '../../context/LanguageContext'
import type { Motivo } from './medicion'

// Textos de interfaz de la dirección K (es y en). El japonés cae a inglés hasta que Max elija dirección; los textos
// del registro (hero, cargos, obras, FAQ, contacto) ya vienen en los tres idiomas desde useV5().
// Reglas de copy: nada de plazos, garantías, métodos de pago ni cifras que no salgan de los datos.

const es = {
  saltar: 'Saltar al contenido',
  idioma: 'Idioma',
  medellin: 'Medellín',
  pedir: 'Pedir revisión',
  pedirNota: 'Gratis, 20 minutos. Sin discurso de venta ni contrato.',
  nav: { aria: 'Principal', inicio: 'Inicio', obra: 'Obra', trayectoria: 'Trayectoria', contacto: 'Contacto', cv: 'CV', menu: 'Menú', cerrarMenu: 'Cerrar menú', barra: 'Atajos' },
  capa: { aria: 'Capa sobre la línea', etiqueta: 'Capa sobre la línea', piel: 'Piel', esqueleto: 'Esqueleto', medicion: 'Medición' },
  vistas: { home: 'inicio', pdp: 'producto' },
  placa: {
    aria: (n: string) => `Placa de ${n}: radiografía de la página completa`,
    alt: (n: string, v: string, f: string) => `Captura de página completa de ${n}, ${v === 'home' ? 'inicio' : 'producto'}, ${f}`,
    isla: 'isla',
    medida: 'medida',
    asa: 'Línea de escaneo',
    ayuda: 'Flechas arriba y abajo cambian de sección; Inicio y Fin van a la primera y a la última.',
    arrastra: 'Arrastra la línea',
    leyAsa: 'línea',
    leySec: 'sección',
    leyMed: 'medido ×N',
    anterior: 'Sección anterior',
    siguiente: 'Sección siguiente',
    bloquear: 'Bloquear scroll',
    desbloquear: 'Volver al scroll',
  },
  insp: {
    aria: 'Inspector: secciones en orden de página',
    titulo: (v: string) => `Inspector · ${v}`,
    resumen: (s: string, i: string, m: string, a: string) => `${s} secciones · ${i} islas · ${m} medidos · ${a} px`,
    clave: 'Clave',
    alto: 'Alto',
    isla: 'Isla',
    siIsla: 'isla',
    medicion: 'Medición',
    medida: 'medida',
    cajones: (n: number) => `${n} cajones`,
    prov: (f: string, tema: string, dom: string, caj: number) =>
      `Medido el ${f} en el tema público «${tema}» de ${dom}. Isla = data-island montada${caj ? `, incluye ${caj} cajones` : ''}.`,
  },
  inicio: {
    titulo: 'Maximiliano Bustamante · Radiografía de tiendas Shopify',
    meta: (n: string) => `Medellín · ${n} tiendas construidas`,
    comoSeLee: 'Cómo se lee',
    comoSeLeeTexto: 'Arrastra la línea sobre la página completa: arriba, cómo está hecha; abajo, cómo la ve el cliente.',
    placaTitulo: (n: string, nombre: string) => `Placa ${n} · ${nombre} · inicio`,
    regleta: 'Regleta',
    regletaNota: (f: string) => `Medidas en su tema público el ${f}. Una barra por sección; el grosor es la altura.`,
    regletaAria: 'Tiendas medidas',
  },
  regleta: { secciones: (n: number) => `${n} secciones` },
  obra: {
    titulo: 'Obra · Radiografía de tiendas Shopify',
    h1: 'Tiendas medidas por dentro',
    bajada: 'Cada placa es una tienda tal como la ve el cliente y tal como está hecha: secciones, islas y elementos medidos en su DOM público. Las que no tienen radiografía lo dicen, y por qué.',
    filtrar: 'Filtrar obra',
    filtrarN: (n: number) => (n ? `Filtrar · ${n} activos` : 'Filtrar'),
    capa: 'Capa',
    conRadiografia: 'Con radiografía',
    soloPiel: 'Solo piel',
    rubro: 'Rubro',
    anio: 'Año',
    rol: 'Rol',
    pieza: 'Pieza',
    orden: 'Orden',
    ordenAnio: 'Año',
    ordenNombre: 'Nombre',
    ordenSecciones: 'Secciones',
    todas: 'Todas',
    mostrando: (n: number, t: number) => `Mostrando ${n} de ${t}`,
    limpiar: 'Limpiar',
    vacio: 'Ninguna tienda con esos filtros.',
    sinCaptura: 'Sin captura',
    medidas: (s: string, i: string, m: string, f: string) => `${s} secciones · ${i} islas · ${m} medidos · ${f}`,
    otras: 'Productos y proyectos',
  },
  motivos: {
    cliente: 'Tema del cliente: sin radiografía',
    tercero: 'Base de terceros: sin radiografía',
    sinMarcas: 'Sin radiografía: el tema público no lleva la medición de Digitdeck',
    sinDominio: 'Sin dominio público: sin radiografía',
  } satisfies Record<Motivo, string>,
  tipos: { store: 'Tienda', product: 'Producto', personal: 'Proyecto', role: 'Entregable' },
  ficha: {
    noExiste: 'Esa obra no está en el índice',
    volver: 'Volver a la obra',
    titulo: (n: string) => `${n} · Radiografía · Maximiliano Bustamante`,
    vista: 'Página',
    dispositivo: 'Dispositivo',
    escritorio: 'Escritorio',
    movil: 'Móvil',
    placaTitulo: (n: string, nombre: string, v: string) => `Placa ${n} · ${nombre} · ${v}`,
    migas: 'Ruta',
    anterior: 'Placa anterior',
    siguiente: 'Placa siguiente',
    sinRadiografia: 'Piel · sin radiografía',
    captura: 'Captura',
  },
  datos: {
    registro: 'registro de obra',
    rubro: 'Rubro',
    rol: 'Rol',
    tipo: 'Tipo',
    pila: 'Pila',
    git: 'Git',
    secciones: 'secciones',
    gitNota: (mes: string) => `del repo de la tienda, a ${mes}`,
    lighthouse: 'Lighthouse',
    movil: 'Móvil',
    acc: 'A11y',
    rend: 'Rend.',
    lhNota: (f: string) => `local, mejor de 3 · ${f}`,
    catalogo: 'Catálogo',
    catalogoValor: (p: number, c: number) => `${p} productos · ${c} colecciones`,
    catalogoNota: 'catálogo público',
    hecho: 'Hecho',
    sitio: 'Sitio',
    sitioNota: 'se abre en otra pestaña',
  },
  tray: {
    titulo: 'Trayectoria · Maximiliano Bustamante',
    h1: 'Los cargos, capa por capa',
    bajada: (n: number) => `${n} cargos, del más reciente al más antiguo. Cada capa dice empresa y periodo; ábrela para ver stack, logros y entregables. En el núcleo, el alto de cada tramo son los meses del cargo (el que está en curso queda abierto) y la línea marca el abierto.`,
    meses: (m: number) => `${m} meses`,
    desde: 'en curso',
    stack: 'Stack',
    logros: 'Qué se entregó',
    metricas: 'Cifras',
    segunCv: 'Según el CV de Max.',
    entregables: 'Entregables',
  },
  contacto: {
    titulo: 'Contacto · Revisión gratis de 20 minutos',
    correo: 'Correo',
    motivo: 'Motivo',
    mensaje: 'Mensaje',
    enviar: 'Enviar',
    enviando: 'Enviando',
    atras: 'Volver',
    ok: 'Recibido. Te escribo al correo que dejaste.',
    error: 'No se pudo enviar. Se abrió tu correo con el mensaje listo.',
    canales: 'Directo',
    copiado: 'Copiado',
    copiar: 'Copiar',
    textoListo: 'Con texto listo',
    llamadas: 'Llamadas',
    llamar: 'Llamar',
    abrir: 'Abrir',
    mira: 'Qué miro en 20 minutos',
    moverLinea: 'Llevar la línea aquí',
    puntos: {
      velocidad: { titulo: 'Velocidad', texto: 'Qué tarda en verse lo primero y qué pesa hasta ahí.' },
      ofertas: { titulo: 'Ofertas', texto: 'Cómo se presentan el descuento y el combo antes de llegar al carrito.' },
      checkout: { titulo: 'Fricción en el checkout', texto: 'Qué se interpone entre el carrito y el pedido.' },
    },
    dondeSeVe: (k: string, m: string) => `En la placa de NOS Café: ${k} · ${m}`,
    cajon: 'cajón',
    verPlaca: 'Ver la placa de NOS Café',
    noPromete: 'En la revisión miro tu tienda con esta misma lente. Esta página no la radiografía sola.',
    faq: 'Preguntas frecuentes',
    waTexto: 'Hola Max, quiero la revisión gratis de 20 minutos de mi tienda: ',
    presets: {
      revision: 'Quiero la revisión gratis de 20 minutos de mi tienda.',
      proyecto: 'Quiero construir un proyecto. Esto es lo que tengo en mente: ',
      continuo: 'Busco quien mantenga la ingeniería de mi tienda. Hoy tenemos: ',
      empleo: 'Te escribo por una vacante: ',
    },
  },
}

const en: typeof es = {
  saltar: 'Skip to content',
  idioma: 'Language',
  medellin: 'Medellín',
  pedir: 'Book a review',
  pedirNota: 'Free, 20 minutes. No sales pitch, no contract.',
  nav: { aria: 'Main', inicio: 'Home', obra: 'Work', trayectoria: 'Career', contacto: 'Contact', cv: 'CV', menu: 'Menu', cerrarMenu: 'Close menu', barra: 'Shortcuts' },
  capa: { aria: 'Layer above the line', etiqueta: 'Layer above the line', piel: 'Skin', esqueleto: 'Skeleton', medicion: 'Measured' },
  vistas: { home: 'home', pdp: 'product' },
  placa: {
    aria: (n: string) => `Plate of ${n}: full-page X-ray`,
    alt: (n: string, v: string, f: string) => `Full-page capture of ${n}, ${v === 'home' ? 'home' : 'product'} page, ${f}`,
    isla: 'island',
    medida: 'measured',
    asa: 'Scan line',
    ayuda: 'Up and down arrows change section; Home and End jump to the first and the last.',
    arrastra: 'Drag the line',
    leyAsa: 'line',
    leySec: 'section',
    leyMed: 'measured ×N',
    anterior: 'Previous section',
    siguiente: 'Next section',
    bloquear: 'Lock scroll',
    desbloquear: 'Back to scroll',
  },
  insp: {
    aria: 'Inspector: sections in page order',
    titulo: (v: string) => `Inspector · ${v}`,
    resumen: (s: string, i: string, m: string, a: string) => `${s} sections · ${i} islands · ${m} measured · ${a} px`,
    clave: 'Key',
    alto: 'Height',
    isla: 'Island',
    siIsla: 'island',
    medicion: 'Measured',
    medida: 'measured',
    cajones: (n: number) => `${n} drawers`,
    prov: (f: string, tema: string, dom: string, caj: number) =>
      `Measured on ${f} in the public theme «${tema}» of ${dom}. Island = a mounted data-island${caj ? `, includes ${caj} drawers` : ''}.`,
  },
  inicio: {
    titulo: 'Maximiliano Bustamante · X-ray of Shopify stores',
    meta: (n: string) => `Medellín · ${n} stores built`,
    comoSeLee: 'How to read it',
    comoSeLeeTexto: 'Drag the line over the full page: above it, how it is built; below it, how the customer sees it.',
    placaTitulo: (n: string, nombre: string) => `Plate ${n} · ${nombre} · home`,
    regleta: 'Ruler',
    regletaNota: (f: string) => `Measured on their public theme on ${f}. One bar per section; thickness is height.`,
    regletaAria: 'Measured stores',
  },
  regleta: { secciones: (n: number) => `${n} sections` },
  obra: {
    titulo: 'Work · X-ray of Shopify stores',
    h1: 'Stores, measured inside',
    bajada: 'Each plate is a store as the customer sees it and as it is built: sections, islands and elements measured on its public DOM. The ones without an X-ray say so, and why.',
    filtrar: 'Filter work',
    filtrarN: (n: number) => (n ? `Filter · ${n} active` : 'Filter'),
    capa: 'Layer',
    conRadiografia: 'With X-ray',
    soloPiel: 'Skin only',
    rubro: 'Industry',
    anio: 'Year',
    rol: 'Role',
    pieza: 'Piece',
    orden: 'Sort',
    ordenAnio: 'Year',
    ordenNombre: 'Name',
    ordenSecciones: 'Sections',
    todas: 'All',
    mostrando: (n: number, t: number) => `Showing ${n} of ${t}`,
    limpiar: 'Clear',
    vacio: 'No store matches these filters.',
    sinCaptura: 'No capture',
    medidas: (s: string, i: string, m: string, f: string) => `${s} sections · ${i} islands · ${m} measured · ${f}`,
    otras: 'Products and projects',
  },
  motivos: {
    cliente: "Client's theme: no X-ray",
    tercero: 'Third-party base: no X-ray',
    sinMarcas: "No X-ray: the public theme does not carry Digitdeck's measurement",
    sinDominio: 'No public domain: no X-ray',
  },
  tipos: { store: 'Store', product: 'Product', personal: 'Project', role: 'Deliverable' },
  ficha: {
    noExiste: 'That work is not in the index',
    volver: 'Back to work',
    titulo: (n: string) => `${n} · X-ray · Maximiliano Bustamante`,
    vista: 'Page',
    dispositivo: 'Device',
    escritorio: 'Desktop',
    movil: 'Mobile',
    placaTitulo: (n: string, nombre: string, v: string) => `Plate ${n} · ${nombre} · ${v}`,
    migas: 'Path',
    anterior: 'Previous plate',
    siguiente: 'Next plate',
    sinRadiografia: 'Skin · no X-ray',
    captura: 'Capture',
  },
  datos: {
    registro: 'work record',
    rubro: 'Industry',
    rol: 'Role',
    tipo: 'Type',
    pila: 'Stack',
    git: 'Git',
    secciones: 'sections',
    gitNota: (mes: string) => `from the store repo, as of ${mes}`,
    lighthouse: 'Lighthouse',
    movil: 'Mobile',
    acc: 'A11y',
    rend: 'Perf.',
    lhNota: (f: string) => `local, best of 3 · ${f}`,
    catalogo: 'Catalog',
    catalogoValor: (p: number, c: number) => `${p} products · ${c} collections`,
    catalogoNota: 'public catalog',
    hecho: 'Fact',
    sitio: 'Site',
    sitioNota: 'opens in a new tab',
  },
  tray: {
    titulo: 'Career · Maximiliano Bustamante',
    h1: 'The roles, layer by layer',
    bajada: (n: number) => `${n} roles, newest to oldest. Each layer states the company and the period; open it for the stack, what shipped and the deliverables. In the core, the height of each stretch is the months of the role (the ongoing one stays open) and the line marks the open one.`,
    meses: (m: number) => `${m} months`,
    desde: 'ongoing',
    stack: 'Stack',
    logros: 'What shipped',
    metricas: 'Figures',
    segunCv: "According to Max's CV.",
    entregables: 'Deliverables',
  },
  contacto: {
    titulo: 'Contact · Free 20-minute review',
    correo: 'Email',
    motivo: 'Reason',
    mensaje: 'Message',
    enviar: 'Send',
    enviando: 'Sending',
    atras: 'Back',
    ok: 'Received. I will write to the email you left.',
    error: 'It could not be sent. Your email app opened with the message ready.',
    canales: 'Direct',
    copiado: 'Copied',
    copiar: 'Copy',
    textoListo: 'Text ready',
    llamadas: 'Calls',
    llamar: 'Call',
    abrir: 'Open',
    mira: 'What I look at in 20 minutes',
    moverLinea: 'Move the line here',
    puntos: {
      velocidad: { titulo: 'Speed', texto: 'How long the first thing takes to show and what it weighs until then.' },
      ofertas: { titulo: 'Offers', texto: 'How the discount and the bundle are presented before the cart.' },
      checkout: { titulo: 'Checkout friction', texto: 'What stands between the cart and the order.' },
    },
    dondeSeVe: (k: string, m: string) => `On the NOS Café plate: ${k} · ${m}`,
    cajon: 'drawer',
    verPlaca: 'See the NOS Café plate',
    noPromete: 'In the review I look at your store through this same lens. This page does not X-ray it on its own.',
    faq: 'Frequently asked questions',
    waTexto: "Hi Max, I'd like the free 20-minute review of my store: ",
    presets: {
      revision: 'I want the free 20-minute review of my store.',
      proyecto: 'I want to build a project. Here is what I have in mind: ',
      continuo: 'I am looking for someone to maintain my store engineering. Today we have: ',
      empleo: 'I am writing about an opening: ',
    },
  },
}

const COPY = { es, en }
export type Copy = typeof es

/** Textos de la dirección K en el idioma activo (ja cae a en). */
export function useCopy(): Copy {
  const { locale } = useLanguage()
  return COPY[locale === 'es' ? 'es' : 'en']
}
