// Etiquetas de interfaz de la dirección C (es y en). El japonés cae a inglés hasta que Max elija dirección (Q12).
// Cifras, nombres y textos de marca NO viven aquí: salen de useV5().

const es = {
  saltar: 'Saltar al contenido',
  marca: 'Maximiliano Bustamante, inicio',
  idioma: { aria: 'Idioma', nota: 'Las etiquetas de esta dirección todavía no están en japonés y se muestran en inglés.' },
  nav: { aria: 'Principal', obra: 'Obra', trayectoria: 'Trayectoria', contacto: 'Contacto', menu: 'Menú' },
  vista: { aria: 'Vista', lectura: 'Lectura', mesa: 'Mesa' },
  por: { aria: 'Disposición', rubro: 'Por rubro', tec: 'Por tecnología', anio: 'Por año' },
  tipos: { store: 'Tienda', product: 'Producto', personal: 'Proyecto personal', role: 'Entregable de un cargo' } as Record<string, string>,
  producto: 'Producto propio',
  vistas: { home: 'home', pdp: 'página de producto' },
  vps: { desktop: 'escritorio', mobile: 'móvil' },
  pieVista: { home: 'Home', pdp: 'PDP' },
  capturaAlt: (nombre: string, vista: string, vp: string, fecha: string) => `${nombre}, ${vista}, ${vp}, captura del ${fecha}`,
  pedir: 'Pedir revisión',
  revisionNota: 'Revisión gratis de 20 minutos.',
  inicio: {
    calco: 'CALCO 01 · LECTURA',
    apoyo: (n: string) => `${n} tiendas construidas, una suite de apps y el sistema que las entrega.`,
    cifras: 'La hoja de contactos en cifras',
    tiendas: 'Tiendas con captura',
    diapositivas: 'Diapositivas',
    captura: 'Captura',
    taller: 'Taller',
    tallerValor: 'Medellín',
    sello: 'Lectura',
    hoja: (obras: number, slides: number) => `${obras} obras · ${slides} diapositivas`,
    abrirMesa: 'Abrir la mesa',
    abrirMesaNota: 'Arrastra, pellizca y acerca',
    leadLectura: (fecha: string) => `Capturas reales del ${fecha}, agrupadas a tu gusto. Cada fila lleva a su ficha.`,
    cinta: 'Saltar a un año',
    sinCapturas: 'sin capturas',
    capturasDe: (n: string) => `Capturas de ${n}`,
    cuenta: (n: number, tiendas: boolean) => (tiendas ? (n === 1 ? '1 tienda' : `${n} tiendas`) : n === 1 ? '1 obra' : `${n} obras`),
  },
  obra: {
    calco: 'CALCO 02 · OBRA',
    titulo: 'Obra',
    lead: (fecha: string) => `Tiendas, productos y proyectos, del más reciente al más antiguo. Capturas del ${fecha}.`,
    filtros: 'Filtros',
    filtrar: 'Filtrar',
    tipo: 'Tipo',
    anio: 'Año',
    rol: 'Rol',
    tec: 'Tecnología',
    mostrando: (n: number) => `Mostrando ${n}`,
    limpiar: 'Limpiar',
    vacio: 'Ninguna obra coincide con esos filtros.',
    verMesa: 'Ver en la mesa',
    sinCaptura: 'Sin captura pública: solo ficha de datos.',
  },
  ficha: {
    calco: 'CALCO 03 · FICHA',
    navegacion: 'Navegación entre obras',
    volver: 'Obra',
    rol: 'Rol',
    anio: 'Año',
    construccion: 'Construcción',
    pila: 'Pila',
    hechos: 'Hechos',
    medido: 'Medido',
    git: (commits: number, secciones: number, fecha: string) => `${commits} commits · ${secciones} secciones, de los repos de las tiendas, a ${fecha}`,
    lh: 'Lighthouse',
    lhNota: (fecha: string) => `Medición local, mejor de 3, ${fecha}`,
    movil: 'Móvil',
    escritorio: 'Escritorio',
    rendimiento: 'Rendimiento',
    accesibilidad: 'Accesibilidad',
    seo: 'SEO',
    abrir: 'Ver la tienda',
    abrirSitio: 'Abrir el sitio',
    nuevaPestana: 'se abre en una pestaña nueva',
    verMesa: 'Ver en la mesa',
    anterior: 'Anterior',
    siguiente: 'Siguiente',
    sinCaptura: 'Esta obra no tiene captura pública: se muestra solo su ficha de datos.',
    noExiste: 'No hay una obra con ese nombre',
    numero: (nr: string) => `Nº ${nr}`,
  },
  trayectoria: {
    calco: 'CALCO 04 · TRAYECTORIA',
    titulo: 'Trayectoria',
    h1: 'Cargos y trabajo, año por año',
    lead: 'Cada cargo con su periodo en texto. Las cifras son del CV de Max y van atribuidas.',
    segunCv: (periodo: string) => `Según el CV de Max, ${periodo}`,
    entregables: 'Entregables',
    tiendasDe: (y: number) => `Tiendas de ${y}`,
    sinObra: 'Sin tiendas registradas ese año',
  },
  contacto: {
    calco: 'CALCO 05 · CONTACTO',
    brief: 'Arma tu mensaje',
    briefLead: 'Elige lo que te interesa y el mensaje se arma solo. No se envía nada hasta que lo mandes.',
    motivo: 'Motivo',
    correo: 'Tu correo',
    enviar: 'Enviar',
    enviando: 'Enviando',
    ok: 'Mensaje enviado. Gracias.',
    error: 'No se pudo enviar: se abrió tu correo con el mensaje listo.',
    interes: (fichas: string) => `Me interesa: ${fichas}.`,
    directo: 'Directo',
    copiar: 'Copiar correo',
    copiado: 'Correo copiado',
    whatsapp: 'Escribir por WhatsApp',
    correoLink: 'Escribir por correo',
    llamar: 'Llamar',
    linkedin: 'LinkedIn',
    hora: (h: string) => `Ahora en Medellín: ${h}`,
    waTexto: (fichas: string) => (fichas ? `Hola Max, me interesa: ${fichas}. Mi tienda: ` : 'Hola Max, quiero escribirte. Mi tienda: '),
    waAsunto: 'Mensaje desde tu portafolio',
    faq: 'Preguntas frecuentes',
  },
  mesa: {
    region: 'Mesa de luz: lienzo con las capturas de la obra',
    leyenda: 'Arrastra · pellizca · + − con la mesa enfocada · Ctrl + rueda acerca',
    teclas: 'Flechas mueven, + y − acercan, 0 encuadra todo, F enfoca la selección, L vuelve a la Lectura, Esc suelta.',
    salir: 'Salir de la mesa',
    camara: 'Cámara',
    acercar: 'Acercar',
    alejar: 'Alejar',
    verTodo: 'Ver todo',
    abriendo: 'Abriendo la mesa',
    soltar: 'Cerrar el visor',
    enfocar: 'Enfocar',
    abrirFicha: 'Abrir la ficha',
    anuncio: (por: string, n: number) => `${por} · ${n} grupos`,
    sinCapturas: (anio: string) => `Sin capturas de ${anio}`,
    paquete: (nombre: string, grupo: string) => `${nombre}, grupo ${grupo}`,
    copia: 'copia en otro grupo',
    visorDe: (n: string) => `Visor de ${n}`,
    vistasDe: 'Diapositiva a mostrar',
    nivel: 'Nivel de detalle',
    original: 'original',
    pista: 'Un dedo desplaza, dos dedos acercan. «Salir de la mesa» siempre está arriba.',
  },
  pie: { marca: 'Mesa de luz · prototipo de la dirección C' },
}

const en: typeof es = {
  saltar: 'Skip to content',
  marca: 'Maximiliano Bustamante, home',
  idioma: { aria: 'Language', nota: 'The labels of this direction are not translated to Japanese yet and show in English.' },
  nav: { aria: 'Main', obra: 'Work', trayectoria: 'Career', contacto: 'Contact', menu: 'Menu' },
  vista: { aria: 'View', lectura: 'Reading', mesa: 'Table' },
  por: { aria: 'Arrangement', rubro: 'By industry', tec: 'By technology', anio: 'By year' },
  tipos: { store: 'Store', product: 'Product', personal: 'Personal project', role: 'Deliverable inside a role' },
  producto: 'Own product',
  vistas: { home: 'home', pdp: 'product page' },
  vps: { desktop: 'desktop', mobile: 'mobile' },
  pieVista: { home: 'Home', pdp: 'PDP' },
  capturaAlt: (nombre, vista, vp, fecha) => `${nombre}, ${vista}, ${vp}, screenshot from ${fecha}`,
  pedir: 'Request a review',
  revisionNota: 'Free 20-minute review.',
  inicio: {
    calco: 'TRACING 01 · READING',
    apoyo: (n) => `${n} stores built, an app suite and the system that ships them.`,
    cifras: 'The contact sheet in numbers',
    tiendas: 'Stores captured',
    diapositivas: 'Slides',
    captura: 'Captured',
    taller: 'Studio',
    tallerValor: 'Medellín',
    sello: 'Reading',
    hoja: (obras, slides) => `${obras} works · ${slides} slides`,
    abrirMesa: 'Open the table',
    abrirMesaNota: 'Drag, pinch and zoom',
    leadLectura: (fecha) => `Real screenshots from ${fecha}, grouped your way. Each row leads to its case sheet.`,
    cinta: 'Jump to a year',
    sinCapturas: 'no screenshots',
    capturasDe: (n) => `Screenshots of ${n}`,
    cuenta: (n, tiendas) => (tiendas ? (n === 1 ? '1 store' : `${n} stores`) : n === 1 ? '1 work' : `${n} works`),
  },
  obra: {
    calco: 'TRACING 02 · WORK',
    titulo: 'Work',
    lead: (fecha) => `Stores, products and projects, newest first. Screenshots from ${fecha}.`,
    filtros: 'Filters',
    filtrar: 'Filter',
    tipo: 'Type',
    anio: 'Year',
    rol: 'Role',
    tec: 'Technology',
    mostrando: (n) => `Showing ${n}`,
    limpiar: 'Clear',
    vacio: 'No work matches those filters.',
    verMesa: 'See on the table',
    sinCaptura: 'No public screenshot: data sheet only.',
  },
  ficha: {
    calco: 'TRACING 03 · CASE SHEET',
    navegacion: 'Navigation between works',
    volver: 'Work',
    rol: 'Role',
    anio: 'Year',
    construccion: 'Build window',
    pila: 'Stack',
    hechos: 'Facts',
    medido: 'Measured',
    git: (commits, secciones, fecha) => `${commits} commits · ${secciones} sections, from the store repos, as of ${fecha}`,
    lh: 'Lighthouse',
    lhNota: (fecha) => `Local measurement, best of 3, ${fecha}`,
    movil: 'Mobile',
    escritorio: 'Desktop',
    rendimiento: 'Performance',
    accesibilidad: 'Accessibility',
    seo: 'SEO',
    abrir: 'Visit the store',
    abrirSitio: 'Open the site',
    nuevaPestana: 'opens in a new tab',
    verMesa: 'See on the table',
    anterior: 'Previous',
    siguiente: 'Next',
    sinCaptura: 'This work has no public screenshot: only its data sheet is shown.',
    noExiste: 'There is no work with that name',
    numero: (nr) => `No. ${nr}`,
  },
  trayectoria: {
    calco: 'TRACING 04 · CAREER',
    titulo: 'Career',
    h1: 'Roles and work, year by year',
    lead: "Each role with its period in text. The figures come from Max's CV and are attributed.",
    segunCv: (periodo) => `According to Max's CV, ${periodo}`,
    entregables: 'Deliverables',
    tiendasDe: (y) => `Stores of ${y}`,
    sinObra: 'No stores recorded that year',
  },
  contacto: {
    calco: 'TRACING 05 · CONTACT',
    brief: 'Build your message',
    briefLead: 'Pick what you are interested in and the message builds itself. Nothing is sent until you send it.',
    motivo: 'Reason',
    correo: 'Your email',
    enviar: 'Send',
    enviando: 'Sending',
    ok: 'Message sent. Thank you.',
    error: 'It could not be sent: your email app opened with the message ready.',
    interes: (fichas) => `I am interested in: ${fichas}.`,
    directo: 'Direct',
    copiar: 'Copy email',
    copiado: 'Email copied',
    whatsapp: 'Write on WhatsApp',
    correoLink: 'Write by email',
    llamar: 'Call',
    linkedin: 'LinkedIn',
    hora: (h) => `Medellín right now: ${h}`,
    waTexto: (fichas) => (fichas ? `Hi Max, I am interested in: ${fichas}. My store: ` : 'Hi Max, I would like to write to you. My store: '),
    waAsunto: 'Message from your portfolio',
    faq: 'Frequently asked questions',
  },
  mesa: {
    region: 'Light table: a canvas with the screenshots of the work',
    leyenda: 'Drag · pinch · + − with the table focused · Ctrl + wheel zooms',
    teclas: 'Arrows move, + and − zoom, 0 fits everything, F focuses the selection, L returns to Reading, Esc releases.',
    salir: 'Leave the table',
    camara: 'Camera',
    acercar: 'Zoom in',
    alejar: 'Zoom out',
    verTodo: 'Fit all',
    abriendo: 'Opening the table',
    soltar: 'Close the viewer',
    enfocar: 'Focus',
    abrirFicha: 'Open the case sheet',
    anuncio: (por, n) => `${por} · ${n} groups`,
    sinCapturas: (anio) => `No screenshots from ${anio}`,
    paquete: (nombre, grupo) => `${nombre}, group ${grupo}`,
    copia: 'copy in another group',
    visorDe: (n) => `Viewer of ${n}`,
    vistasDe: 'Slide to show',
    nivel: 'Level of detail',
    original: 'original',
    pista: 'One finger pans, two fingers zoom. “Leave the table” is always at the top.',
  },
  pie: { marca: 'Light table · prototype of direction C' },
}

export const copy = { es, en }
export type Copy = typeof es
