import { useLanguage } from '../../context/LanguageContext'

// Rótulos propios de la dirección. Los textos del portafolio (posicionamiento, cifras con su fuente, proceso, modelos de trabajo,
// FAQ, cargos, habilidades) NO se copian aquí: llegan de useV5().strings en el idioma activo.
const es = {
  saltar: 'Saltar al contenido',
  principal: 'Navegación principal',
  idioma: 'Idioma',
  abrirMenu: 'Abrir menú',
  cerrarMenu: 'Cerrar menú',
  nav: { inicio: 'Inicio', obra: 'Obra', trayectoria: 'Trayectoria', contacto: 'Contacto' },
  no: 'Nº',
  flecha: 'a',
  rango: 'a',
  verObra: 'Ver la obra',
  cv: 'Descargar CV',
  escala: { productos: 'Productos', colecciones: 'Colecciones', variantes: 'Variantes por producto', fuente: 'Catálogo público de la tienda, {fecha}' },
  inicio: {
    rollos: 'Tres tiendas colgadas',
    obraDestacada: 'Obra destacada',
    obraT: 'Lo que construí',
    otras: 'Más tiendas',
    verToda: 'Ver toda la obra',
    cierreSub: 'O escríbeme un correo',
    quien: 'Quién',
    ahora: 'Ahora',
    verTrayectoria: 'Ver la trayectoria completa',
    hoy: 'hoy',
  },
  obra: {
    titulo: 'Obra',
    lead: 'Tiendas Shopify construidas y migradas, los productos propios y los proyectos aparte: lo que ve el comprador y el trabajo que lo sostiene.',
    filtros: { todo: 'Todo', tiendas: 'Tiendas', productos: 'Productos', proyectos: 'Proyectos' },
    filtrar: 'Filtrar la obra',
    destacadas: 'Destacadas',
    resto: 'El resto de la obra',
    mas: 'Más obra',
    masLead: 'Sin captura pública todavía.',
    tempranas: 'Otras tiendas tempranas, sin captura pública',
    vacio: 'Nada en este filtro.',
  },
  ficha: {
    volver: 'Obra',
    historia: 'La historia',
    caso: 'El caso',
    reto: 'El reto',
    hice: 'Lo que hice',
    quedo: 'Lo que quedó',
    hoy: 'La tienda hoy',
    hoyTxt: 'Lo que dice hoy el catálogo público de la tienda.',
    info: 'Información',
    sector: 'Sector',
    rol: 'Rol',
    periodo: 'Periodo',
    anio: 'Año',
    pila: 'Pila',
    enlace: 'Enlace',
    repo: 'Repositorio',
    ver: 'Ver la tienda',
    verSitio: 'Abrir el sitio',
    visor: 'Visor de capturas',
    anterior: 'Captura anterior',
    siguiente: 'Captura siguiente',
    sinCaptura: 'Sin captura',
    proxima: 'Siguiente obra',
    vistas: { 'home-desktop': 'Inicio · escritorio', 'pdp-desktop': 'Producto · escritorio', 'home-mobile': 'Inicio · móvil', 'pdp-mobile': 'Producto · móvil' },
    medido: 'Medido, en segundo plano',
    noExiste: 'Esa obra no existe',
  },
  trayectoria: {
    titulo: 'Trayectoria',
    abrir: 'Hablemos',
    ahora: 'Ahora',
    abrirCargo: 'Abrir el cargo',
    cerrarCargo: 'Cerrar el cargo',
    uso: 'El número: en cuántas tiendas de esta página la pila nombra la herramienta.',
    contrato: { 'full-time': 'Tiempo completo', 'part-time': 'Medio tiempo', contract: 'Por contrato' } as Record<string, string>,
  },
  contacto: {
    titulo: 'Contacto',
    canales: 'Canales',
    correo: 'Correo',
    whatsapp: 'WhatsApp',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    cv: 'CV',
    copiar: 'Copiar',
    copiado: 'Copiado',
    formulario: 'Escríbeme',
    motivo: 'Cómo quieres que trabajemos',
    motivos: { revision: 'Revisión gratis de 20 minutos', proyecto: 'Construir un proyecto', continuo: 'Trabajo continuo', empleo: 'Empleo' } as Record<string, string>,
    empleoNota: 'Para una vacante o una entrevista.',
    tienda: 'La URL de tu tienda',
    tiendaEj: 'tutienda.com',
    tiendaFalta: 'Escribe la URL de tu tienda para la revisión.',
    correoL: 'Tu correo',
    correoEj: 'nombre@correo.com',
    correoFalta: 'Escribe un correo válido.',
    mensaje: 'Mensaje (opcional)',
    enviar: { revision: 'Pedir la revisión', proyecto: 'Contar mi proyecto', continuo: 'Hablar de trabajo continuo', empleo: 'Enviar mensaje' } as Record<string, string>,
    enviando: 'Enviando',
    ok: 'Recibido. Te respondo desde mi correo.',
    error: 'No se pudo enviar desde aquí; se abrió tu aplicación de correo con el mensaje listo.',
  },
  pie: { medellin: 'Medellín', volver: 'Volver arriba', derechos: '© 2026' },
  // El selector de temas: una palabra en la cabecera abre una fila de rollos, uno por tema, cada uno con su cartela.
  temas: { boton: 'Temas', titulo: 'Temas', sub: 'La misma obra, otra manera de recorrerla', lista: 'Temas del sitio', cerrar: 'Cerrar', cerrarAria: 'Cerrar los temas', actual: 'Tema actual', elegir: 'Elegir' },
}

type Copy = typeof es

const en: Copy = {
  saltar: 'Skip to content',
  principal: 'Main navigation',
  idioma: 'Language',
  abrirMenu: 'Open menu',
  cerrarMenu: 'Close menu',
  nav: { inicio: 'Home', obra: 'Work', trayectoria: 'Career', contacto: 'Contact' },
  no: 'No.',
  flecha: 'to',
  rango: 'to',
  verObra: 'See the work',
  cv: 'Download CV',
  escala: { productos: 'Products', colecciones: 'Collections', variantes: 'Variants per product', fuente: 'The store’s public catalog, {fecha}' },
  inicio: {
    rollos: 'Three stores, hanging',
    obraDestacada: 'Selected work',
    obraT: 'What I built',
    otras: 'More stores',
    verToda: 'See all work',
    cierreSub: 'Or write me an email',
    quien: 'Who',
    ahora: 'Now',
    verTrayectoria: 'See the full career',
    hoy: 'now',
  },
  obra: {
    titulo: 'Work',
    lead: 'Shopify stores built and migrated, my own products and side projects: what the shopper sees and the work that holds it up.',
    filtros: { todo: 'All', tiendas: 'Stores', productos: 'Products', proyectos: 'Projects' },
    filtrar: 'Filter the work',
    destacadas: 'Selected',
    resto: 'The rest of the work',
    mas: 'More work',
    masLead: 'No public capture yet.',
    tempranas: 'Other early stores, no public capture',
    vacio: 'Nothing under this filter.',
  },
  ficha: {
    volver: 'Work',
    historia: 'The story',
    caso: 'The case',
    reto: 'The challenge',
    hice: 'What I did',
    quedo: 'What stayed',
    hoy: 'The store today',
    hoyTxt: 'What the store’s public catalog says today.',
    info: 'Information',
    sector: 'Sector',
    rol: 'Role',
    periodo: 'Period',
    anio: 'Year',
    pila: 'Stack',
    enlace: 'Link',
    repo: 'Repository',
    ver: 'See the store',
    verSitio: 'Open the site',
    visor: 'Capture viewer',
    anterior: 'Previous capture',
    siguiente: 'Next capture',
    sinCaptura: 'No capture',
    proxima: 'Next work',
    vistas: { 'home-desktop': 'Home · desktop', 'pdp-desktop': 'Product · desktop', 'home-mobile': 'Home · mobile', 'pdp-mobile': 'Product · mobile' },
    medido: 'Measured, in the background',
    noExiste: 'That work does not exist',
  },
  trayectoria: {
    titulo: 'Career',
    abrir: 'Let’s talk',
    ahora: 'Now',
    abrirCargo: 'Open the role',
    cerrarCargo: 'Close the role',
    uso: 'The number: how many stores on this page list the tool in their stack.',
    contrato: { 'full-time': 'Full time', 'part-time': 'Part time', contract: 'Contract' },
  },
  contacto: {
    titulo: 'Contact',
    canales: 'Channels',
    correo: 'Email',
    whatsapp: 'WhatsApp',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    cv: 'CV',
    copiar: 'Copy',
    copiado: 'Copied',
    formulario: 'Write to me',
    motivo: 'How you would like us to work',
    motivos: { revision: 'Free 20-minute review', proyecto: 'Build a project', continuo: 'Ongoing work', empleo: 'Hiring' },
    empleoNota: 'For an opening or an interview.',
    tienda: 'Your store URL',
    tiendaEj: 'yourstore.com',
    tiendaFalta: 'Enter your store URL for the review.',
    correoL: 'Your email',
    correoEj: 'name@email.com',
    correoFalta: 'Enter a valid email.',
    mensaje: 'Message (optional)',
    enviar: { revision: 'Request the review', proyecto: 'Tell me about the project', continuo: 'Talk about ongoing work', empleo: 'Send message' },
    enviando: 'Sending',
    ok: 'Received. I will reply from my email.',
    error: 'It could not be sent from here; your mail app opened with the message ready.',
  },
  pie: { medellin: 'Medellín', volver: 'Back to top', derechos: '© 2026' },
  temas: { boton: 'Themes', titulo: 'Themes', sub: 'The same work, another way to walk through it', lista: 'Site themes', cerrar: 'Close', cerrarAria: 'Close themes', actual: 'Current theme', elegir: 'Choose' },
}

// Japonés: la interfaz completa; los textos del portafolio (posicionamiento, cifras, cargos, FAQ) llegan en japonés desde useV5().
const ja: Copy = {
  saltar: '本文へ移動',
  principal: 'メインナビゲーション',
  idioma: '言語',
  abrirMenu: 'メニューを開く',
  cerrarMenu: 'メニューを閉じる',
  nav: { inicio: 'ホーム', obra: '制作', trayectoria: '経歴', contacto: '連絡' },
  no: 'No.',
  flecha: 'から',
  rango: 'から',
  verObra: '制作を見る',
  cv: '履歴書をダウンロード',
  escala: { productos: '商品数', colecciones: 'コレクション数', variantes: '商品あたりのバリエーション', fuente: 'ストアの公開カタログ、{fecha}' },
  inicio: {
    rollos: '掛け軸のように並べた3つのストア',
    obraDestacada: '主な制作',
    obraT: '手がけたもの',
    otras: 'そのほかのストア',
    verToda: '制作をすべて見る',
    cierreSub: 'またはメールで',
    quien: 'プロフィール',
    ahora: '現在',
    verTrayectoria: '経歴をすべて見る',
    hoy: '現在',
  },
  obra: {
    titulo: '制作',
    lead: '構築・移行したShopifyストア、自社プロダクト、個人プロジェクト。購入者に見える部分と、それを支える仕事です。',
    filtros: { todo: 'すべて', tiendas: 'ストア', productos: 'プロダクト', proyectos: 'プロジェクト' },
    filtrar: '制作を絞り込む',
    destacadas: '注目の制作',
    resto: 'そのほかの制作',
    mas: 'その他の制作',
    masLead: '公開できる画面はまだありません。',
    tempranas: '初期のストア（公開できる画面なし）',
    vacio: 'この条件に該当するものはありません。',
  },
  ficha: {
    volver: '制作',
    historia: '経緯',
    caso: '事例',
    reto: '課題',
    hice: 'やったこと',
    quedo: '残ったもの',
    hoy: '現在のストア',
    hoyTxt: 'ストアの公開カタログが今伝えていること。',
    info: '情報',
    sector: '業種',
    rol: '役割',
    periodo: '期間',
    anio: '年',
    pila: '技術',
    enlace: 'リンク',
    repo: 'リポジトリ',
    ver: 'ストアを見る',
    verSitio: 'サイトを開く',
    visor: 'スクリーンショットビューア',
    anterior: '前の画面',
    siguiente: '次の画面',
    sinCaptura: '画面なし',
    proxima: '次の制作',
    vistas: { 'home-desktop': 'ホーム · デスクトップ', 'pdp-desktop': '商品 · デスクトップ', 'home-mobile': 'ホーム · モバイル', 'pdp-mobile': '商品 · モバイル' },
    medido: '計測値（補足）',
    noExiste: 'その制作は見つかりません',
  },
  trayectoria: {
    titulo: '経歴',
    abrir: '話してみる',
    ahora: '現在',
    abrirCargo: '詳細を開く',
    cerrarCargo: '詳細を閉じる',
    uso: '数字は、このページの中で技術スタックにそのツールを挙げているストアの数です。',
    contrato: { 'full-time': 'フルタイム', 'part-time': 'パートタイム', contract: '契約' },
  },
  contacto: {
    titulo: '連絡',
    canales: '連絡先',
    correo: 'メール',
    whatsapp: 'WhatsApp',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    cv: '履歴書',
    copiar: 'コピー',
    copiado: 'コピーしました',
    formulario: 'メッセージ',
    motivo: '進め方',
    motivos: { revision: '無料20分のストア診断', proyecto: 'プロジェクトの構築', continuo: '継続的な支援', empleo: '採用' },
    empleoNota: '求人や面接のご連絡です。',
    tienda: 'ストアのURL',
    tiendaEj: 'yourstore.com',
    tiendaFalta: '診断のためにストアのURLを入力してください。',
    correoL: 'メールアドレス',
    correoEj: 'name@email.com',
    correoFalta: '有効なメールアドレスを入力してください。',
    mensaje: 'メッセージ（任意）',
    enviar: { revision: '診断を依頼する', proyecto: 'プロジェクトを相談する', continuo: '継続支援を相談する', empleo: '送信する' },
    enviando: '送信中',
    ok: '受け取りました。メールでお返事します。',
    error: 'ここから送信できなかったため、メールアプリを開きました。',
  },
  pie: { medellin: 'メデジン', volver: '上へ戻る', derechos: '© 2026' },
  temas: { boton: 'テーマ', titulo: 'テーマ', sub: '同じ仕事を、別の見かたで', lista: 'サイトのテーマ', cerrar: '閉じる', cerrarAria: 'テーマを閉じる', actual: '現在のテーマ', elegir: '選ぶ' },
}

const TEXTOS: Record<string, Copy> = { es, en, ja }

export function useCopy(): Copy {
  const { locale } = useLanguage()
  return TEXTOS[locale] ?? en
}
