import type { RolId } from './datos'

// Textos propios de la dirección Anatomía (es y en; ja cae a en). Todo lo demás (titular, nota, FAQ, cargos, obra) viene
// de useV5() y nunca se copia aquí.

const es = {
  nav: { inicio: 'Inicio', obra: 'Obra', trayectoria: 'Trayectoria', contacto: 'Contacto', menu: 'Menú', cerrar: 'Cerrar', piezas: 'Piezas', idioma: 'Idioma', principal: 'Principal', inferior: 'Atajos', saltar: 'Saltar al contenido' },
  piezas: {
    anuncio: { nombre: 'Anuncio', nota: 'El texto de cada recorte es de su tienda.' },
    cabecera: { nombre: 'Cabecera', nota: 'La barra de navegación tal como la sirve cada tienda.' },
    hero: { nombre: 'Hero', nota: 'La primera sección de la home. Mismo trabajo, no el mismo componente: la isla cambia de nombre de una tienda a otra.' },
    carrusel: { nombre: 'Carrusel de producto', nota: 'Solo entran las tiendas cuya sección se llama carrusel de producto.' },
    resenas: { nombre: 'Reseñas', nota: 'Se compara la pieza, no las reseñas: el contenido de cada recorte es de su tienda.' },
    faq: { nombre: 'FAQ', nota: 'Las preguntas frecuentes de la home de cada tienda.' },
    pie: { nombre: 'Pie', nota: 'El pie de página de cada tienda, de punta a punta.' },
  } as Record<RolId, { nombre: string; nota: string }>,
  inicio: {
    indice: 'Piezas del atlas',
    recortes: (n: number) => (n === 1 ? '1 recorte' : `${n} recortes`),
    tiendas: (n: number) => `en ${n} tiendas medidas`,
    porMedir: 'por medir',
    construidas: (n: string) => `${n} tiendas construidas`,
    numero: (n: number, nombre: string, alineado: boolean) => `Nº ${String(n).padStart(2, '0')} · ${nombre}${alineado ? ' · alineado' : ''}`,
    cota: (fecha: string) => `Cota = alto real de la sección · sonda del ${fecha}`,
    alinear: 'Alinear',
    alineado: 'Alineado',
    verTodas: (n: number) => `Ver las ${n}`,
    anterior: 'Recortes anteriores',
    siguiente: 'Más recortes',
    sinRecortes: 'Esta pieza todavía no tiene recortes medidos.',
  },
  tira: {
    isla: (i: string) => `isla ${i}`,
    seccion: (c: string) => `sección ${c}`,
    fondo: 'fondo',
    sinFondo: 'fondo sin declarar',
    alto: 'px',
    escala: 'Esc.',
    recortes: (n: number) => (n === 1 ? '1 recorte' : `${n} recortes`),
    verTodas: 'Ver todas',
    verMenos: 'Ver menos',
    alt: (pieza: string, tienda: string, h: number) => `Recorte real de la pieza ${pieza} de ${tienda}: ${h} píxeles de alto`,
  },
  obra: {
    titulo: 'Obra',
    porPieza: 'Por pieza',
    porTienda: 'Por tienda',
    vista: 'Vista de la obra',
    rubro: 'Rubro',
    anio: 'Año',
    todos: 'Todos',
    sonda: (fecha: string, n: number) => `Sonda del ${fecha} · ${n} tiendas`,
    contador: (n: number, m: number) => (n === m ? `${m} recortes` : `${n} de ${m} recortes`),
    sinResultados: 'Ningún recorte con ese rubro y año. Quita un filtro.',
    fila: (n: number, m: number) => `${String(n).padStart(2, '0')} / ${String(m).padStart(2, '0')}`,
    leyenda: { isla: 'Isla', piel: 'Piel', cota: 'Cota' },
    leyendaIsla: 'data-island de la sección; si no hay, su clave.',
    leyendaPiel: 'Titulares y cuerpo leídos del CSS computado.',
    leyendaCota: 'Alto real de la sección, en píxeles.',
    razon: {
      cliente: 'Tema del cliente, sin recortes',
      'por-confirmar': 'Tema por confirmar',
      'sin-medicion': 'Sin medición del tema',
      producto: 'Producto, no tienda',
      cargo: 'Entregable de un cargo',
      personal: 'Proyecto personal',
      pendiente: 'Sin recortes medidos todavía',
    } as Record<string, string>,
    piezasDe: (n: number) => (n === 1 ? '1 pieza' : `${n} piezas`),
    abrir: (n: string) => `Abrir ${n}`,
    obras: (n: number) => `${n} obras`,
  },
  visor: {
    cerrar: 'Cerrar el visor',
    anterior: 'Recorte anterior',
    siguiente: 'Recorte siguiente',
    de: (i: number, n: number) => `${i} de ${n}`,
    clave: 'Clave',
    isla: 'Isla',
    sinIsla: 'sin isla',
    cota: 'Cota',
    piel: 'Piel medida',
    titulares: 'Titulares',
    cuerpo: 'Cuerpo',
    fondo: 'Fondo',
    sinFondo: 'sin declarar',
    medido: 'Medido el',
    verObra: 'Ver la obra',
    mismaPieza: 'Misma pieza, otra marca: usa las flechas o desliza.',
    plantilla: (nombre: string) => `Tema declarado: ${nombre}`,
  },
  ficha: {
    comparador: 'Comparador',
    con: 'Comparar con',
    sinPareja: 'Elige otra tienda para comparar',
    piezasComunes: 'Piezas que ambas tienen',
    piel: 'Piel medida',
    titulares: 'Titulares',
    cuerpo: 'Cuerpo',
    fondo: 'Fondo',
    sinFondo: 'sin declarar',
    sinRecortes: (razon: string) => `Esta obra no tiene recortes para comparar (${razon.toLowerCase()}). Abajo están sus datos y sus capturas.`,
    ningunaComun: 'Estas dos tiendas no comparten ninguna pieza medida.',
    datos: 'Ficha de datos',
    rubro: 'Rubro',
    rol: 'Rol',
    pila: 'Pila',
    periodo: 'Periodo',
    git: 'Git del repo',
    gitValor: (c: number, s: number | undefined, f: string) => `${c} commits${s ? ` · ${s} secciones propias` : ''} · medido el ${f}`,
    lighthouse: 'Lighthouse',
    lhValor: (m: number, d: number, f: string) => `móvil ${m} · escritorio ${d} · medido el ${f}`,
    enlace: 'Enlace',
    capturas: 'Capturas',
    home: 'Home',
    pdp: 'PDP',
    escritorio: 'Escritorio',
    movil: 'Móvil',
    verPieza: 'Ver esta pieza en otras tiendas',
    ladoA: 'A',
    ladoB: 'B',
    lado: 'Lado que se muestra',
    volver: 'Volver a la obra',
  },
  tray: {
    titulo: 'Trayectoria',
    matriz: 'Pieza × cargo',
    nota: 'Un punto aparece solo si el stack declarado de ese cargo nombra la herramienta.',
    herramienta: 'Herramienta',
    cargo: 'Cargo',
    abrirCargo: (n: string) => `Abrir el cargo ${n}`,
    abrirHerramienta: (n: string) => `Ver dónde aparece ${n}`,
    resumen: 'Resumen',
    logros: 'Lo que se entregó',
    metricas: 'Cifras atribuidas',
    entregables: 'Entregables del cargo',
    stack: 'Stack declarado',
    nombran: (h: string) => `Cargos y tiendas que nombran ${h}`,
    ninguno: 'Ningún cargo la nombra en su stack declarado.',
    cargosLista: 'Cargos',
    tiendasLista: 'Tiendas',
    elige: 'Toca un cargo o una herramienta para ver el detalle.',
    volver: 'Volver a la matriz',
    grupos: { shopify: 'Shopify', frontend: 'Frontend', backend: 'Backend', quality: 'Calidad', cro: 'CRO', ai: 'IA', otras: 'Otras' } as Record<string, string>,
    punto: 'nombra la herramienta',
    sinPunto: 'no la nombra',
    sinCargo: (n: number) => `${n} herramientas del registro no aparecen: ningún cargo las declara en su stack.`,
  },
  contacto: {
    pedir: 'Pedir una pieza',
    pedirNota: 'Elige lo que quieres que mire primero. El mensaje sale ya armado.',
    fuga: 'Puntos de fuga',
    fugas: ['Velocidad', 'Ofertas', 'Fricción en el checkout'],
    elegiste: (l: string) => `Elegiste: ${l}`,
    ninguna: 'Todavía no elegiste nada: puedes escribir igual.',
    porCorreo: 'Escribir por correo',
    porWhatsApp: 'Escribir por WhatsApp',
    asunto: 'Revisión de mi tienda Shopify',
    cuerpo: (l: string) => `Hola Max, quiero que mires esto primero: ${l || 'lo que veas'}.\n\nURL de mi tienda: `,
    formulario: 'O deja tu tienda y tu correo',
    url: 'URL de tu tienda',
    urlEjemplo: 'tutienda.com',
    correo: 'Tu correo',
    motivo: 'Motivo',
    enviar: 'Enviar',
    enviando: 'Enviando',
    enviado: 'Listo. Recibes respuesta en un día hábil.',
    fallo: 'No se pudo enviar desde aquí; se abrió tu correo con el mensaje.',
    errorUrl: 'Escribe la URL de tu tienda.',
    errorCorreo: 'Escribe un correo válido.',
    canales: 'Canales directos',
    copiar: 'Copiar correo',
    copiado: 'Correo copiado',
    whatsapp: 'WhatsApp',
    linkedin: 'LinkedIn',
    cv: 'Descargar CV',
    llamadas: 'Llamadas',
    hora: 'Hora en Medellín',
    preguntas: 'Antes de escribir',
    cierre: '¿Qué miras en 20 minutos?',
    cierreCta: 'Pedir la revisión',
  },
  pie: { medido: (f: string) => `Recortes medidos: ${f}`, hora: (h: string) => `Medellín ${h}` },
  idiomas: { es: 'ES', en: 'EN', ja: 'JA' },
}

type Copy = typeof es

const en: Copy = {
  nav: { inicio: 'Home', obra: 'Work', trayectoria: 'Career', contacto: 'Contact', menu: 'Menu', cerrar: 'Close', piezas: 'Pieces', idioma: 'Language', principal: 'Main', inferior: 'Shortcuts', saltar: 'Skip to content' },
  piezas: {
    anuncio: { nombre: 'Announcement bar', nota: 'The text in each crop belongs to its store.' },
    cabecera: { nombre: 'Header', nota: 'The navigation bar as each store serves it.' },
    hero: { nombre: 'Hero', nota: 'The first section of the home page. Same work, not the same component: the island changes name from one store to another.' },
    carrusel: { nombre: 'Product carousel', nota: 'Only stores whose section is a product carousel appear here.' },
    resenas: { nombre: 'Reviews', nota: 'The piece is compared, not the reviews: the content of each crop belongs to its store.' },
    faq: { nombre: 'FAQ', nota: 'The frequently asked questions on each store home page.' },
    pie: { nombre: 'Footer', nota: 'Each store footer, edge to edge.' },
  },
  inicio: {
    indice: 'Pieces of the atlas',
    recortes: (n) => (n === 1 ? '1 crop' : `${n} crops`),
    tiendas: (n) => `in ${n} measured stores`,
    porMedir: 'to be measured',
    construidas: (n) => `${n} stores built`,
    numero: (n, nombre, alineado) => `No. ${String(n).padStart(2, '0')} · ${nombre}${alineado ? ' · aligned' : ''}`,
    cota: (fecha) => `Dimension = real section height · probe of ${fecha}`,
    alinear: 'Align',
    alineado: 'Aligned',
    verTodas: (n) => `See all ${n}`,
    anterior: 'Previous crops',
    siguiente: 'More crops',
    sinRecortes: 'This piece has no measured crops yet.',
  },
  tira: {
    isla: (i) => `island ${i}`,
    seccion: (c) => `section ${c}`,
    fondo: 'background',
    sinFondo: 'background undeclared',
    alto: 'px',
    escala: 'Scale',
    recortes: (n) => (n === 1 ? '1 crop' : `${n} crops`),
    verTodas: 'See all',
    verMenos: 'See fewer',
    alt: (pieza, tienda, h) => `Real crop of the ${pieza} piece of ${tienda}: ${h} pixels tall`,
  },
  obra: {
    titulo: 'Work',
    porPieza: 'By piece',
    porTienda: 'By store',
    vista: 'Work view',
    rubro: 'Industry',
    anio: 'Year',
    todos: 'All',
    sonda: (fecha, n) => `Probe of ${fecha} · ${n} stores`,
    contador: (n, m) => (n === m ? `${m} crops` : `${n} of ${m} crops`),
    sinResultados: 'No crop with that industry and year. Remove a filter.',
    fila: (n, m) => `${String(n).padStart(2, '0')} / ${String(m).padStart(2, '0')}`,
    leyenda: { isla: 'Island', piel: 'Skin', cota: 'Dimension' },
    leyendaIsla: 'The data-island of the section; if none, its key.',
    leyendaPiel: 'Headings and body read from computed CSS.',
    leyendaCota: 'Real section height, in pixels.',
    razon: {
      cliente: 'Client theme, no crops',
      'por-confirmar': 'Theme to be confirmed',
      'sin-medicion': 'Theme not measured',
      producto: 'Product, not a store',
      cargo: 'Deliverable of a role',
      personal: 'Personal project',
      pendiente: 'No measured crops yet',
    },
    piezasDe: (n) => (n === 1 ? '1 piece' : `${n} pieces`),
    abrir: (n) => `Open ${n}`,
    obras: (n) => `${n} works`,
  },
  visor: {
    cerrar: 'Close the viewer',
    anterior: 'Previous crop',
    siguiente: 'Next crop',
    de: (i, n) => `${i} of ${n}`,
    clave: 'Key',
    isla: 'Island',
    sinIsla: 'no island',
    cota: 'Dimension',
    piel: 'Measured skin',
    titulares: 'Headings',
    cuerpo: 'Body',
    fondo: 'Background',
    sinFondo: 'undeclared',
    medido: 'Measured on',
    verObra: 'See the work',
    mismaPieza: 'Same piece, another brand: use the arrows or swipe.',
    plantilla: (nombre) => `Declared theme: ${nombre}`,
  },
  ficha: {
    comparador: 'Comparator',
    con: 'Compare with',
    sinPareja: 'Pick another store to compare',
    piezasComunes: 'Pieces both have',
    piel: 'Measured skin',
    titulares: 'Headings',
    cuerpo: 'Body',
    fondo: 'Background',
    sinFondo: 'undeclared',
    sinRecortes: (razon) => `This work has no crops to compare (${razon.toLowerCase()}). Its data and captures are below.`,
    ningunaComun: 'These two stores share no measured piece.',
    datos: 'Data sheet',
    rubro: 'Industry',
    rol: 'Role',
    pila: 'Stack',
    periodo: 'Period',
    git: 'Repo git',
    gitValor: (c, s, f) => `${c} commits${s ? ` · ${s} custom sections` : ''} · measured on ${f}`,
    lighthouse: 'Lighthouse',
    lhValor: (m, d, f) => `mobile ${m} · desktop ${d} · measured on ${f}`,
    enlace: 'Link',
    capturas: 'Captures',
    home: 'Home',
    pdp: 'PDP',
    escritorio: 'Desktop',
    movil: 'Mobile',
    verPieza: 'See this piece in other stores',
    ladoA: 'A',
    ladoB: 'B',
    lado: 'Side shown',
    volver: 'Back to the work',
  },
  tray: {
    titulo: 'Career',
    matriz: 'Piece × role',
    nota: 'A dot appears only if the declared stack of that role names the tool.',
    herramienta: 'Tool',
    cargo: 'Role',
    abrirCargo: (n) => `Open the role ${n}`,
    abrirHerramienta: (n) => `See where ${n} appears`,
    resumen: 'Summary',
    logros: 'What shipped',
    metricas: 'Attributed figures',
    entregables: 'Deliverables of the role',
    stack: 'Declared stack',
    nombran: (h) => `Roles and stores that name ${h}`,
    ninguno: 'No role names it in its declared stack.',
    cargosLista: 'Roles',
    tiendasLista: 'Stores',
    elige: 'Tap a role or a tool to see the detail.',
    volver: 'Back to the matrix',
    grupos: { shopify: 'Shopify', frontend: 'Frontend', backend: 'Backend', quality: 'Quality', cro: 'CRO', ai: 'AI', otras: 'Other' },
    punto: 'names the tool',
    sinPunto: 'does not name it',
    sinCargo: (n) => `${n} tools in the registry do not appear: no role declares them in its stack.`,
  },
  contacto: {
    pedir: 'Ask for a piece',
    pedirNota: 'Pick what you want me to look at first. The message comes out already written.',
    fuga: 'Leak points',
    fugas: ['Speed', 'Offers', 'Checkout friction'],
    elegiste: (l) => `You picked: ${l}`,
    ninguna: 'Nothing picked yet: you can still write.',
    porCorreo: 'Write by email',
    porWhatsApp: 'Write on WhatsApp',
    asunto: 'Review of my Shopify store',
    cuerpo: (l) => `Hi Max, I want you to look at this first: ${l || 'whatever you see'}.\n\nMy store URL: `,
    formulario: 'Or leave your store and email',
    url: 'Your store URL',
    urlEjemplo: 'yourstore.com',
    correo: 'Your email',
    motivo: 'Reason',
    enviar: 'Send',
    enviando: 'Sending',
    enviado: 'Done. You hear back within one business day.',
    fallo: 'It could not be sent from here; your email app opened with the message.',
    errorUrl: 'Enter your store URL.',
    errorCorreo: 'Enter a valid email.',
    canales: 'Direct channels',
    copiar: 'Copy email',
    copiado: 'Email copied',
    whatsapp: 'WhatsApp',
    linkedin: 'LinkedIn',
    cv: 'Download CV',
    llamadas: 'Calls',
    hora: 'Time in Medellín',
    preguntas: 'Before you write',
    cierre: 'What do you look at in 20 minutes?',
    cierreCta: 'Ask for the review',
  },
  pie: { medido: (f) => `Crops measured: ${f}`, hora: (h) => `Medellín ${h}` },
  idiomas: { es: 'ES', en: 'EN', ja: 'JA' },
}

export const copyFor = (locale: string): Copy => (locale === 'es' ? es : en)
export type { Copy }
