export { ExploreDesignsLuxury } from './ExploreDesignsLuxury'
export { ExploreDesignsBrutalist } from './ExploreDesignsBrutalist'
export { ShopifyWork } from './ShopifyWork'
export { Gallery, shotsFor, lightboxItems, caseStudyFor } from './Gallery'
export type { SectionHeading } from './Gallery'
export { Years } from './Years'
export { Process } from './Process'
export { Testimonials } from './Testimonials'
