export { ExploreDesignsLuxury } from './ExploreDesignsLuxury'
export { ExploreDesignsBrutalist } from './ExploreDesignsBrutalist'
export { ShopifyWork } from './ShopifyWork'
export { Gallery, shotsFor, lightboxItems } from './Gallery'
export type { SectionHeading } from './Gallery'
