import { useLanguage } from '../../context/LanguageContext'

// Etiquetas de interfaz de la dirección D (es y en; ja cae a en hasta que Max elija dirección: Q12).
// Nada de aquí es un dato: cifras, nombres y textos de obra salen de useV5().

const es = {
  saltar: 'Saltar al contenido',
  marcaAria: 'Maximiliano Bustamante, inicio',
  navAria: 'Navegación principal',
  idiomaAria: 'Idioma de la interfaz',
  jaParcial: 'parcial',
  nav: {
    inicio: ['Inicio', 'Hoja'],
    obra: ['Obra', 'Comparar modelos'],
    trayectoria: ['Trayectoria', 'Historial'],
    contacto: ['Contacto', 'Puertos'],
  },
  titulos: { inicio: 'Aluminio', obra: 'Obra', trayectoria: 'Trayectoria', contacto: 'Contacto' },
  pie: { enlaces: 'Enlaces', cv: 'CV (PDF)', hora: 'Hora en Medellín', sitio: 'Sitio privado, sin indexar' },

  inicio: {
    modelo: 'Maxfolio · hoja de especificaciones',
    ctaCorto: 'Pedir revisión gratis',
    cvEtiqueta: 'CV',
    seisDe: '{n} de {total} construidas',
    capturasDel: 'capturas {fecha}',
    ctaNota: 'Revisión gratis de 20 minutos.',
    figura: 'Fig. 1 · Panel frontal',
    figuraAyuda: 'Los interruptores funcionan',
    pantalla: 'Pantalla de puntos',
    interruptores: 'Interruptores',
    interruptoresAyuda: 'Idioma · Movimiento · Densidad',
    datoN: 'Dato {i}/{n}',
    lcdMov: ['MOV NORMAL', 'MOV REDUC'],
    lcdDens: ['DENS CÓMODA', 'DENS COMPACTA'],
    aparato: 'Panel de datos',
    lcdAria: 'Pantalla de datos',
    mando: 'Siguiente dato',
    mandoEstado: 'Dato {i} de {n}',
    medellin: 'Medellín',
    idioma: 'Idioma',
    movimiento: 'Movimiento',
    densidad: 'Densidad',
    normal: 'Normal',
    reducido: 'Reducido',
    comoda: 'Cómoda',
    compacta: 'Compacta',
    lcdTiendas: '{n} tiendas construidas · corte 2026-09',
    tiendasEtiqueta: 'tiendas construidas · corte 2026-09',
    lcdCapturas: 'Capturas del {fecha}',
    lcdGit: 'Git: commits del {fecha}',
    lcdLighthouse: 'Lighthouse: medición local del {fecha}',
    avisoIdioma: 'Idioma: {v}',
    avisoMovimiento: 'Movimiento: {v}',
    avisoDensidad: 'Densidad: {v}',
    hojaTitulo: 'Hoja de especificaciones',
    hoy: 'Modelo · hoy',
    empresa: 'Empresa',
    trayectoria: 'Trayectoria',
    ubicacion: 'Ubicación',
    idiomasSitio: 'Idiomas del sitio',
    idiomasSitioValor: 'es · en · ja (ja parcial)',
    interfaces: 'Interfaces',
    presente: 'presente',
    correo: 'Correo',
    despieceTitulo: 'Despiece',
    despieceLead: 'Seis capas de lo que hay dentro de una tienda. Elige una y mira cuántas fichas del registro la nombran.',
    capa: 'Capa {i}',
    cuentaDe: '{n} de {m} {etiqueta}',
    fichasLaNombran: 'fichas la nombran en su stack',
    tiendasConIslas: 'tiendas con islas, entre las que tienen telemetría de git',
    segunCv: 'Según el CV de Max, en su cargo en Digitdeck.',
    datoAl: 'dato al {f}',
    fuenteDespiece: 'Los textos son del sitio y de lo que Max cuenta de su trabajo. Las cuentas salen del registro de obra y de la telemetría de git del 2026-09-08: «la nombran» es lo que dice el stack de cada ficha, no un conteo de uso. Las capas 4 y 6 se apoyan en el CV de Max.',
    capas: [
      { id: 'tema', nombre: 'Tema Liquid sobre la plantilla Digitdeck' },
      { id: 'islas', nombre: 'Islas React' },
      { id: 'apps', nombre: 'Suite de apps' },
      { id: 'functions', nombre: 'Functions, Web Pixel y extensiones de tema' },
      { id: 'medicion', nombre: 'Medición propia data-dd-*' },
      { id: 'qa', nombre: 'Arnés de QA en Playwright' },
    ],
    comoTitulo: 'Cómo trabajo, según Max',
    comoNota: 'Su proceso, en sus palabras. Las cifras que vienen de su CV se atribuyen a él.',
    comoChecks: 'Pruebas antes de publicar',
    comoCommits: '{n} commits en los repos de {t} tiendas, a septiembre de 2026. Son commits del repo de cada tienda, no de una sola persona.',
    ultimosTitulo: 'Línea de modelos',
    ultimosLead: 'Las obras más recientes con captura real, a {fecha}.',
    verObra: 'Comparar todas las obras',
    verFicha: 'Abrir la ficha de {nombre}',
    recibirRevision: 'Recibir mi revisión',
  },

  obra: {
    lead: 'Cada obra es una columna y cada atributo, una fila. Lo que no existe se escribe «—».',
    filtros: 'Filtros',
    tipo: 'Tipo',
    anio: 'Año',
    rol: 'Rol',
    tecnologia: 'Tecnología',
    tipos: { store: 'Tiendas', product: 'Productos', personal: 'Personales', role: 'Entregables' },
    tipoUno: { store: 'Tienda', product: 'Producto', personal: 'Proyecto personal', role: 'Entregable de un cargo' },
    rolCustom: 'Personalizada',
    mostrando: 'Mostrando {n}',
    buscar: 'Buscar',
    rend: 'rend.',
    acc: 'acc',
    tambien: 'También',
    enLaTabla: 'en la tabla',
    lcdContador: '{n} DE {t} OBRAS',
    lcdComparando: 'COMPARANDO {n} · MÁX 3',
    lcdLibre: 'ELIGE HASTA 3 PARA COMPARAR',
    lcdMovil: 'DESLIZA PARA COMPARAR',
    columnaFija: 'Columna fija · desplaza',
    filtrosAbrir: 'Filtros',
    modeloN: 'M{n}',
    elegir: 'Elegir para comparar',
    comparaAncho: 'Comparar {n} a todo ancho',
    limpiar: 'Limpiar',
    masModelos: 'Mostrar {n} más',
    otras: 'Ver otras {n}',
    anteriores: 'Ver las {n} anteriores',
    masFiltros: '+ {n}',
    sinResultados: 'Ninguna obra coincide con estos filtros.',
    tablaAria: 'Tabla de comparación de obras',
    atributo: 'Atributo',
    comparar: 'Comparar',
    compararN: 'Comparar {n} modelos',
    compararAyuda: 'Marca dos o tres para fijarlas a todo ancho.',
    comparando: 'Comparando {n} modelos',
    quitarComparacion: 'Volver a todas',
    modelo: 'Modelo',
    filas: {
      rubro: 'Rubro',
      tipo: 'Tipo',
      anio: 'Año',
      construccion: 'Construcción',
      rol: 'Rol',
      pila: 'Pila',
      git: 'Git',
      lhMovil: 'Lighthouse móvil',
      lhEscritorio: 'Lighthouse escritorio',
      catalogo: 'Catálogo',
      capturas: 'Capturas',
    },
    gitCelda: '{commits} commits · {secciones} secciones',
    lhMovil: 'Móvil',
    lhEscritorio: 'Escritorio',
    lhOrden: 'rend. / acces. / SEO',
    catalogoCelda: '{p} productos · {c} colecciones',
    temaCliente: 'Tema del cliente, no es obra de Max',
    si: 'Sí',
    pieGit: 'Git: commits del repo de cada tienda, 2026-09-08.',
    pieLighthouse: 'Lighthouse: medición local del 2026-09-10, mejor de 3; solo tiendas con tema de Digitdeck al medir.',
    pieCatalogo: 'Catálogo público al 2026-09-09; no son ventas.',
  },

  ficha: {
    migas: 'Obra',
    resumen: 'Resumen',
    specs: 'Especificaciones',
    hechoCon: 'Hecho con',
    anclas: 'Secciones de la ficha',
    galeria: 'Capturas',
    vista: 'Vista',
    home: 'Home',
    pdp: 'Página de producto',
    dispositivo: 'Dispositivo',
    escritorio: 'Escritorio',
    movil: 'Móvil',
    sinCapturas: 'Sin capturas públicas de esta obra.',
    abrir: 'Abrir el sitio',
    hechos: 'Hechos',
    labTitulo: 'Mediciones de laboratorio',
    labNota: 'Medición local del {fecha}, mejor de 3. Buenas prácticas se omite: los scripts de Shopify la fijan entre 54 y 77.',
    rendimiento: 'Rendimiento',
    accesibilidad: 'Accesibilidad',
    seo: 'SEO',
    gitTitulo: 'Repositorio',
    gitNota: 'Commits del repo de la tienda, a {fecha}.',
    primerCommit: 'Primer commit',
    ultimoCommit: 'Último commit',
    commits: 'Commits',
    secciones: 'Secciones Liquid',
    lineasLiquid: 'Líneas de Liquid',
    lineasIslas: 'Líneas de islas TS/TSX',
    catalogoTitulo: 'Catálogo público',
    catalogoNota: 'Catálogo público al {fecha}; no son ventas.',
    productos: 'Productos',
    colecciones: 'Colecciones',
    moneda: 'Moneda',
    precios: 'Rango de precios',
    hechoConLead: 'Productos propios cuyo nombre aparece en el stack de esta obra.',
    hechoConNinguno: 'El stack de esta obra no nombra ningún producto propio.',
    anterior: 'Anterior',
    siguiente: 'Siguiente',
    pedirRevision: 'Pedir la revisión de mi tienda',
    pedirCorto: 'Pedir revisión',
    specsCorto: 'Datos',
    pie: 'Otras obras',
    volver: 'Volver a la tabla',
    noExiste: 'Esta obra no está en el registro',
    semanas: 'Commits por semana',
    semanasNota: 'Cada barra es una semana del repo, desde {desde}.',
    ver: 'Ver',
    sitio: 'Sitio',
    sinMedicion: 'Sin medición propia de Lighthouse para esta obra.',
    temaCliente: 'El tema que sirve este dominio es del cliente: esa medición no es obra de Max.',
    stack: 'Pila',
    rol: 'Rol',
    anio: 'Año',
    rubro: 'Rubro',
    construccion: 'Construcción',
    tipo: 'Tipo',
    movilLab: 'Móvil',
    escritorioLab: 'Escritorio',
    lcp: 'LCP',
  },

  trayectoria: {
    lead: 'Cada cargo como una nota de versión: periodo, empresa, qué cambió.',
    hoy: 'Hoy',
    segunCv: 'Cifras según el CV de Max, atribuidas a este cargo y a su periodo.',
    cambios: 'Cambios',
    cifras: 'Cifras del cargo',
    tiendasConstruidas: '{n} tiendas construidas',
    presente: 'presente',
    compatibilidad: 'Compatibilidad',
    compatLead: 'Herramientas por grupo y cuántas fichas del registro las nombran en su stack.',
    mencionada: 'Mencionada en {n} fichas',
    mencionadaUna: 'Mencionada en 1 ficha',
    delCv: 'En el CV de Max',
    plegadas: '{n} herramientas que el stack de las fichas no nombra',
    plegadasNota: 'Esto no mide lo que Max usa: mide lo que escribió en la ficha de cada obra.',
    compatNota: 'La cuenta sale de expresiones escritas a mano sobre los stacks de tiendas, productos y entregables; no es «N tiendas la usan».',
    grupos: 'Grupos de herramientas',
    nota: 'Nota {n} de {t}',
    aniosAria: 'Una línea por año',
    actual: 'Actual',
    riel: 'Notas de versión, de la más reciente a la más antigua',
    lugar: 'Lugar',
    tipoEmpleo: 'Tipo',
    empleo: { 'full-time': 'Tiempo completo', 'part-time': 'Medio tiempo', contract: 'Contrato' },
    sinTitulo: 'Cargo actual en Digitdeck',
  },

  contacto: {
    modos: 'Qué necesitas',
    modosAyuda: 'Elige una forma de empezar; cambia el asunto del correo y el motivo del formulario.',
    puertos: 'Panel trasero',
    puertosAria: 'Canales directos',
    correo: 'Correo',
    copiar: 'Toca para copiar',
    copiado: 'Correo copiado',
    abrirCorreo: 'Abrir en tu app de correo',
    whatsapp: 'WhatsApp',
    llamada: 'Llamada',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    cv: 'CV',
    cvValor: 'PDF · 2 páginas · en inglés',
    perfil: 'Perfil',
    formularioTitulo: 'Formulario compacto',
    tienda: 'La URL de tu tienda',
    tiendaAyuda: 'Opcional',
    correoCampo: 'Tu correo',
    enviar: 'Enviar',
    enviando: 'Enviando…',
    ok: 'Enviado. Gracias: reviso tu tienda y te escribo.',
    error: 'No se pudo enviar. Se abrió tu app de correo con el mensaje listo.',
    procedimiento: 'Procedimiento',
    pasoDe: 'Paso {n} de {t}',
    siguiente: 'Qué pasa después',
    faq: 'Preguntas frecuentes',
    hora: 'Hora en Medellín',
    oferta: 'Lo que ofrezco',
    titulo: 'Contacto',
    leadPuertos: 'Seis puertos directos. Toca uno: el correo se copia y los demás se abren.',
    ledEncendido: 'encendido',
    apagado: 'En espera',
    asuntoRevision: 'Revisión gratis de 20 minutos',
    formularioAyuda: 'Tres datos bastan para empezar.',
    motivo: 'Motivo',
    camposRequeridos: 'Falta el correo para poder responderte.',
    entregable: 'Recibes',
  },
}

const en: typeof es = {
  saltar: 'Skip to content',
  marcaAria: 'Maximiliano Bustamante, home',
  navAria: 'Main navigation',
  idiomaAria: 'Interface language',
  jaParcial: 'partial',
  nav: {
    inicio: ['Home', 'Datasheet'],
    obra: ['Work', 'Compare models'],
    trayectoria: ['Career', 'Changelog'],
    contacto: ['Contact', 'Ports'],
  },
  titulos: { inicio: 'Aluminium', obra: 'Work', trayectoria: 'Career', contacto: 'Contact' },
  pie: { enlaces: 'Links', cv: 'CV (PDF)', hora: 'Time in Medellín', sitio: 'Private site, not indexed' },

  inicio: {
    modelo: 'Maxfolio · datasheet',
    ctaCorto: 'Get a free review',
    cvEtiqueta: 'CV',
    seisDe: '{n} of {total} built',
    capturasDel: 'screenshots {fecha}',
    ctaNota: 'Free 20-minute review.',
    figura: 'Fig. 1 · Front panel',
    figuraAyuda: 'The switches work',
    pantalla: 'Dot display',
    interruptores: 'Switches',
    interruptoresAyuda: 'Language · Motion · Density',
    datoN: 'Datum {i}/{n}',
    lcdMov: ['MOT NORMAL', 'MOT REDUCED'],
    lcdDens: ['DENS COMFY', 'DENS COMPACT'],
    aparato: 'Data panel',
    lcdAria: 'Data display',
    mando: 'Next datum',
    mandoEstado: 'Datum {i} of {n}',
    medellin: 'Medellín',
    idioma: 'Language',
    movimiento: 'Motion',
    densidad: 'Density',
    normal: 'Normal',
    reducido: 'Reduced',
    comoda: 'Comfortable',
    compacta: 'Compact',
    lcdTiendas: '{n} storefronts built · cut-off 2026-09',
    tiendasEtiqueta: 'storefronts built · cut-off 2026-09',
    lcdCapturas: 'Screenshots of {fecha}',
    lcdGit: 'Git: commits of {fecha}',
    lcdLighthouse: 'Lighthouse: local run of {fecha}',
    avisoIdioma: 'Language: {v}',
    avisoMovimiento: 'Motion: {v}',
    avisoDensidad: 'Density: {v}',
    hojaTitulo: 'Specifications',
    hoy: 'Model · today',
    empresa: 'Company',
    trayectoria: 'Career',
    ubicacion: 'Location',
    idiomasSitio: 'Site languages',
    idiomasSitioValor: 'es · en · ja (ja partial)',
    interfaces: 'Interfaces',
    presente: 'present',
    correo: 'Email',
    despieceTitulo: 'Exploded view',
    despieceLead: 'Six layers of what sits inside a store. Pick one and see how many registry entries name it.',
    capa: 'Layer {i}',
    cuentaDe: '{n} of {m} {etiqueta}',
    fichasLaNombran: 'entries name it in their stack',
    tiendasConIslas: 'stores with islands, among those with git telemetry',
    segunCv: 'According to Max’s CV, in his Digitdeck role.',
    datoAl: 'as of {f}',
    fuenteDespiece: 'The texts come from the site and from what Max says about his work. The counts come from the work registry and the git telemetry of 2026-09-08: «name it» means the entry’s stack lists it, not a usage count. Layers 4 and 6 rely on Max’s CV.',
    capas: [
      { id: 'tema', nombre: 'Liquid theme on the Digitdeck template' },
      { id: 'islas', nombre: 'React islands' },
      { id: 'apps', nombre: 'App suite' },
      { id: 'functions', nombre: 'Functions, Web Pixel and theme extensions' },
      { id: 'medicion', nombre: 'First-party data-dd-* measurement' },
      { id: 'qa', nombre: 'Playwright QA harness' },
    ],
    comoTitulo: 'How I work, according to Max',
    comoNota: 'His process, in his words. Figures that come from his CV are attributed to him.',
    comoChecks: 'Checks before publishing',
    comoCommits: '{n} commits across the repos of {t} stores, as of September 2026. They are commits of each store repo, not of one person.',
    ultimosTitulo: 'Model line',
    ultimosLead: 'The most recent work with a real screenshot, as of {fecha}.',
    verObra: 'Compare all work',
    verFicha: 'Open the {nombre} page',
    recibirRevision: 'Get my review',
  },

  obra: {
    lead: 'Each work is a column and each attribute a row. Whatever does not exist is written «—».',
    filtros: 'Filters',
    tipo: 'Type',
    anio: 'Year',
    rol: 'Role',
    tecnologia: 'Technology',
    tipos: { store: 'Stores', product: 'Products', personal: 'Personal', role: 'Deliverables' },
    tipoUno: { store: 'Store', product: 'Product', personal: 'Personal project', role: 'Deliverable of a role' },
    rolCustom: 'Customized',
    mostrando: 'Showing {n}',
    buscar: 'Search',
    rend: 'perf.',
    acc: 'a11y',
    tambien: 'Also',
    enLaTabla: 'in the table',
    lcdContador: '{n} OF {t} WORKS',
    lcdComparando: 'COMPARING {n} · MAX 3',
    lcdLibre: 'PICK UP TO 3 TO COMPARE',
    lcdMovil: 'SWIPE TO COMPARE',
    columnaFija: 'Pinned column · scroll',
    filtrosAbrir: 'Filters',
    modeloN: 'M{n}',
    elegir: 'Pick to compare',
    comparaAncho: 'Compare {n} at full width',
    limpiar: 'Clear',
    masModelos: 'Show {n} more',
    otras: 'See the next {n}',
    anteriores: 'See the previous {n}',
    masFiltros: '+ {n}',
    sinResultados: 'No work matches these filters.',
    tablaAria: 'Work comparison table',
    atributo: 'Attribute',
    comparar: 'Compare',
    compararN: 'Compare {n} models',
    compararAyuda: 'Tick two or three to pin them at full width.',
    comparando: 'Comparing {n} models',
    quitarComparacion: 'Back to all',
    modelo: 'Model',
    filas: {
      rubro: 'Industry',
      tipo: 'Type',
      anio: 'Year',
      construccion: 'Build window',
      rol: 'Role',
      pila: 'Stack',
      git: 'Git',
      lhMovil: 'Lighthouse mobile',
      lhEscritorio: 'Lighthouse desktop',
      catalogo: 'Catalog',
      capturas: 'Screenshots',
    },
    gitCelda: '{commits} commits · {secciones} sections',
    lhMovil: 'Mobile',
    lhEscritorio: 'Desktop',
    lhOrden: 'perf. / a11y / SEO',
    catalogoCelda: '{p} products · {c} collections',
    temaCliente: 'Client theme, not Max’s work',
    si: 'Yes',
    pieGit: 'Git: commits of each store repo, 2026-09-08.',
    pieLighthouse: 'Lighthouse: local run of 2026-09-10, best of 3; only stores on a Digitdeck theme when measured.',
    pieCatalogo: 'Public catalog as of 2026-09-09; not sales.',
  },

  ficha: {
    migas: 'Work',
    resumen: 'Overview',
    specs: 'Specs',
    hechoCon: 'Built with',
    anclas: 'Sections of this page',
    galeria: 'Screenshots',
    vista: 'View',
    home: 'Home',
    pdp: 'Product page',
    dispositivo: 'Device',
    escritorio: 'Desktop',
    movil: 'Mobile',
    sinCapturas: 'No public screenshots of this work.',
    abrir: 'Open the site',
    hechos: 'Facts',
    labTitulo: 'Lab measurements',
    labNota: 'Local run of {fecha}, best of 3. Best Practices is left out: Shopify’s own scripts pin it between 54 and 77.',
    rendimiento: 'Performance',
    accesibilidad: 'Accessibility',
    seo: 'SEO',
    gitTitulo: 'Repository',
    gitNota: 'Commits of the store repo, as of {fecha}.',
    primerCommit: 'First commit',
    ultimoCommit: 'Last commit',
    commits: 'Commits',
    secciones: 'Liquid sections',
    lineasLiquid: 'Liquid lines',
    lineasIslas: 'TS/TSX island lines',
    catalogoTitulo: 'Public catalog',
    catalogoNota: 'Public catalog as of {fecha}; not sales.',
    productos: 'Products',
    colecciones: 'Collections',
    moneda: 'Currency',
    precios: 'Price range',
    hechoConLead: 'In-house products whose name appears in this work’s stack.',
    hechoConNinguno: 'This work’s stack names no in-house product.',
    anterior: 'Previous',
    siguiente: 'Next',
    pedirRevision: 'Ask for my store review',
    pedirCorto: 'Ask for review',
    specsCorto: 'Specs',
    pie: 'More work',
    volver: 'Back to the table',
    noExiste: 'This work is not in the registry',
    semanas: 'Commits per week',
    semanasNota: 'Each bar is one week of the repo, starting {desde}.',
    ver: 'View',
    sitio: 'Site',
    sinMedicion: 'No in-house Lighthouse run for this work.',
    temaCliente: 'The theme serving this domain is the client’s: that run is not Max’s work.',
    stack: 'Stack',
    rol: 'Role',
    anio: 'Year',
    rubro: 'Industry',
    construccion: 'Build window',
    tipo: 'Type',
    movilLab: 'Mobile',
    escritorioLab: 'Desktop',
    lcp: 'LCP',
  },

  trayectoria: {
    lead: 'Each role as a release note: period, company, what changed.',
    hoy: 'Today',
    segunCv: 'Figures from Max’s CV, attributed to this role and its period.',
    cambios: 'Changes',
    cifras: 'Role figures',
    tiendasConstruidas: '{n} storefronts built',
    presente: 'present',
    compatibilidad: 'Compatibility',
    compatLead: 'Tools by group and how many registry entries name them in their stack.',
    mencionada: 'Named in {n} entries',
    mencionadaUna: 'Named in 1 entry',
    delCv: 'In Max’s CV',
    plegadas: '{n} tools the entries’ stacks do not name',
    plegadasNota: 'This does not measure what Max uses: it measures what he wrote in each work’s entry.',
    compatNota: 'The count comes from hand-written expressions over the stacks of stores, products and deliverables; it is not «N stores use it».',
    grupos: 'Tool groups',
    nota: 'Note {n} of {t}',
    aniosAria: 'One line per year',
    actual: 'Current',
    riel: 'Release notes, newest to oldest',
    lugar: 'Place',
    tipoEmpleo: 'Type',
    empleo: { 'full-time': 'Full time', 'part-time': 'Part time', contract: 'Contract' },
    sinTitulo: 'Current role at Digitdeck',
  },

  contacto: {
    modos: 'What you need',
    modosAyuda: 'Pick a way to start; it sets the email subject and the form reason.',
    puertos: 'Back panel',
    puertosAria: 'Direct channels',
    correo: 'Email',
    copiar: 'Tap to copy',
    copiado: 'Email copied',
    abrirCorreo: 'Open in your mail app',
    whatsapp: 'WhatsApp',
    llamada: 'Call',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    cv: 'CV',
    cvValor: 'PDF · 2 pages · in English',
    perfil: 'Profile',
    formularioTitulo: 'Compact form',
    tienda: 'Your store URL',
    tiendaAyuda: 'Optional',
    correoCampo: 'Your email',
    enviar: 'Send',
    enviando: 'Sending…',
    ok: 'Sent. Thanks: I will look at your store and write back.',
    error: 'It could not be sent. Your mail app opened with the message ready.',
    procedimiento: 'Procedure',
    pasoDe: 'Step {n} of {t}',
    siguiente: 'What happens next',
    faq: 'Frequently asked questions',
    hora: 'Time in Medellín',
    oferta: 'What I offer',
    titulo: 'Contact',
    leadPuertos: 'Six direct ports. Tap one: the email is copied and the others open.',
    ledEncendido: 'lit',
    apagado: 'Standby',
    asuntoRevision: 'Free 20-minute review',
    formularioAyuda: 'Three details are enough to start.',
    motivo: 'Reason',
    camposRequeridos: 'An email is needed so I can reply.',
    entregable: 'You get',
  },
}

export type Copy = typeof es
const textos: Record<'es' | 'en', Copy> = { es, en }

/** Etiquetas de la dirección en el idioma activo (ja cae a en). */
export function useCopy(): Copy {
  const { locale } = useLanguage()
  return textos[locale === 'es' ? 'es' : 'en']
}

/** Rellena los {marcadores} de una etiqueta. */
export const llenar = (t: string, v: Record<string, string | number>) => t.replace(/\{(\w+)\}/g, (_, k) => String(v[k] ?? ''))
