import { useLanguage } from '../../context/LanguageContext'
import type { ObraKind } from '../data'
import { MOTIVOS, type Motivo } from '../shared/contacto'
import type { CapacidadId } from './publico'

// Etiquetas de interfaz de El Reportaje. Los textos de contenido (obras, cargos, FAQ, hero, proceso) vienen de useV5();
// aquí solo vive lo que escribe el reportaje: titulares de figura, pies, rótulos. Una cifra solo se dice si el registro la
// sostiene. El asunto del correo que llega a Max va siempre en inglés (shared/contacto). El japonés reutiliza el inglés salvo la
// navegación: el contenido sí llega en japonés.
const motivos = (l: 'es' | 'en') => Object.fromEntries(Object.entries(MOTIVOS).map(([k, v]) => [k, v[l]])) as Record<Motivo, string>

const es = {
  saltar: 'Saltar al contenido',
  principal: 'Principal',
  nav: { inicio: 'Inicio', obra: 'Obra', trayectoria: 'Trayectoria', contacto: 'Contacto' },
  /** Número de capítulo en la hoja de papel que cae entre vistas. */
  capitulo: { inicio: 'I', obra: 'II', trayectoria: 'III', contacto: 'IV' },
  idioma: 'Idioma',
  menu: { abrir: 'Abrir el menú', cerrar: 'Cerrar el menú', etiqueta: 'Menú' },
  /** Selector de temas: «Otras ediciones», un quiosco de portadas. */
  ediciones: {
    boton: 'Ediciones',
    etiqueta: 'Otras ediciones: cambiar de tema',
    kicker: (n: number) => `El quiosco · ${n} ediciones`,
    titulo: 'Otras ediciones',
    dek: (n: number) => `La misma carrera, en ${n} portadas. Eliges una y sigues en esta misma vista.`,
    cerrar: 'Cerrar',
    cerrarEtiqueta: 'Cerrar las ediciones',
    actual: 'Edición actual',
    numero: (n: number) => `N.º ${String(n).padStart(2, '0')}`,
  },
  pedir: 'Pedir revisión',
  cvLabel: 'Descargar CV',
  fig: 'Fig.',
  fuente: 'Fuente',
  medida: 'Medida',
  metodo: { titulo: 'Fuentes y método', abrir: 'Abrir fuentes y método', cerrar: 'Cerrar fuentes y método', tablaCifras: 'Las seis cifras, en tabla', cifra: 'Cifra', valor: 'Valor', fuente: 'Fuente', colofon: 'Compuesto en Newsreader, DM Mono y Source Sans 3.' },
  kinds: { store: 'Tienda', product: 'Producto', role: 'Entregable', personal: 'Proyecto personal' } satisfies Record<ObraKind, string>,
  leerCaso: 'Leer el caso',
  enConstruccion: 'En construcción',
  capacidades: { bundles: 'Bundles', quiz: 'Quiz', subscriptions: 'Suscripciones', reviews: 'Reseñas', migration: 'Migraciones', islands: 'Islas React', tracking: 'Tracking', i18n: 'Multimoneda' } satisfies Record<CapacidadId, string>,

  portada: {
    kicker: 'Reportaje · Edición 2026 · Medellín',
    por: 'Por',
    laminaPie: (fecha: string) => `Capturas reales de la página de inicio en el móvil (390 px), tomadas el ${fecha}.`,
  },
  cifras: {
    kicker: 'Las cifras',
    h2: 'Seis cifras, cada una con su cargo y su periodo',
    lighthouse: {
      titulo: 'Lighthouse, antes y después de la migración del CMS',
      lectura: 'Rendimiento sobre 100. La línea punteada marca 90, el umbral de «bueno» que usa Lighthouse.',
      aria: 'Lighthouse sube de aproximadamente 70 a 95 o más, sobre 100',
      antes: 'Antes',
      despues: 'Después',
      umbral: 'Umbral 90',
    },
    minis: 'Una captura real por tienda',
    minisNota: 'Página de inicio, tomada el',
  },
  casos: {
    kicker: 'Los casos',
    pasoDe: (n: number, t: number) => `Caso ${n} de ${t}`,
    pie: (n: number, t: number, nombre: string, fecha: string) => `Caso ${n} de ${t} · ${nombre} · captura de escritorio (1440 px) y móvil (390 px), ${fecha}`,
    suiteKicker: 'Apps y plataforma detrás',
    suiteH: 'Lo que hay debajo de las tiendas',
    todaLaObra: 'Ver toda la obra',
    dato: 'Dato de la obra',
  },
  proceso: { kicker: 'Cómo se trabaja', pasoDe: (n: number, t: number) => `Paso ${n} de ${t}` },
  cierre: {
    kicker: 'Escríbeme',
    copiar: 'Copiar el correo',
    copiado: 'Copiado',
    estado: (vivo: number, dev: number) => `${vivo} tiendas en vivo · ${dev} en construcción`,
  },

  obra: {
    kicker: 'La obra',
    h1: 'La obra completa',
    filtrar: 'Filtrar por lo que hace',
    todas: 'Todas',
    enVivo: 'En vivo',
    enConstruccion: 'En construcción',
    figSub: 'Capturas reales de la página de inicio, 1440 px, sin retoque. Cada una abre su caso.',
    sinResultados: 'Ninguna obra con captura tiene esa capacidad.',
    productos: 'Apps y plataforma',
    proyectos: 'Proyectos propios',
    entregables: 'Entregables dentro de los cargos',
    sinCaptura: 'Sin captura',
    metodoLineas: [
      'Capturas de la página de inicio y de la página de producto en escritorio (1440 px) y móvil (390 px), tomadas el {fecha}.',
      'Las capacidades se leen del stack que declara cada tienda: una tienda cuenta en «Bundles» si su stack nombra Bundles.',
      '«Construida» es el rol declarado en el registro de tiendas; las que corren sobre un tema de tercero se rotulan «Personalizada sobre…».',
      'El catálogo y las mediciones de cada tienda están en su ficha, con su fecha.',
      'Solo se enlaza una tienda cuando su dominio sirve un tema de Digitdeck.',
    ],
    figFuente: 'registro de obra de Max.',
  },
  ficha: {
    volver: 'Obra',
    visitar: 'Visitar el sitio',
    repo: 'Ver el código',
    historia: 'La historia',
    datos: 'Hoja de datos',
    rubro: 'Rubro',
    rol: 'Rol',
    estado: 'Estado',
    anio: 'Año',
    periodo: 'Periodo',
    empleo: 'Empleo',
    pila: 'Pila',
    catalogo: 'Catálogo',
    catalogoNota: (f: string) => `Catálogo público de la tienda, a ${f}.`,
    codigo: 'Código',
    figHome: 'Página de inicio',
    figPdp: 'Página de producto',
    capturas: (nombre: string, fecha: string) => `${nombre} · 1440 y 390 px · ${fecha}`,
    escritorio: 'Escritorio',
    movil: 'Móvil',
    pdpSub: 'La misma tienda en la página de producto, donde se cierra la venta.',
    medido: 'Medido, con su fecha',
    lighthouse: 'Lighthouse',
    rend: 'Rendimiento',
    acc: 'Accesibilidad',
    seo: 'SEO',
    lhNota: (f: string) => `Medición local del ${f}, mejor de 3, sobre el dominio de la tienda.`,
    git: 'Repositorio',
    commits: 'commits',
    secciones: 'secciones',
    primerCommit: 'primer commit',
    gitNota: (f: string) => `Del repositorio de la tienda, a ${f}.`,
    metodoApunte: 'Ver las mediciones y sus fechas',
    siguiente: 'Siguiente',
    noExiste: 'Esa obra no existe',
    volverObra: 'Volver a la obra',
    enElCargo: 'Hecho dentro del cargo',
    delCargo: 'Lo que dejó el cargo',
    sinCapturaNota: 'Sin captura pública: se muestra solo lo que consta en el registro.',
    queHace: 'Lo que hace',
    dato: 'Dato de la obra',
    medidoT: 'Así rinde hoy la tienda en Lighthouse, en escritorio',
    medidoSub: (f: string) => `Medición local del ${f}, mejor de 3. La de móvil está en Fuentes y método.`,
    lcp: 'LCP, carga del contenido principal',
    relacionada: 'Obra relacionada',
    masCon: (cap: string) => `Más obra con ${cap}`,
    dondeCorre: 'Dónde corre',
    dondeCorreNota: 'Tiendas de la obra que usan este módulo, con su caso.',
    suite: 'Qué incluye',
    suiteNota: 'Cinco módulos en una sola instalación; la lista es la de la ficha del producto.',
    modulos: ['Aviso de stock', 'Bundles', 'Referidos', 'Reseñas', 'Pruebas A/B'],
    suiteCifras: { modulos: 'Módulos de app', pruebas: 'Pruebas automatizadas' },
    /** La captura de un producto no siempre es su pantalla propia: se dice qué muestra. */
    capturaDe: { 'digitdeck-apps': 'El módulo de Bundles en producción: el armador de cajas de NOS Café.' } as Record<string, string>,
  },
  tray: {
    kicker: 'Trayectoria',
    cargosKicker: 'Los cargos',
    cargosH2: 'Cada cargo, con lo que dejó',
    figTitulo: 'Dónde pasó el trabajo, mes a mes',
    figSub: 'Cada barra es un cargo y su largo son los meses. Se ilumina el que estás leyendo.',
    figFuente: 'CV de Maximiliano Bustamante, cargo por cargo.',
    escala: 'Escala: meses',
    meses: (n: number) => `${n} m`,
    leyendo: 'Leyendo',
    tiempoCompleto: 'Tiempo completo',
    contrato: 'Contrato',
    parcial: 'Medio tiempo',
    logros: 'Qué se entregó',
    pila: 'Pila',
    visitar: 'Visitar el sitio',
    aniosKicker: 'Año por año',
    habKicker: 'Con qué',
    proyKicker: 'En mi tiempo',
    proyVer: 'Ver el proyecto',
    cierre: 'El CV completo, en PDF',
    metodoLineas: [
      'Cargos, periodos y métricas: el CV de Max, tal cual. Cada métrica está dentro de su cargo y su periodo.',
      'Los cargos se solapan en el tiempo y el diagrama los dibuja solapados.',
      'Las eras de cada año y los textos de los cargos son los de maxfolio.dev.',
      'Los conteos por herramienta salen del stack declarado de cada tienda, producto y cargo.',
    ],
  },
  contacto: {
    kicker: 'Contacto',
    formulario: 'Pide tu revisión',
    viaEscrita: 'Si prefieres escribir, déjame tu tienda y tu correo.',
    tienda: 'La URL de tu tienda',
    tiendaEj: 'tutienda.com',
    correo: 'Tu correo',
    correoEj: 'tu@tienda.com',
    motivos: motivos('es'),
    motivo: 'Motivo',
    enviar: { revision: 'Pedir la revisión', proyecto: 'Contar el proyecto', continuo: 'Hablar del trabajo continuo', empleo: 'Escribir por la vacante' },
    enviando: 'Enviando',
    ok: 'Recibido. Te escribiré al correo que dejaste.',
    error: 'No se pudo enviar. Se abrió tu correo con el mensaje listo.',
    falta: 'Escribe un correo válido.',
    faltaTienda: 'Escribe la URL de tu tienda.',
    elegir: 'Elegir este modelo',
    canales: 'Canales',
    canalCorreo: 'Correo',
    copiar: 'Copiar',
    copiado: 'Copiado',
    whatsapp: 'WhatsApp',
    waTexto: 'Hola Max, quiero la revisión gratis de 20 minutos de mi tienda.',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    cv: 'CV en PDF',
    modelosKicker: 'Tres formas de empezar',
    faqKicker: 'Preguntas',
    faq: 'Antes de escribir',
  },
  pie: { medellin: 'Medellín, Colombia', arriba: 'Volver arriba', hora: 'hora local' },
}

export type Copy = typeof es

const en: Copy = {
  saltar: 'Skip to content',
  principal: 'Main',
  nav: { inicio: 'Home', obra: 'Work', trayectoria: 'Career', contacto: 'Contact' },
  capitulo: { inicio: 'I', obra: 'II', trayectoria: 'III', contacto: 'IV' },
  idioma: 'Language',
  menu: { abrir: 'Open the menu', cerrar: 'Close the menu', etiqueta: 'Menu' },
  /** Selector de temas: «Otras ediciones», un quiosco de portadas. */
  ediciones: {
    boton: 'Editions',
    etiqueta: 'Other editions: change theme',
    kicker: (n: number) => `The newsstand · ${n} editions`,
    titulo: 'Other editions',
    dek: (n: number) => `The same career on ${n} covers. Pick one and you stay on this same page.`,
    cerrar: 'Close',
    cerrarEtiqueta: 'Close the editions',
    actual: 'Current edition',
    numero: (n: number) => `No. ${String(n).padStart(2, '0')}`,
  },
  pedir: 'Book a review',
  cvLabel: 'Download CV',
  fig: 'Fig.',
  fuente: 'Source',
  medida: 'Measure',
  metodo: { titulo: 'Sources and method', abrir: 'Open sources and method', cerrar: 'Close sources and method', tablaCifras: 'The six figures, as a table', cifra: 'Figure', valor: 'Value', fuente: 'Source', colofon: 'Set in Newsreader, DM Mono and Source Sans 3.' },
  kinds: { store: 'Store', product: 'Product', role: 'Deliverable', personal: 'Personal project' },
  leerCaso: 'Read the case',
  enConstruccion: 'In progress',
  capacidades: { bundles: 'Bundles', quiz: 'Quiz', subscriptions: 'Subscriptions', reviews: 'Reviews', migration: 'Migrations', islands: 'React islands', tracking: 'Tracking', i18n: 'Multi-currency' },

  portada: {
    kicker: 'Report · 2026 edition · Medellín',
    por: 'By',
    laminaPie: (fecha: string) => `Real screenshots of the home page on mobile (390 px), taken on ${fecha}.`,
  },
  cifras: {
    kicker: 'The figures',
    h2: 'Six figures, each with its role and its period',
    lighthouse: {
      titulo: 'Lighthouse, before and after the CMS migration',
      lectura: 'Performance out of 100. The dotted line marks 90, the “good” threshold Lighthouse uses.',
      aria: 'Lighthouse rises from about 70 to 95 or more, out of 100',
      antes: 'Before',
      despues: 'After',
      umbral: 'Threshold 90',
    },
    minis: 'One real screenshot per store',
    minisNota: 'Home page, taken on',
  },
  casos: {
    kicker: 'The cases',
    pasoDe: (n: number, t: number) => `Case ${n} of ${t}`,
    pie: (n: number, t: number, nombre: string, fecha: string) => `Case ${n} of ${t} · ${nombre} · desktop (1440 px) and mobile (390 px) screenshot, ${fecha}`,
    suiteKicker: 'Apps and platform behind',
    suiteH: 'What sits under the stores',
    todaLaObra: 'See all the work',
    dato: 'Fact from the work',
  },
  proceso: { kicker: 'How I work', pasoDe: (n: number, t: number) => `Step ${n} of ${t}` },
  cierre: {
    kicker: 'Write to me',
    copiar: 'Copy the email',
    copiado: 'Copied',
    estado: (vivo: number, dev: number) => `${vivo} storefronts live · ${dev} in development`,
  },

  obra: {
    kicker: 'The work',
    h1: 'The complete work',
    filtrar: 'Filter by what it does',
    todas: 'All',
    enVivo: 'Live',
    enConstruccion: 'In development',
    figSub: 'Real screenshots of the home page at 1440 px, untouched. Each opens its case.',
    sinResultados: 'No work with a screenshot has that capability.',
    productos: 'Apps and platform',
    proyectos: 'Side projects',
    entregables: 'Deliverables inside the roles',
    sinCaptura: 'No screenshot',
    metodoLineas: [
      'Screenshots of the home page and the product page on desktop (1440 px) and mobile (390 px), taken on {fecha}.',
      'Capabilities are read from each store’s declared stack: a store counts under “Bundles” if its stack names Bundles.',
      '“Built” is the role declared in the store register; stores on a third-party theme are labelled “Customized on…”.',
      'Each store’s catalog and measurements are on its page, with their date.',
      'A store is linked only when its domain serves a Digitdeck theme.',
    ],
    figFuente: 'Max’s work register.',
  },
  ficha: {
    volver: 'Work',
    visitar: 'Visit the site',
    repo: 'See the code',
    historia: 'The story',
    datos: 'Fact sheet',
    rubro: 'Category',
    rol: 'Role',
    estado: 'Status',
    anio: 'Year',
    periodo: 'Period',
    empleo: 'Employer',
    pila: 'Stack',
    catalogo: 'Catalog',
    catalogoNota: (f: string) => `Public store catalog, as of ${f}.`,
    codigo: 'Code',
    figHome: 'Home page',
    figPdp: 'Product page',
    capturas: (nombre: string, fecha: string) => `${nombre} · 1440 and 390 px · ${fecha}`,
    escritorio: 'Desktop',
    movil: 'Mobile',
    pdpSub: 'The same store on the product page, where the sale closes.',
    medido: 'Measured, with its date',
    lighthouse: 'Lighthouse',
    rend: 'Performance',
    acc: 'Accessibility',
    seo: 'SEO',
    lhNota: (f: string) => `Local measurement of ${f}, best of 3, on the store’s domain.`,
    git: 'Repository',
    commits: 'commits',
    secciones: 'sections',
    primerCommit: 'first commit',
    gitNota: (f: string) => `From the store’s repository, as of ${f}.`,
    metodoApunte: 'See the measurements and their dates',
    siguiente: 'Next',
    noExiste: 'That work does not exist',
    volverObra: 'Back to the work',
    enElCargo: 'Done inside the role',
    delCargo: 'What the role left',
    sinCapturaNota: 'No public screenshot: only what the register states is shown.',
    queHace: 'What it does',
    dato: 'Fact from the work',
    medidoT: 'How the store scores on Lighthouse today, on desktop',
    medidoSub: (f: string) => `Local measurement of ${f}, best of 3. The mobile one is in Sources and method.`,
    lcp: 'LCP, main content load',
    relacionada: 'Related work',
    masCon: (cap: string) => `More work with ${cap}`,
    dondeCorre: 'Where it runs',
    dondeCorreNota: 'Stores in the work that use this module, with their case.',
    suite: 'What it includes',
    suiteNota: 'Five modules in a single install; the list is the one on the product sheet.',
    modulos: ['Stock alerts', 'Bundles', 'Referrals', 'Reviews', 'A/B tests'],
    suiteCifras: { modulos: 'App modules', pruebas: 'Automated tests' },
    capturaDe: { 'digitdeck-apps': 'The Bundles module in production: NOS Café’s box builder.' },
  },
  tray: {
    kicker: 'Career',
    cargosKicker: 'The roles',
    cargosH2: 'Each role, with what it left',
    figTitulo: 'Where the work happened, month by month',
    figSub: 'Each bar is a role and its length is the months. The one you are reading lights up.',
    figFuente: 'Maximiliano Bustamante’s CV, role by role.',
    escala: 'Scale: months',
    meses: (n: number) => `${n} mo`,
    leyendo: 'Reading',
    tiempoCompleto: 'Full time',
    contrato: 'Contract',
    parcial: 'Part time',
    logros: 'What shipped',
    pila: 'Stack',
    visitar: 'Visit the site',
    aniosKicker: 'Year by year',
    habKicker: 'With what',
    proyKicker: 'On my own time',
    proyVer: 'See the project',
    cierre: 'The full CV, as a PDF',
    metodoLineas: [
      'Roles, periods and metrics: Max’s CV, as is. Each metric sits inside its role and period.',
      'The roles overlap in time and the diagram draws them overlapping.',
      'The era of each year and the role texts are those of maxfolio.dev.',
      'The count per tool comes from the declared stack of each store, product and role.',
    ],
  },
  contacto: {
    kicker: 'Contact',
    formulario: 'Book your review',
    viaEscrita: 'Prefer to write? Leave me your store and your email.',
    tienda: 'Your store URL',
    tiendaEj: 'yourstore.com',
    correo: 'Your email',
    correoEj: 'you@store.com',
    motivos: motivos('en'),
    motivo: 'Reason',
    enviar: { revision: 'Book the review', proyecto: 'Tell me about the project', continuo: 'Talk about ongoing work', empleo: 'Write about the role' },
    enviando: 'Sending',
    ok: 'Received. I will write back to the email you left.',
    error: 'It could not be sent. Your email app opened with the message ready.',
    falta: 'Enter a valid email.',
    faltaTienda: 'Enter your store URL.',
    elegir: 'Choose this model',
    canales: 'Channels',
    canalCorreo: 'Email',
    copiar: 'Copy',
    copiado: 'Copied',
    whatsapp: 'WhatsApp',
    waTexto: 'Hi Max, I would like the free 20-minute review of my store.',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    cv: 'CV as PDF',
    modelosKicker: 'Three ways to start',
    faqKicker: 'Questions',
    faq: 'Before you write',
  },
  pie: { medellin: 'Medellín, Colombia', arriba: 'Back to top', hora: 'local time' },
}

const ja: Copy = {
  ...en,
  saltar: '本文へ移動',
  nav: { inicio: 'ホーム', obra: '実績', trayectoria: '経歴', contacto: '連絡' },
  idioma: '言語',
  menu: { abrir: 'メニューを開く', cerrar: 'メニューを閉じる', etiqueta: 'メニュー' },
  /** Selector de temas: «Otras ediciones», un quiosco de portadas. */
  ediciones: {
    boton: '別の号',
    etiqueta: '別の号：テーマを切り替え',
    kicker: (n: number) => `キオスク · 全${n}号`,
    titulo: '別の号',
    dek: (n: number) => `同じキャリアを${n}つの表紙で。号を選んでも、いまのページのままです。`,
    cerrar: '閉じる',
    cerrarEtiqueta: '号の一覧を閉じる',
    actual: '現在の号',
    numero: (n: number) => `第${n}号`,
  },
  pedir: 'レビューを依頼',
  cvLabel: '履歴書をダウンロード',
  pie: { medellin: 'コロンビア・メデジン', arriba: 'ページの先頭へ', hora: '現地時間' },
}

const DICCIONARIOS = { es, en, ja }
export const useCopy = (): Copy => DICCIONARIOS[useLanguage().locale]
