import type { PortfolioContent } from './types'

export const en: PortfolioContent = {
  meta: {
    title: 'Maximiliano Bustamante | CTO & Shopify Tech Lead',
    description:
      'CTO & Shopify Tech Lead at Digitdeck. 18+ Shopify storefronts, a production app suite, and the delivery system behind them. Open for Shopify CRO consulting.',
  },
  hero: {
    eyebrow: 'CTO & Shopify Tech Lead · Digitdeck',
    positioning: 'Your Shopify store has traffic. I find where it stops turning into orders.',
    lead: '18+ storefronts, a multi-tenant app suite and a QA harness that catches what a launch would have broken. You get Shopify engineering that is measured: what moved, why, and what to do next.',
    availability: 'Open for Shopify CRO consulting and quotes',
    location: 'Based in Medellín, working with US and LATAM brands',
    ctaContact: 'Get in touch',
    ctaPrimary: 'Get a free 20-minute store review',
    ctaSecondary: 'See the 18+ storefronts',
    ctaNote: 'No pitch, no contract. Just where the store leaks and what to fix first.',
    ctaCv: 'Download CV',
  },
  stats: {
    storefronts: 'Shopify storefronts',
    tests: 'Automated tests',
    conversion: 'Conversion lift, Shopify storefronts',
    savings: 'Saved per year, enterprise CMS migration',
    subscriptions: 'Subscriptions on a live recurring-billing integration',
    contacts: 'Contacts on an enterprise newsletter platform',
  },
  statSources: {
    storefronts: 'Digitdeck storefronts, 2024–2026',
    tests: 'Digitdeck app suite, 2026',
    conversion: 'Frontend Developer (Shopify), Digitdeck, 2023–2024',
    savings: 'Frontend Developer, RH, 2024–2025',
    subscriptions: 'CTO & Shopify Technical Lead, Digitdeck, 2026',
    contacts: 'Full Stack Developer, ABI Data, 2025',
  },
  sections: {
    experience: { eyebrow: 'Every role, in order', title: 'Where the work', titleAccent: 'happened', achievements: 'What shipped', technologies: 'Stack', visit: 'Visit website' },
    shopify: {
      eyebrow: 'Real stores, real checkouts',
      title: 'Storefronts, apps,',
      titleAccent: 'and the platform behind them',
      lead: 'Open any store below and you are one click from its real checkout, not a mockup. 18+ storefronts: bundles priced by Shopify Functions, product quizzes, review walls, dual-currency catalogs, migrations from Framer and WooCommerce.',
      tabStores: 'Storefronts',
      tabProducts: 'Apps & platform',
      legacyLabel: 'Earlier work',
      visit: 'Visit store',
      showAll: 'Show all {n} stores',
      showLess: 'Show fewer',
      filterAll: 'All',
      filters: { bundles: 'Bundles', quiz: 'Quiz', subscriptions: 'Subscriptions', reviews: 'Reviews', migration: 'Migrations', islands: 'React islands', tracking: 'Tracking', i18n: 'Multi-currency' },
    },
    gallery: {
      eyebrow: 'Built for the phone in their hand',
      title: 'Built to sell,',
      titleAccent: 'on every screen',
      lead: 'Every store here gets the same standard: a home page that earns the click and a product page that closes it, on the phone your customers actually use. Hover to flip to the product page; open a store and you see the four captures, the build and what it runs on.',
      filterAll: 'All',
      filterLive: 'Live',
      filterDev: 'In development',
      viewLabel: 'View',
      viewCarousel: 'Carousel',
      viewDevices: 'Laptop + phone',
      viewPhones: 'Phones only',
      open: 'Open gallery',
      close: 'Close',
      home: 'Home',
      pdp: 'Product page',
      desktop: 'Desktop',
      mobile: 'Mobile',
    },
    process: {
      eyebrow: 'How it ships',
      title: 'Five steps,',
      titleAccent: 'no surprises',
      problemLabel: 'The bottleneck.',
      problem: 'Speed, offers or checkout friction: most stores leak revenue in one of three places, and most teams guess which.',
      fixLabel: 'The fix.',
      fix: 'Five checkpoints in the same order every time, so you know what happens next and what you get at each one.',
      stepOf: 'Step {n} of {total}',
      deliverableLabel: 'You get',
      steps: [
        { title: 'Discovery', body: 'Your store, your numbers, your bottlenecks. I read the data before touching a line.', deliverable: 'A written diagnosis: where the store leaks and what to fix first.' },
        { title: 'Pattern map', body: 'Every page gets a plan: which sections, which offers, which proof, in what order.', deliverable: 'A page-by-page plan you can read before a line is written.' },
        { title: 'Build', body: 'Liquid + React islands on the Digitdeck template, instrumented from the first commit.', deliverable: 'A theme in git, reporting first-party events from day one.' },
        { title: 'QA', body: 'A Playwright harness runs the whole store behaviorally before anything goes live.', deliverable: 'A behavioral test run across the whole store, with its report.' },
        { title: 'Handoff', body: 'The store is yours to run: every setting lives in the editor, every decision in the docs.', deliverable: 'The editor, the docs and the numbers. Nothing depends on me.' },
      ],
    },
    faq: {
      eyebrow: 'Before you write',
      title: 'Questions I get',
      titleAccent: 'before the first call',
      items: [
        { q: 'Do I need Shopify Plus?', a: 'No. Most of these stores run on standard Shopify. The bundles priced by Shopify Functions, the app suite and the tracking work on both plans.' },
        { q: 'What if my store already converts well?', a: 'Then the review says so, with the numbers, and we stop there. I only propose work where there is a measurable gap.' },
        { q: 'What do I actually get at the end?', a: 'A theme in git, first-party tracking from the first day, a behavioral QA run before launch, and the editor plus the docs at handoff. Nothing depends on me to keep running.' },
        { q: 'Can you work alongside my team or agency?', a: 'Yes. Every store here shipped with the client keeping the editor and the content. I take the engineering, the QA gate and the measurement.' },
        { q: 'How long does a build take?', a: 'It depends on the scope. Discovery ends with a written window, and you follow progress issue by issue on a shared board.' },
        { q: 'Are you vetted by Shopify?', a: 'I\'m a working Shopify Tech Lead — the 18+ stores on this page are the credential, not a badge.' },
        { q: 'Did an AI build this portfolio?', a: 'Every section started as a Figma or Framer reference I approved, then got built by hand. Sample data is always labeled.' },
      ],
    },
    manifesto: { label: 'What doesn\'t change', lines: ['Read the numbers before the code.', 'Ship from git, never from the editor.', 'Test the whole store, not one page.', 'Hand over the keys.'] },
    testimonials: { eyebrow: 'In their words', title: 'What clients', titleAccent: 'say' },
    now: { label: 'Now', live: '{n} storefronts live', dev: '{n} in development', band: 'Storefronts shipped', local: 'Medellín · {time} local' },
    statBand: { label: 'The work, in numbers', asOf: 'September 2026', sourceLabel: 'Source' },
    careerSubway: { eyebrow: 'Career map', title: 'The roles,', titleAccent: 'on one line', lead: 'Six years as a subway map: one line per employer, a transfer where two roles overlapped.', toggleShow: 'View as a map', toggleHide: 'Hide the map', transferLabel: 'Overlap', rowAria: '{company}: {period}' },
    years: { eyebrow: 'One block per year, nothing padded', title: 'Five years,', titleAccent: 'one direction', lead: 'From React components in 2022 to a fleet of Shopify stores and the platform behind them. Every line is derived from the same records as the rest of the site.', roles: 'Roles', shipped: 'Storefronts', work: 'Client projects', products: 'Products', side: 'On my own time', more: '+{n} more', count: '{n} storefronts', perYear: 'Shipped work whose build touched the year', eras: { '2022': 'React and Salesforce', '2023': 'First Shopify storefronts', '2024': 'Enterprise front end, then CTO', '2025': 'CTO and contract builds', '2026': 'The fleet and the platform' } },
    chapters: {
      eyebrow: 'One block per year, nothing padded',
      title: 'Five years,',
      titleAccent: 'one direction',
      lead: 'From React components in 2022 to a fleet of Shopify stores and the platform behind them. Every card is derived from the same records as the rest of the site.',
      chapterOf: '{n} / {total}',
      prevAria: 'Previous year',
      nextAria: 'Next year',
      highlightsLabel: 'Highlights',
    },
    featuredBuild: {
      eyebrow: 'One build, in full',
      title: 'NOS Café,',
      titleAccent: 'start to finish',
      lead: 'One storefront followed from the finished Framer design to the live checkout — the same records as the rest of the site, just slower.',
      visit: 'Visit cafesnos.com',
      beats: [
        { label: 'The problem', body: 'A finished Framer design that could not lose a pixel on its way to Shopify, and a box builder the roaster needed: up to five bags per box, a discount that climbs as it fills.' },
        { label: 'The plan', body: 'Port the design 1:1 to Liquid, add React islands only where the builder needs interaction, and price the ladder through a Shopify Function so it applies itself at checkout — no coupon to find.' },
        { label: 'The build', body: '{commits} commits and {sections} custom sections, {range}.' },
        { label: 'The result', body: 'Live at {url} — {products} products, {collections} collections, {priceRange} — the {ladder} ladder holds at every step.' },
      ],
    },
    reviewChecklist: {
      eyebrow: 'What a review actually checks',
      title: 'Not a glance —',
      titleAccent: 'a harness',
      lead: 'The free review runs the same Playwright QA harness behind every Digitdeck store: it crawls, clicks and measures, then reports what it finds.',
      countLabel: '{n}+ automated checks',
      cta: 'Get the free 20-minute review',
      groups: [
        { label: 'Commerce', items: ['Buy-more-get-more discounts merge into one cart line, not several', 'Cart state matches the real /cart.js truth, not a cached guess', 'Gift discounts are backed by a real automatic discount, not a fake price'] },
        { label: 'Content', items: ['Card titles render in the theme\'s real display font', 'Empty states never look like a stuck loading spinner', 'Media keeps its declared aspect ratio instead of jumping'] },
        { label: 'Data', items: ['Every field has a non-empty default fill', 'Ratings are never a fabricated placeholder', 'Every section carries the tracking hooks it claims to'] },
        { label: 'Geometry', items: ['A grid only becomes a carousel past 4 items', 'Carousels keep the 15px gap standard', 'Edge-bleed layouts stay aligned at rest', 'Cards in the same row keep equal height', 'Mobile carousels peek the next item', 'No section causes horizontal overflow', 'The page frame respects its two width knobs', 'PDP urgency messaging sits at the right offset'] },
        { label: 'Motion', items: ['Carousels step one item at a time', 'A measurement never re-triggers its own animation', 'Reduced motion is actually respected', 'Every scroll reveal actually executes'] },
        { label: 'Navigation', items: ['Every anchor link resolves to a real section', 'Mega menus behave on hover and on touch'] },
        { label: 'Overlays', items: ['Backdrops cover the header, not just the body', 'Scroll locks while an overlay is open', 'Sticky buy bars complete their two-phase reveal', 'Z-index order never lets one overlay hide behind another'] },
      ],
    },
    fiveLines: {
      kinds: {
        stores: { one: 'one', singular: 'storefront', plural: 'storefronts' },
        work: { one: 'one', singular: 'client project', plural: 'client projects' },
        products: { one: 'one', singular: 'product', plural: 'products' },
        personal: { one: 'one', singular: 'side project', plural: 'side projects' },
      },
      numberWords: ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen', 'twenty'],
      joiner: ' ',
      listJoiner: ', ',
      listFinal: ' and ',
      empty: 'a quiet year',
    },
    yearStrip: {
      legend: 'Build or role active',
      monthAria: '{month} — {state}',
      activeState: 'build or role active',
      inactiveState: 'quiet',
      currentState: 'current month',
      countUnit: 'active months',
    },
    projects: { eyebrow: 'The app suite, outside Shopify', title: 'Things I build', titleAccent: 'on my own time', view: 'View project' },
    skills: {
      eyebrow: 'What shipped, not installed',
      title: 'What I',
      titleAccent: 'work with',
      groups: { shopify: 'Shopify', frontend: 'Frontend', backend: 'Backend', quality: 'Testing & CI/CD', cro: 'CRO & analytics', ai: 'AI engineering' },
      usageLabel: 'Across the fleet',
      usageUnit: 'stores',
      usageNote: 'Counted from the {n} storefronts in the index above, not estimated.',
      usageItems: { liquid: 'Liquid themes', react: 'React islands', framer: 'Framer → Liquid ports', tailwind: 'Tailwind', metaobjects: 'Metaobjects', tracking: 'First-party tracking', bundles: 'Bundles', quiz: 'Product quizzes', reviews: 'Review walls', migration: 'Platform migrations' },
      narrative: {
        shopify: 'Storefronts and apps ship on {skills}.',
        frontend: 'The front end runs on {skills}.',
        backend: 'Behind it, {skills}.',
        quality: 'Nothing goes live without {skills}.',
        cro: 'The numbers come from {skills}.',
        ai: 'The delivery system is built with {skills}.',
      },
      groupNote: {
        shopify: "Storefronts and apps ship directly on Shopify's platform primitives.",
        frontend: 'The front end is React islands mounted into Liquid, only where interaction earns it.',
        backend: 'The backend behind the apps and the Platform is the same one running in production.',
        quality: 'Nothing goes live without an automated pass first.',
        cro: 'Every number quoted here comes from the fleet, not a benchmark.',
        ai: 'The build pipeline itself runs on AI agents, end to end.',
      },
      sunburst: {
        caption: 'Hover, tap or tab an arc — the number behind it is real.',
        storesUnit: '{n} stores',
        storesUnitOne: '{n} store',
        productsUnit: '{n} products',
        productsUnitOne: '{n} product',
        roleUnit: '{n} client roles',
        roleUnitOne: '{n} client role',
        noData: 'In the toolkit, no fleet count yet',
        legendLabel: 'Ring legend',
        triLiquid: 'Lines of Liquid, across the fleet',
        triTs: 'Lines of TypeScript, across the fleet',
        triStoresDefault: '{n} stores in the fleet',
        depthLabel: 'Depth',
      },
      panel: {
        eyebrow: 'Selected tool',
        pinned: 'Pinned',
        hint: 'Click or press Enter to pin it — Esc releases it.',
      },
    },
    contact: {
      eyebrow: 'Diagnosis first, free, 20 minutes',
      title: 'Your store gets the traffic.',
      titleAccent: 'Let\'s turn more of it into orders.',
      lead: 'Send me your store. In 20 minutes I show you where it leaks — speed, offers, checkout friction — and what to fix first.',
      promise: 'Free, no pitch. You leave knowing what to fix first, whether or not we work together.',
      status: 'Available for consulting',
      note: 'US and LATAM brands. You hear back within one business day.',
      cta: 'Get the free 20-minute review',
      ctaSecondary: 'Or email me',
      nextLabel: 'What happens next',
      next: ['Send your store URL through the form or by email.', 'You hear back within one business day.', 'A 20-minute call: where the store leaks and what to fix first.', 'If we work together, the diagnosis comes first, then the fix.'],
      urlLabel: 'Your store URL',
      urlPlaceholder: 'yourstore.com',
      email: 'Email',
      phone: 'Phone',
      location: 'Location',
      elsewhere: 'Elsewhere',
    },
    explore: { eyebrow: 'Explore', title: 'Same portfolio, four designs', lead: 'Pick the aesthetic you prefer. The content is identical.', viewing: 'Currently viewing' },
    caseStudy: {
      facts: 'Store facts', results: 'Measured results', stack: 'Stack', visit: 'Visit store', prev: 'Previous', next: 'Next', timeline: 'Build window', commits: 'commits', sections: 'custom sections', open: 'Case study', metrics: 'Lighthouse · mobile', perf: 'Performance', a11y: 'Accessibility', bp: 'Best practices', seo: 'SEO', lcp: 'LCP', measured: 'Lab run on the home page, {date}, median of {runs} Lighthouse runs (mobile, simulated throttling).', trail: 'Build trail', trailNote: 'From the store repo\'s git history: {n} commits, {range}. Lines counted over the theme\'s layout, sections, snippets and templates.', perWeek: 'Commits per week', peak: 'Busiest week: {n} commits', codebase: 'Codebase', liquidLines: 'lines of Liquid', islandLines: 'lines of TypeScript', sectionsCount: 'theme sections', weeks: 'weeks', copyLink: 'Copy link', copied: 'Copied',
      commerce: {
        title: 'By the numbers',
        catalogLabel: 'Catalog',
        offerLabel: 'Offer',
        deliveryLabel: 'Delivery',
        reachLabel: 'Reach',
        catalogLine: '{products} products · {collections} collections · from {price}',
        catalogLineNoPrice: '{products} products · {collections} collections',
        deliveryLine: 'Shipped in {weeks} weeks · live since {month}',
        reachLine: '{currency} · ships to {n} places',
        reachLineSingle: '{currency} pricing',
        offerFallback: 'Custom Shopify build',
        offerKind: { ladder: 'Bundle ladder', tracked: 'Instrumented UI', offers: 'Synced offers', transfer: 'Store transfer', quality: 'Web-quality pass', pricing: 'Dual pricing', sync: 'Catalog sync', ab: 'A/B testing', reviews: 'Seeded reviews', ads: 'Ad landing pages', migration: 'Platform migration' },
        vsFleetPct: '{sign}{pct}% vs fleet median',
        vsFleetWeeks: '{sign}{n} wk vs fleet median',
        unavailable: 'Public catalog not shown',
        engineering: 'Engineering detail',
      },
    },
  },
  badges: { live: 'Live', dev: 'In development', current: 'Current', completed: 'Completed', roles: { built: 'Built', maintained: 'Maintained', migrated: 'Migrated' } },
  experience: {
    'digitdeck-cto': {
      title: 'CTO & Shopify Technical Lead',
      summary: 'I set the engineering standard for a Shopify agency and build the delivery system itself: component libraries, automated QA, CI/CD, and AI-agent tooling.',
      highlights: [
        'Standardized a hybrid Liquid + React islands architecture with a 33-component shared library and design tokens spanning 14 brands.',
        'Built a multi-tenant Shopify app suite on the official Remix stack — A/B testing, reviews, bundles, referrals, back in stock — plus a subscription billing engine with 800+ automated tests.',
        'Shipped Shopify Functions compiled to WASM, a consent-gated Web Pixel, and Theme App Extensions.',
        'Led WooCommerce-to-Shopify and staging-to-production migrations; re-platformed an 11,000-line Liquid theme into React islands with verified visual parity.',
        'Built GitHub Actions pipelines and a Playwright harness that tests whole storefronts behaviorally, with 40+ Shopify-specific checks.',
        'Researched 59 DTC brands into a 70-pattern conversion library and wrote the agency\'s Bayesian A/B testing methodology.',
      ],
      metricLabels: { storefronts: 'Storefronts', modules: 'App modules', tests: 'Automated tests' },
    },
    ellamau: {
      title: 'Lead Shopify Developer',
      summary: 'Full Shopify storefront build for a US fashion brand, from planning to deployment.',
      highlights: ['Modular Liquid sections with reusable blocks and configurable schemas.', '15+ responsive templates, mobile first.', 'Lighthouse above 90 after optimization.'],
      metricLabels: { templates: 'Templates', lighthouse: 'Lighthouse' },
    },
    abidata: {
      title: 'Full Stack Developer',
      summary: 'Internal platform to create, customize, and send enterprise newsletters.',
      highlights: ['React email editor that cut campaign creation time by about 40%.', '10,000+ contact records and hundreds of active campaigns.', 'Owned the REST APIs from design to deployment.'],
      metricLabels: { contacts: 'Contacts', campaignTime: 'Campaign time', users: 'Internal users' },
    },
    rh: {
      title: 'Frontend Developer',
      summary: 'Enterprise CMS migration from Adobe AEM to Contentful for a large US retailer.',
      highlights: ['25+ reusable components that made the migration possible.', 'Accessibility work took Lighthouse from ~70 to 95+.', 'Cut content-authoring costs by roughly $45,000 a year.'],
      metricLabels: { components: 'Components', lighthouse: 'Lighthouse', savings: 'Savings' },
    },
    'digitdeck-fe': {
      title: 'Frontend Developer (Shopify)',
      summary: 'Built and optimized Shopify storefronts with custom Liquid themes.',
      highlights: ['Custom sections, blocks, and snippets for 4+ storefronts.', 'UX and checkout work lifted conversion 10–20%.', 'Pages loaded 30–40% faster; organic traffic up 20%+.'],
      metricLabels: { conversion: 'Conversion', loadTime: 'Load time', organic: 'Organic traffic' },
    },
    orthofix: {
      title: 'Salesforce Developer',
      summary: 'Internal healthcare applications for patient and operations workflows.',
      highlights: ['Lightning Web Components used by 50+ internal users.', 'Workflows over thousands of patient and device records.', 'About 20% less manual data entry.'],
      metricLabels: { users: 'Users', dataEntry: 'Manual entry' },
    },
    ibox: {
      title: 'Frontend React Developer',
      summary: 'Company website for smart-locker solutions in US and LATAM markets.',
      highlights: ['20+ reusable React components and 10+ responsive pages.', 'Lighthouse 90+ and ~35% faster loads.'],
      metricLabels: { components: 'Components', pages: 'Pages', lighthouse: 'Lighthouse' },
    },
  },
  roleWork: {
    'ibox-site': 'iBox smart-locker website',
    'orthofix-apps': 'Orthofix internal healthcare apps',
    'rh-migration': 'RH CMS migration, AEM → Contentful',
    'abidata-newsletters': 'ABI Data newsletter platform',
    'ellamau-storefront': 'Ellamau Shopify storefront',
  },
  stores: {
    'the-gummy-box': { industry: 'Functional gummies', tagline: 'Bundle builder wired to our Bundles module, subscriptions, first-party tracking.', description: 'The kit offer had to be simple for the shopper and impossible to game: the Bundles module prices the kit through a Shopify Function at checkout, so the 10% to 20% ladder applies by itself and there is no coupon to find. Subscriptions run through Treli and every surface reports first-party events, so the brand sees what each block does.', factLabels: { ladder: 'Bundle discount, automatic at checkout' } },
    'nos-cafe': { industry: 'Specialty coffee', tagline: 'Framer design ported 1:1 to Liquid; box builder with tiered discounts.', description: 'A finished Framer design that could not lose a pixel on its way to Shopify. I ported it 1:1 to Liquid and built the box builder the roaster needed: up to five bags per box, grind and size chosen per bag, and a discount that climbs from 10% to 20% as the box fills.', factLabels: { ladder: 'Box discount, climbs with every bag' } },
    millennio: { industry: 'Perfumery', tagline: 'Framer port on React islands, 260+ tracked elements.', description: 'The perfumery wanted its Framer design live on Shopify and wanted to know what shoppers actually touch. The port runs as React islands over a Liquid base, and every card, rail and CTA is instrumented: 260+ tracked elements report to the Optimize dashboard.', factLabels: { tracked: 'Shopper touchpoints measured' } },
    mindfuel: { industry: 'Nootropics', tagline: 'Full React V2 port, promoted to live.', description: 'The brand was rebuilt as a React V2 port on the Digitdeck template and promoted to live on August 20, 2026. Home, product page and the quiz share one component library, so a change ships once and lands everywhere.', factLabels: { live: 'Live since' } },
    nalua: { industry: 'Skincare', tagline: 'Purchase offers and quantity tiers, cash-on-delivery flow.', description: 'Offers that only looked like discounts were the risk here. Purchase offers and quantity tiers are wired to real automatic discounts, and the cash-on-delivery flow through Releasit stays in sync offer by offer: 19 of 19 offers matched.', factLabels: { offers: 'Offers in sync with cash on delivery' } },
    sebum: { industry: 'Skincare', tagline: 'V2 rebuild with an extensible review wall.', description: 'The V2 rebuild came with an extensible review wall and React islands on the product page. The repo and the live theme are byte-identical (100% parity), so every change ships from git and nothing lives only in the editor.' },
    'valdo-cafe': { industry: 'Coffee', tagline: 'Transferred from a staging store to the real one and promoted.', description: 'Built on a staging store, transferred to the real one and promoted the next day (July 9 to 10, 2026). Small theme, clean templates, ready for the client to run without me.', factLabels: { transfer: 'From transfer to live' } },
    'factores-2x2': { industry: 'Supplements', tagline: 'Framer to Liquid, web-quality pass to 95+.', description: 'Framer to Liquid first, then a web-quality pass across the whole route matrix. Today the home page scores 100 for accessibility and 100 for SEO on Lighthouse mobile (September 2026 lab run).', factLabels: { quality: 'Accessibility · SEO (Lighthouse mobile, Sep 2026)' } },
    pixxiesx: { industry: 'Fashion', tagline: 'Product quiz, metaobject-driven PDP, same-day delivery.', description: 'A sunglasses brand that needed the product page to answer questions before support did. A product quiz, a PDP driven by six metaobject types (benefits, traits, material, FAQ, pain points, measures) and same-day delivery messaging.' },
    'luxe-shine': { industry: 'Beauty', tagline: 'Scroll-driven video hero, tracking retrofit.', description: 'The existing theme stayed; what changed is what it reports. A scroll-driven video hero, a full PDP image rollout and a tracking retrofit so this store feeds the same dashboard as the new builds.' },
    atmosfera: { industry: 'Computers', tagline: 'Catalog sync from supplier lists, dual pricing.', description: 'A computer retailer whose catalog changes with supplier price lists. The catalog syncs from those lists every 12 hours, prices show with and without VAT, specs live in metafields and variant stock is mirrored.', factLabels: { pricing: 'Prices shown', sync: 'Catalog refreshed every' } },
    'saint-theory': { industry: 'Streetwear', tagline: 'Custom Liquid theme, still live.', description: 'Streetwear brand with a custom Liquid theme built in 2023 that is still the live theme today.' },
    peluna: { industry: 'Pet care', tagline: 'Redesign on the Digitdeck template with A/B testing.', description: 'Redesign on the Digitdeck template with an A/B testing setup from day one and metaobjects for product data; the client\'s Shrine theme keeps running in parallel until the switch.', factLabels: { ab: 'A/B testing' } },
    'en-amor-a-dos': { industry: 'Jewelry', tagline: '57 custom sections on React islands.', description: 'A jewelry brand with 57 custom sections built on React islands over a Dawn base, staged on a QA theme while the client\'s live store stays untouched.' },
    unik: { industry: 'Denim', tagline: 'Bilingual, dual-currency storefront with bulk catalog i18n.', description: 'A denim brand rebuilt as a bilingual, dual-currency storefront, with the catalog translated in bulk through the Admin GraphQL API. The build sits 389 files ahead of the client\'s live Dawn.', factLabels: { langs: 'Languages · currencies' } },
    'origen-vital': { industry: 'Supplements', tagline: 'Framer port, product quiz, 302 seeded reviews, promo landings.', description: 'A supplement brand ported from Framer with a product quiz, 302 seeded reviews with photos (80+ per product), a mega menu over five collections and promo landings synthesized from 192 ads.', factLabels: { reviews: 'Reviews with photos, live', ads: 'Ads turned into landing pages' } },
    'para-machos': { industry: 'Men\'s grooming', tagline: 'New Digitdeck theme in development.', description: 'A men\'s grooming brand getting a new Digitdeck theme on a DEV copy while the client\'s live theme stays immutable until launch.' },
    tierramont: { industry: 'Outdoor', tagline: 'New theme in development for the real store.', description: 'An outdoor apparel brand with a new theme in development for the real store, tracked issue by issue (81 so far) on a shared board the client can read.' },
    'alma-de-aviador': { industry: 'Apparel', tagline: 'WooCommerce to Shopify migration with a Framer port.', description: 'An aviation-inspired apparel brand migrated from WooCommerce to Shopify, with the Framer design componentized into 35 sections on the V2 theme.', factLabels: { migration: 'Platform migration' } },
    joystaz: { industry: 'Denim', tagline: 'Tailwind Liquid theme with a custom reviews backend.', description: 'Denim brand on a Tailwind Liquid theme with a custom reviews backend (Express + Prisma) built in 2025.' },
    'new-urban': { industry: 'Fashion', tagline: 'Early Digitdeck storefront.', description: 'Early Digitdeck storefront for a fashion brand, built in 2023.' },
    gummind: { industry: 'Wellness', tagline: 'Skeleton-theme storefront.', description: 'Wellness storefront on a skeleton theme, built in 2025.' },
    rimo: { industry: 'Retail', tagline: 'Early Digitdeck storefront.', description: 'Early Digitdeck storefront, built in 2023.' },
  },
  products: {
    'digitdeck-apps': { tagline: 'One install, five modules', description: 'Multi-tenant Shopify app on the official Remix stack: back in stock, bundles, referrals, reviews, A/B testing. Two Shopify Functions, a consent-gated Web Pixel, and a Theme App Extension.' },
    'digitdeck-platform': { tagline: 'The agency\'s operating system', description: 'Modular monolith with tenant isolation, a module registry, RBAC, and a BYO-AI gateway. Live at app.digitdeck.co.' },
    'audit-dashboard': { tagline: 'Audits clients can open offline', description: 'Renders a self-contained HTML dashboard from audit data, a brand theme, and screenshots. No CDN, no external requests.' },
    'feedback-portal': { tagline: 'Client feedback as GitHub issues', description: 'Private multi-client portal where every report becomes a standardized issue on the right board.' },
    track: { tagline: 'First-party events by convention', description: 'A data-dd-* contract every section follows, feeding the Optimize dashboard and the A/B testing module.' },
  },
  projects: {
    kotodama: { tagline: 'Learn Japanese as a JRPG', description: 'Zero to JLPT N1 with spaced repetition, listening, kanji, and reading quests.' },
    'autofill-plugin': { tagline: 'Browser autofill helper', description: 'Fills repetitive forms from saved profiles.' },
    pagui: { tagline: 'OCR onboarding', description: 'Identity registration with OCR for bank clients.' },
    scorrea: { tagline: 'Developer portfolio', description: 'Astro site for a senior software developer.' },
    'dr-hugo': { tagline: 'Cosmetic dentist site', description: 'Services and booking presence for a dental practice.' },
    maxfolio: { tagline: 'This site', description: 'Four design languages, one content model, three languages.' },
  },
  footer: { tagline: 'Shopify engineering, measured.', services: ['Shopify storefronts', 'Shopify apps', 'CRO & A/B testing', 'Store migrations', 'Performance'], servicesTitle: 'What I do', quickLinks: 'Quick links', rights: 'All rights reserved.', stamp: 'Rebuilt September 2026 · React 19 + Vite · Lighthouse 100/100/100/100 on desktop (local lab run)', backToTop: 'Back to top' },
  location: 'Medellín, Colombia',
}
