import type { PortfolioContent } from './types'

export const en: PortfolioContent = {
  meta: {
    title: 'Maximiliano Bustamante | CTO & Shopify Tech Lead',
    description:
      'CTO & Shopify Tech Lead at Digitdeck. 18+ Shopify storefronts, a production app suite, and the delivery system behind them. Open for Shopify CRO consulting.',
  },
  hero: {
    eyebrow: 'CTO & Shopify Tech Lead · Digitdeck',
    positioning: 'I build Shopify stores that sell — and the system that ships them.',
    lead: '18+ storefronts, a multi-tenant app suite, and a QA pipeline that catches what a launch would have broken. You get Shopify engineering that is measured, not guessed.',
    availability: 'Open for Shopify CRO consulting and quotes',
    ctaContact: 'Get in touch',
    ctaCv: 'Download CV',
  },
  stats: {
    storefronts: 'Shopify storefronts',
    modules: 'App modules in production',
    functions: 'Shopify Functions (WASM)',
    standards: 'Engineering standards',
    tests: 'Automated tests',
    brands: 'Brand token systems',
  },
  sections: {
    experience: { eyebrow: 'Experience', title: 'Where the work', titleAccent: 'happened', achievements: 'What shipped', technologies: 'Stack', visit: 'Visit website' },
    shopify: {
      eyebrow: 'Shopify work',
      title: 'Storefronts, apps,',
      titleAccent: 'and the platform behind them',
      lead: '18+ storefronts: bundles priced by Shopify Functions, product quizzes, review walls, dual-currency catalogs, migrations from Framer and WooCommerce. Open a store for its case; the live ones take you to the real checkout.',
      tabStores: 'Storefronts',
      tabProducts: 'Apps & platform',
      legacyLabel: 'Earlier work',
      visit: 'Visit store',
      showAll: 'Show all {n} stores',
      showLess: 'Show fewer',
    },
    gallery: {
      eyebrow: 'Gallery',
      title: 'Built to sell,',
      titleAccent: 'on every screen',
      lead: 'Every store here gets the same standard: a home page that earns the click and a product page that closes it, on the phone your customers actually use. Hover to flip to the product page; open a store and you see the four captures, the build and what it runs on.',
      filterAll: 'All',
      filterLive: 'Live',
      filterDev: 'In development',
      viewLabel: 'View',
      viewCarousel: 'Carousel',
      viewDevices: 'Laptop + phone',
      viewPhones: 'Phones only',
      open: 'Open gallery',
      close: 'Close',
      home: 'Home',
      pdp: 'Product page',
      desktop: 'Desktop',
      mobile: 'Mobile',
    },
    years: { eyebrow: 'Year by year', title: 'Five years,', titleAccent: 'one direction', lead: 'From React components in 2022 to a fleet of Shopify stores and the platform behind them. Every card is derived from the same records as the rest of the site.', roles: 'Roles', shipped: 'Storefronts', products: 'Products', side: 'On my own time', more: '+{n} more' },
    projects: { eyebrow: 'Projects', title: 'Things I build', titleAccent: 'on my own time', view: 'View project' },
    skills: {
      eyebrow: 'Skills',
      title: 'What I',
      titleAccent: 'work with',
      groups: { shopify: 'Shopify', frontend: 'Frontend', backend: 'Backend', quality: 'Testing & CI/CD', cro: 'CRO & analytics', ai: 'AI engineering' },
    },
    contact: {
      eyebrow: 'Contact',
      title: 'Your store gets traffic.',
      titleAccent: 'Let\'s turn more of it into orders.',
      lead: 'I find where your Shopify store leaks — speed, offers, checkout friction — and fix it with A/B tests you can read, not guesses. Diagnosis first, then the fix.',
      status: 'Available for consulting',
      note: 'US and LATAM brands. You hear back within one business day.',
      cta: 'Send a message',
      email: 'Email',
      phone: 'Phone',
      location: 'Location',
    },
    explore: { eyebrow: 'Explore', title: 'Same portfolio, four designs', lead: 'Pick the aesthetic you prefer. The content is identical.', viewing: 'Currently viewing' },
    caseStudy: { facts: 'By the numbers', results: 'Measured results', stack: 'Stack', visit: 'Visit store', prev: 'Previous', next: 'Next', timeline: 'Build window', commits: 'commits', sections: 'custom sections', open: 'Case study', metrics: 'Lighthouse · mobile', perf: 'Performance', a11y: 'Accessibility', bp: 'Best practices', seo: 'SEO', lcp: 'LCP', measured: 'Lab run on the home page, {date}, median of {runs} Lighthouse runs (mobile, simulated throttling).', story: 'What moved', sampleBadge: 'Sample data', sampleNote: 'Illustrative shapes until the measured numbers replace them. Indexed: before = 100.', measuredFrom: '{source} · {period} · indexed, before = 100', before: 'Before', after: 'After', metric: { cr: 'Conversion rate', aov: 'Average order value', revenue: 'Revenue', lcp: 'Mobile load (LCP)', checkout: 'Checkout drop-off' } },
  },
  badges: { live: 'Live', dev: 'In development', current: 'Current', completed: 'Completed', roles: { built: 'Built', maintained: 'Maintained', migrated: 'Migrated' } },
  experience: {
    'digitdeck-cto': {
      title: 'CTO & Shopify Technical Lead',
      summary: 'I set the engineering standard for a Shopify agency and build the delivery system itself: component libraries, automated QA, CI/CD, and AI-agent tooling.',
      highlights: [
        'Standardized a hybrid Liquid + React islands architecture with a 33-component shared library and design tokens spanning 14 brands.',
        'Built a multi-tenant Shopify app suite on the official Remix stack — A/B testing, reviews, bundles, referrals, back in stock — plus a subscription billing engine with 800+ automated tests.',
        'Shipped Shopify Functions compiled to WASM, a consent-gated Web Pixel, and Theme App Extensions.',
        'Led WooCommerce-to-Shopify and staging-to-production migrations; re-platformed an 11,000-line Liquid theme into React islands with verified visual parity.',
        'Built GitHub Actions pipelines and a Playwright harness that tests whole storefronts behaviorally, with 40+ Shopify-specific checks.',
        'Researched 59 DTC brands into a 70-pattern conversion library and wrote the agency\'s Bayesian A/B testing methodology.',
      ],
      metricLabels: { storefronts: 'Storefronts', modules: 'App modules', tests: 'Automated tests' },
    },
    ellamau: {
      title: 'Lead Shopify Developer',
      summary: 'Full Shopify storefront build for a US fashion brand, from planning to deployment.',
      highlights: ['Modular Liquid sections with reusable blocks and configurable schemas.', '15+ responsive templates, mobile first.', 'Lighthouse above 90 after optimization.'],
      metricLabels: { templates: 'Templates', lighthouse: 'Lighthouse' },
    },
    abidata: {
      title: 'Full Stack Developer',
      summary: 'Internal platform to create, customize, and send enterprise newsletters.',
      highlights: ['React email editor that cut campaign creation time by about 40%.', '10,000+ contact records and hundreds of active campaigns.', 'Owned the REST APIs from design to deployment.'],
      metricLabels: { contacts: 'Contacts', campaignTime: 'Campaign time', users: 'Internal users' },
    },
    rh: {
      title: 'Frontend Developer',
      summary: 'Enterprise CMS migration from Adobe AEM to Contentful for a large US retailer.',
      highlights: ['25+ reusable components that made the migration possible.', 'Accessibility work took Lighthouse from ~70 to 95+.', 'Cut content-authoring costs by roughly $45,000 a year.'],
      metricLabels: { components: 'Components', lighthouse: 'Lighthouse', savings: 'Savings' },
    },
    'digitdeck-fe': {
      title: 'Frontend Developer (Shopify)',
      summary: 'Built and optimized Shopify storefronts with custom Liquid themes.',
      highlights: ['Custom sections, blocks, and snippets for 4+ storefronts.', 'UX and checkout work lifted conversion 10–20%.', 'Pages loaded 30–40% faster; organic traffic up 20%+.'],
      metricLabels: { conversion: 'Conversion', loadTime: 'Load time', organic: 'Organic traffic' },
    },
    orthofix: {
      title: 'Salesforce Developer',
      summary: 'Internal healthcare applications for patient and operations workflows.',
      highlights: ['Lightning Web Components used by 50+ internal users.', 'Workflows over thousands of patient and device records.', 'About 20% less manual data entry.'],
      metricLabels: { users: 'Users', dataEntry: 'Manual entry' },
    },
    ibox: {
      title: 'Frontend React Developer',
      summary: 'Company website for smart-locker solutions in US and LATAM markets.',
      highlights: ['20+ reusable React components and 10+ responsive pages.', 'Lighthouse 90+ and ~35% faster loads.'],
      metricLabels: { components: 'Components', pages: 'Pages', lighthouse: 'Lighthouse' },
    },
  },
  stores: {
    'the-gummy-box': { industry: 'Functional gummies', tagline: 'Bundle builder wired to our Bundles module, subscriptions, first-party tracking.', description: 'The kit offer had to be simple for the shopper and impossible to game: the Bundles module prices the kit through a Shopify Function at checkout, so the 10% to 20% ladder applies by itself and there is no coupon to find. Subscriptions run through Treli and every surface reports first-party events, so the brand sees what each block does.', factLabels: { ladder: 'Bundle discount, automatic at checkout' } },
    'nos-cafe': { industry: 'Specialty coffee', tagline: 'Framer design ported 1:1 to Liquid; box builder with tiered discounts.', description: 'A finished Framer design that could not lose a pixel on its way to Shopify. I ported it 1:1 to Liquid and built the box builder the roaster needed: up to five bags per box, grind and size chosen per bag, and a discount that climbs from 10% to 20% as the box fills.', factLabels: { ladder: 'Box discount, climbs with every bag' } },
    millennio: { industry: 'Perfumery', tagline: 'Framer port on React islands, 260+ tracked elements.', description: 'The perfumery wanted its Framer design live on Shopify and wanted to know what shoppers actually touch. The port runs as React islands over a Liquid base, and every card, rail and CTA is instrumented: 260+ tracked elements report to the Optimize dashboard.', factLabels: { tracked: 'Shopper touchpoints measured' } },
    mindfuel: { industry: 'Nootropics', tagline: 'Full React V2 port, promoted to live.', description: 'The brand was rebuilt as a React V2 port on the Digitdeck template and promoted to live on August 20, 2026. Home, product page and the quiz share one component library, so a change ships once and lands everywhere.', factLabels: { live: 'Live since' } },
    nalua: { industry: 'Skincare', tagline: 'Purchase offers and quantity tiers, cash-on-delivery flow.', description: 'Offers that only looked like discounts were the risk here. Purchase offers and quantity tiers are wired to real automatic discounts, and the cash-on-delivery flow through Releasit stays in sync offer by offer: 19 of 19 offers matched.', factLabels: { offers: 'Offers in sync with cash on delivery' } },
    sebum: { industry: 'Skincare', tagline: 'V2 rebuild with an extensible review wall.', description: 'The V2 rebuild came with an extensible review wall and React islands on the product page. The repo and the live theme are byte-identical (100% parity), so every change ships from git and nothing lives only in the editor.' },
    'valdo-cafe': { industry: 'Coffee', tagline: 'Transferred from a staging store to the real one and promoted.', description: 'Built on a staging store, transferred to the real one and promoted the next day (July 9 to 10, 2026). Small theme, clean templates, ready for the client to run without me.', factLabels: { transfer: 'From transfer to live' } },
    'factores-2x2': { industry: 'Supplements', tagline: 'Framer to Liquid, web-quality pass to 95+.', description: 'Framer to Liquid first, then a web-quality pass across the whole route matrix. Today the home page scores 100 for accessibility and 100 for SEO on Lighthouse mobile (September 2026 lab run).', factLabels: { quality: 'Accessibility · SEO (Lighthouse mobile, Sep 2026)' } },
    pixxiesx: { industry: 'Fashion', tagline: 'Product quiz, metaobject-driven PDP, same-day delivery.', description: 'A sunglasses brand that needed the product page to answer questions before support did. A product quiz, a PDP driven by six metaobject types (benefits, traits, material, FAQ, pain points, measures) and same-day delivery messaging.' },
    'luxe-shine': { industry: 'Beauty', tagline: 'Scroll-driven video hero, tracking retrofit.', description: 'The existing theme stayed; what changed is what it reports. A scroll-driven video hero, a full PDP image rollout and a tracking retrofit so this store feeds the same dashboard as the new builds.' },
    atmosfera: { industry: 'Computers', tagline: 'Catalog sync from supplier lists, dual pricing.', description: 'A computer retailer whose catalog changes with supplier price lists. The catalog syncs from those lists every 12 hours, prices show with and without VAT, specs live in metafields and variant stock is mirrored.', factLabels: { pricing: 'Prices shown', sync: 'Catalog refreshed every' } },
    'saint-theory': { industry: 'Streetwear', tagline: 'Custom Liquid theme, still live.', description: 'Streetwear brand with a custom Liquid theme built in 2023 that is still the live theme today.' },
    peluna: { industry: 'Pet care', tagline: 'Redesign on the Digitdeck template with A/B testing.', description: 'Redesign on the Digitdeck template with an A/B testing setup from day one and metaobjects for product data; the client\'s Shrine theme keeps running in parallel until the switch.', factLabels: { ab: 'A/B testing' } },
    'en-amor-a-dos': { industry: 'Jewelry', tagline: '57 custom sections on React islands.', description: 'A jewelry brand with 57 custom sections built on React islands over a Dawn base, staged on a QA theme while the client\'s live store stays untouched.' },
    unik: { industry: 'Denim', tagline: 'Bilingual, dual-currency storefront with bulk catalog i18n.', description: 'A denim brand rebuilt as a bilingual, dual-currency storefront, with the catalog translated in bulk through the Admin GraphQL API. The build sits 389 files ahead of the client\'s live Dawn.', factLabels: { langs: 'Languages · currencies' } },
    'origen-vital': { industry: 'Supplements', tagline: 'Framer port, product quiz, 302 seeded reviews, promo landings.', description: 'A supplement brand ported from Framer with a product quiz, 302 seeded reviews with photos (80+ per product), a mega menu over five collections and promo landings synthesized from 192 ads.', factLabels: { reviews: 'Reviews with photos, live', ads: 'Ads turned into landing pages' } },
    'para-machos': { industry: 'Men\'s grooming', tagline: 'New Digitdeck theme in development.', description: 'A men\'s grooming brand getting a new Digitdeck theme on a DEV copy while the client\'s live theme stays immutable until launch.' },
    tierramont: { industry: 'Outdoor', tagline: 'New theme in development for the real store.', description: 'An outdoor apparel brand with a new theme in development for the real store, tracked issue by issue (81 so far) on a shared board the client can read.' },
    'alma-de-aviador': { industry: 'Apparel', tagline: 'WooCommerce to Shopify migration with a Framer port.', description: 'An aviation-inspired apparel brand migrated from WooCommerce to Shopify, with the Framer design componentized into 35 sections on the V2 theme.', factLabels: { migration: 'Platform migration' } },
    joystaz: { industry: 'Denim', tagline: 'Tailwind Liquid theme with a custom reviews backend.', description: 'Denim brand on a Tailwind Liquid theme with a custom reviews backend (Express + Prisma) built in 2025.' },
    'new-urban': { industry: 'Fashion', tagline: 'Early Digitdeck storefront.', description: 'Early Digitdeck storefront for a fashion brand, built in 2023.' },
    gummind: { industry: 'Wellness', tagline: 'Skeleton-theme storefront.', description: 'Wellness storefront on a skeleton theme, built in 2025.' },
    rimo: { industry: 'Retail', tagline: 'Early Digitdeck storefront.', description: 'Early Digitdeck storefront, built in 2023.' },
  },
  products: {
    'digitdeck-apps': { tagline: 'One install, five modules', description: 'Multi-tenant Shopify app on the official Remix stack: back in stock, bundles, referrals, reviews, A/B testing. Two Shopify Functions, a consent-gated Web Pixel, and a Theme App Extension.' },
    'digitdeck-platform': { tagline: 'The agency\'s operating system', description: 'Modular monolith with tenant isolation, a module registry, RBAC, and a BYO-AI gateway. Live at app.digitdeck.co.' },
    'audit-dashboard': { tagline: 'Audits clients can open offline', description: 'Renders a self-contained HTML dashboard from audit data, a brand theme, and screenshots. No CDN, no external requests.' },
    'feedback-portal': { tagline: 'Client feedback as GitHub issues', description: 'Private multi-client portal where every report becomes a standardized issue on the right board.' },
    track: { tagline: 'First-party events by convention', description: 'A data-dd-* contract every section follows, feeding the Optimize dashboard and the A/B testing module.' },
  },
  projects: {
    kotodama: { tagline: 'Learn Japanese as a JRPG', description: 'Zero to JLPT N1 with spaced repetition, listening, kanji, and reading quests.' },
    'autofill-plugin': { tagline: 'Browser autofill helper', description: 'Fills repetitive forms from saved profiles.' },
    pagui: { tagline: 'OCR onboarding', description: 'Identity registration with OCR for bank clients.' },
    scorrea: { tagline: 'Developer portfolio', description: 'Astro site for a senior software developer.' },
    'dr-hugo': { tagline: 'Cosmetic dentist site', description: 'Services and booking presence for a dental practice.' },
    maxfolio: { tagline: 'This site', description: 'Four design languages, one content model, three languages.' },
  },
  footer: { tagline: 'Shopify engineering, measured.', services: ['Shopify storefronts', 'Shopify apps', 'CRO & A/B testing', 'Store migrations', 'Performance'], servicesTitle: 'What I do', quickLinks: 'Quick links', rights: 'All rights reserved.' },
  location: 'Medellín, Colombia',
}
