import type { PortfolioContent } from './types'

export const en: PortfolioContent = {
  meta: {
    title: 'Maximiliano Bustamante | CTO & Shopify Tech Lead',
    description:
      'CTO & Shopify Tech Lead at Digitdeck. 18+ Shopify storefronts, a production app suite, and the delivery system behind them. Open for Shopify CRO consulting.',
  },
  hero: {
    eyebrow: 'CTO & Shopify Tech Lead · Digitdeck',
    positioning: 'I build Shopify stores that sell — and the system that ships them.',
    lead: '18+ storefronts, a multi-tenant app suite, and a QA pipeline that catches what a launch would have broken. You get Shopify engineering that is measured, not guessed.',
    availability: 'Open for Shopify CRO consulting and quotes',
    ctaContact: 'Get in touch',
    ctaCv: 'Download CV',
  },
  stats: {
    storefronts: 'Shopify storefronts',
    modules: 'App modules in production',
    functions: 'Shopify Functions (WASM)',
    standards: 'Engineering standards',
    tests: 'Automated tests',
    brands: 'Brand token systems',
  },
  sections: {
    experience: { eyebrow: 'Experience', title: 'Where the work', titleAccent: 'happened', achievements: 'What shipped', technologies: 'Stack', visit: 'Visit website' },
    shopify: {
      eyebrow: 'Shopify work',
      title: 'Storefronts, apps,',
      titleAccent: 'and the platform behind them',
      lead: 'Every store below runs code I wrote or reviewed. Live ones link to the real storefront; the rest are builds still moving through the client\'s pipeline.',
      tabStores: 'Storefronts',
      tabProducts: 'Apps & platform',
      legacyLabel: 'Earlier work',
      visit: 'Visit store',
    },
    gallery: {
      eyebrow: 'Gallery',
      title: 'Same frame,',
      titleAccent: 'every store',
      lead: 'Home and product page, desktop and mobile — captured the same way for every project so you can compare them honestly.',
      filterAll: 'All',
      filterLive: 'Live',
      filterDev: 'In development',
      open: 'Open gallery',
      close: 'Close',
      home: 'Home',
      pdp: 'Product page',
      desktop: 'Desktop',
      mobile: 'Mobile',
    },
    projects: { eyebrow: 'Projects', title: 'Things I build', titleAccent: 'on my own time', view: 'View project' },
    skills: {
      eyebrow: 'Skills',
      title: 'What I',
      titleAccent: 'work with',
      groups: { shopify: 'Shopify', frontend: 'Frontend', backend: 'Backend', quality: 'Testing & CI/CD', cro: 'CRO & analytics', ai: 'AI engineering' },
    },
    contact: {
      eyebrow: 'Contact',
      title: 'Your store gets traffic.',
      titleAccent: 'Let\'s turn more of it into orders.',
      lead: 'I find where your Shopify store leaks — speed, offers, checkout friction — and fix it with A/B tests you can read, not guesses. Diagnosis first, then the fix.',
      status: 'Available for consulting',
      note: 'US and LATAM brands. You hear back within one business day.',
      cta: 'Send a message',
      email: 'Email',
      phone: 'Phone',
      location: 'Location',
    },
    explore: { eyebrow: 'Explore', title: 'Same portfolio, four designs', lead: 'Pick the aesthetic you prefer. The content is identical.', viewing: 'Currently viewing' },
  },
  badges: { live: 'Live', dev: 'In development', current: 'Current', completed: 'Completed', roles: { built: 'Built', maintained: 'Maintained', migrated: 'Migrated' } },
  experience: {
    'digitdeck-cto': {
      title: 'CTO & Shopify Technical Lead',
      summary: 'I set the engineering standard for a Shopify agency and build the delivery system itself: component libraries, automated QA, CI/CD, and AI-agent tooling.',
      highlights: [
        'Standardized a hybrid Liquid + React islands architecture with a 33-component shared library and design tokens spanning 14 brands.',
        'Built a multi-tenant Shopify app suite on the official Remix stack — A/B testing, reviews, bundles, referrals, back in stock — plus a subscription billing engine with 800+ automated tests.',
        'Shipped Shopify Functions compiled to WASM, a consent-gated Web Pixel, and Theme App Extensions.',
        'Led WooCommerce-to-Shopify and staging-to-production migrations; re-platformed an 11,000-line Liquid theme into React islands with verified visual parity.',
        'Built GitHub Actions pipelines and a Playwright harness that tests whole storefronts behaviorally, with 40+ Shopify-specific checks.',
        'Researched 59 DTC brands into a 70-pattern conversion library and wrote the agency\'s Bayesian A/B testing methodology.',
      ],
      metricLabels: { storefronts: 'Storefronts', modules: 'App modules', tests: 'Automated tests' },
    },
    ellamau: {
      title: 'Lead Shopify Developer',
      summary: 'Full Shopify storefront build for a US fashion brand, from planning to deployment.',
      highlights: ['Modular Liquid sections with reusable blocks and configurable schemas.', '15+ responsive templates, mobile first.', 'Lighthouse above 90 after optimization.'],
      metricLabels: { templates: 'Templates', lighthouse: 'Lighthouse' },
    },
    abidata: {
      title: 'Full Stack Developer',
      summary: 'Internal platform to create, customize, and send enterprise newsletters.',
      highlights: ['React email editor that cut campaign creation time by about 40%.', '10,000+ contact records and hundreds of active campaigns.', 'Owned the REST APIs from design to deployment.'],
      metricLabels: { contacts: 'Contacts', campaignTime: 'Campaign time', users: 'Internal users' },
    },
    rh: {
      title: 'Frontend Developer',
      summary: 'Enterprise CMS migration from Adobe AEM to Contentful for a large US retailer.',
      highlights: ['25+ reusable components that made the migration possible.', 'Accessibility work took Lighthouse from ~70 to 95+.', 'Cut content-authoring costs by roughly $45,000 a year.'],
      metricLabels: { components: 'Components', lighthouse: 'Lighthouse', savings: 'Savings' },
    },
    'digitdeck-fe': {
      title: 'Frontend Developer (Shopify)',
      summary: 'Built and optimized Shopify storefronts with custom Liquid themes.',
      highlights: ['Custom sections, blocks, and snippets for 4+ storefronts.', 'UX and checkout work lifted conversion 10–20%.', 'Pages loaded 30–40% faster; organic traffic up 20%+.'],
      metricLabels: { conversion: 'Conversion', loadTime: 'Load time', organic: 'Organic traffic' },
    },
    orthofix: {
      title: 'Salesforce Developer',
      summary: 'Internal healthcare applications for patient and operations workflows.',
      highlights: ['Lightning Web Components used by 50+ internal users.', 'Workflows over thousands of patient and device records.', 'About 20% less manual data entry.'],
      metricLabels: { users: 'Users', dataEntry: 'Manual entry' },
    },
    ibox: {
      title: 'Frontend React Developer',
      summary: 'Company website for smart-locker solutions in US and LATAM markets.',
      highlights: ['20+ reusable React components and 10+ responsive pages.', 'Lighthouse 90+ and ~35% faster loads.'],
      metricLabels: { components: 'Components', pages: 'Pages', lighthouse: 'Lighthouse' },
    },
  },
  stores: {
    'the-gummy-box': { industry: 'Functional gummies', tagline: 'Bundle builder wired to our Bundles module, subscriptions, first-party tracking.' },
    'nos-cafe': { industry: 'Specialty coffee', tagline: 'Framer design ported 1:1 to Liquid; box builder with tiered discounts.' },
    millennio: { industry: 'Perfumery', tagline: 'Framer port on React islands, 260+ tracked elements.' },
    mindfuel: { industry: 'Nootropics', tagline: 'Full React V2 port, promoted to live.' },
    nalua: { industry: 'Skincare', tagline: 'Purchase offers and quantity tiers, cash-on-delivery flow.' },
    sebum: { industry: 'Skincare', tagline: 'V2 rebuild with an extensible review wall.' },
    'valdo-cafe': { industry: 'Coffee', tagline: 'Transferred from a staging store to the real one and promoted.' },
    'factores-2x2': { industry: 'Supplements', tagline: 'Framer to Liquid, web-quality pass to 95+.' },
    pixxiesx: { industry: 'Fashion', tagline: 'Product quiz, metaobject-driven PDP, same-day delivery.' },
    'luxe-shine': { industry: 'Beauty', tagline: 'Scroll-driven video hero, tracking retrofit.' },
    atmosfera: { industry: 'Computers', tagline: 'Catalog sync from supplier lists, dual pricing.' },
    'saint-theory': { industry: 'Streetwear', tagline: 'Custom Liquid theme, still live.' },
    peluna: { industry: 'Pet care', tagline: 'Redesign on the Digitdeck template with A/B testing.' },
    'en-amor-a-dos': { industry: 'Jewelry', tagline: '57 custom sections on React islands.' },
    unik: { industry: 'Denim', tagline: 'Bilingual, dual-currency storefront with bulk catalog i18n.' },
    'origen-vital': { industry: 'Supplements', tagline: 'Framer port, product quiz, 302 seeded reviews, promo landings.' },
    'para-machos': { industry: 'Men\'s grooming', tagline: 'New Digitdeck theme in development.' },
    tierramont: { industry: 'Outdoor', tagline: 'New theme in development for the real store.' },
    'alma-de-aviador': { industry: 'Apparel', tagline: 'WooCommerce to Shopify migration with a Framer port.' },
    joystaz: { industry: 'Denim', tagline: 'Tailwind Liquid theme with a custom reviews backend.' },
    'new-urban': { industry: 'Fashion', tagline: 'Early Digitdeck storefront.' },
    gummind: { industry: 'Wellness', tagline: 'Skeleton-theme storefront.' },
    rimo: { industry: 'Retail', tagline: 'Early Digitdeck storefront.' },
  },
  products: {
    'digitdeck-apps': { tagline: 'One install, five modules', description: 'Multi-tenant Shopify app on the official Remix stack: back in stock, bundles, referrals, reviews, A/B testing. Two Shopify Functions, a consent-gated Web Pixel, and a Theme App Extension.' },
    'digitdeck-platform': { tagline: 'The agency\'s operating system', description: 'Modular monolith with tenant isolation, a module registry, RBAC, and a BYO-AI gateway. Live at app.digitdeck.co.' },
    'audit-dashboard': { tagline: 'Audits clients can open offline', description: 'Renders a self-contained HTML dashboard from audit data, a brand theme, and screenshots. No CDN, no external requests.' },
    'feedback-portal': { tagline: 'Client feedback as GitHub issues', description: 'Private multi-client portal where every report becomes a standardized issue on the right board.' },
    track: { tagline: 'First-party events by convention', description: 'A data-dd-* contract every section follows, feeding the Optimize dashboard and the A/B testing module.' },
  },
  projects: {
    kotodama: { tagline: 'Learn Japanese as a JRPG', description: 'Zero to JLPT N1 with spaced repetition, listening, kanji, and reading quests.' },
    peptidos: { tagline: 'Headless commerce, clinical design', description: 'Minimal, glass-and-grayscale storefront for a research-peptide brand.' },
    'will-you': { tagline: 'A small yes-or-no site', description: 'Weekend build.' },
    'fast-resoluciones': { tagline: 'PDF to Excel, automatically', description: 'Extracts users and IDs from resolution PDFs and fills spreadsheets.' },
    'autofill-plugin': { tagline: 'Browser autofill helper', description: 'Fills repetitive forms from saved profiles.' },
    pagui: { tagline: 'OCR onboarding', description: 'Identity registration with OCR for bank clients.' },
    scorrea: { tagline: 'Developer portfolio', description: 'Astro site for a senior software developer.' },
    'dr-hugo': { tagline: 'Cosmetic dentist site', description: 'Services and booking presence for a dental practice.' },
    maxfolio: { tagline: 'This site', description: 'Four design languages, one content model, three languages.' },
  },
  footer: { tagline: 'Shopify engineering, measured.', services: ['Shopify storefronts', 'Shopify apps', 'CRO & A/B testing', 'Store migrations', 'Performance'], servicesTitle: 'What I do', quickLinks: 'Quick links', rights: 'All rights reserved.' },
  location: 'Medellín, Colombia',
}
