import type { PortfolioContent } from './types'

export const es: PortfolioContent = {
  meta: {
    title: 'Maximiliano Bustamante | CTO & Shopify Tech Lead',
    description:
      'CTO & Shopify Tech Lead en Digitdeck. 18+ tiendas Shopify, una suite de apps en producción y el sistema que las entrega. Disponible para consultoría CRO en Shopify.',
  },
  hero: {
    eyebrow: 'CTO & Shopify Tech Lead · Digitdeck',
    positioning: 'Tu tienda Shopify tiene tráfico. Yo encuentro dónde deja de convertirse en pedidos.',
    lead: '18+ tiendas, una suite de apps multi-tenant y un arnés de QA que atrapa lo que un lanzamiento habría roto. Recibes ingeniería Shopify medida: qué se movió, por qué y qué sigue.',
    availability: 'Disponible para consultoría CRO en Shopify y cotizaciones',
    location: 'Desde Medellín, para marcas de EE. UU. y Latinoamérica',
    ctaContact: 'Escríbeme',
    ctaPrimary: 'Pide tu revisión gratis de 20 minutos',
    ctaSecondary: 'Ver el trabajo',
    ctaNote: 'Sin discurso de venta ni contrato. Solo dónde se fuga la tienda y qué arreglar primero.',
    ctaCv: 'Descargar CV',
  },
  stats: {
    storefronts: 'Tiendas Shopify',
    modules: 'Módulos de app en producción',
    functions: 'Shopify Functions (WASM)',
    standards: 'Estándares de ingeniería',
    tests: 'Pruebas automatizadas',
    brands: 'Sistemas de tokens de marca',
  },
  sections: {
    experience: { eyebrow: 'Experiencia', title: 'Dónde pasó', titleAccent: 'el trabajo', achievements: 'Qué se entregó', technologies: 'Stack', visit: 'Visitar sitio' },
    shopify: {
      eyebrow: 'Trabajo en Shopify',
      title: 'Tiendas, apps',
      titleAccent: 'y la plataforma detrás',
      lead: 'Abre cualquier tienda de abajo y estás a un clic de su checkout real, no de una simulación. 18+ tiendas: combos con precio calculado por Shopify Functions, quizzes de producto, muros de reseñas, catálogos en dos monedas, migraciones desde Framer y WooCommerce.',
      tabStores: 'Tiendas',
      tabProducts: 'Apps y plataforma',
      legacyLabel: 'Trabajo anterior',
      visit: 'Visitar tienda',
      showAll: 'Ver las {n} tiendas',
      showLess: 'Ver menos',
      filterAll: 'Todas',
      filters: { bundles: 'Bundles', quiz: 'Quiz', subscriptions: 'Suscripciones', reviews: 'Reseñas', migration: 'Migraciones', islands: 'Islas React', tracking: 'Tracking', i18n: 'Multimoneda' },
    },
    gallery: {
      eyebrow: 'Galería',
      title: 'Hechas para vender,',
      titleAccent: 'en cualquier pantalla',
      lead: 'Cada tienda aquí recibe el mismo estándar: una home que gana el clic y una página de producto que cierra la venta, en el celular que de verdad usan tus clientes. Pasa el cursor para ver la página de producto; abre una tienda y ves las cuatro tomas, la construcción y sobre qué corre.',
      filterAll: 'Todas',
      filterLive: 'En vivo',
      filterDev: 'En construcción',
      viewLabel: 'Vista',
      viewCarousel: 'Carrusel',
      viewDevices: 'Laptop + móvil',
      viewPhones: 'Solo móviles',
      open: 'Abrir galería',
      close: 'Cerrar',
      home: 'Home',
      pdp: 'Página de producto',
      desktop: 'Escritorio',
      mobile: 'Móvil',
    },
    process: {
      eyebrow: 'Cómo se entrega',
      title: 'Cinco pasos,',
      titleAccent: 'sin sorpresas',
      problemLabel: 'El cuello de botella.',
      problem: 'Velocidad, ofertas o fricción en el checkout: casi toda tienda pierde ingresos en uno de esos tres puntos, y casi todo equipo adivina cuál.',
      fixLabel: 'La solución.',
      fix: 'Cinco puntos de control, siempre en el mismo orden, para que sepas qué sigue y qué recibes en cada uno.',
      stepOf: 'Paso {n} de {total}',
      deliverableLabel: 'Recibes',
      steps: [
        { title: 'Diagnóstico', body: 'Tu tienda, tus números, tus cuellos de botella. Leo los datos antes de tocar una línea.', deliverable: 'Un diagnóstico escrito: dónde se fuga la tienda y qué arreglar primero.' },
        { title: 'Mapa de patrones', body: 'Cada página tiene plan: qué secciones, qué ofertas, qué prueba, en qué orden.', deliverable: 'Un plan página por página que puedes leer antes de que se escriba una línea.' },
        { title: 'Construcción', body: 'Liquid + islas React sobre la plantilla Digitdeck, medido desde el primer commit.', deliverable: 'Un tema en git, reportando eventos propios desde el primer día.' },
        { title: 'QA', body: 'Un arnés de Playwright recorre la tienda completa por comportamiento antes de salir al aire.', deliverable: 'Una corrida de pruebas de comportamiento sobre toda la tienda, con su reporte.' },
        { title: 'Entrega', body: 'La tienda queda en tus manos: cada ajuste vive en el editor y cada decisión en la documentación.', deliverable: 'El editor, la documentación y los números. Nada depende de mí.' },
      ],
    },
    faq: {
      eyebrow: 'Antes de escribir',
      title: 'Preguntas que recibo',
      titleAccent: 'antes de la primera llamada',
      items: [
        { q: '¿Necesito Shopify Plus?', a: 'No. La mayoría de estas tiendas corre en Shopify estándar. Los combos con precio por Shopify Functions, la suite de apps y el tracking funcionan en ambos planes.' },
        { q: '¿Y si mi tienda ya convierte bien?', a: 'Entonces la revisión lo dice, con los números, y paramos ahí. Solo propongo trabajo donde hay una brecha medible.' },
        { q: '¿Qué recibo al final, en concreto?', a: 'Un tema en git, tracking propio desde el primer día, una corrida de QA de comportamiento antes de salir al aire, y el editor con la documentación en la entrega. Nada depende de mí para seguir andando.' },
        { q: '¿Puedes trabajar con mi equipo o mi agencia?', a: 'Sí. Cada tienda de aquí salió con el cliente manteniendo el editor y el contenido. Yo tomo la ingeniería, la puerta de QA y la medición.' },
        { q: '¿Cuánto tarda una construcción?', a: 'Depende del alcance. El diagnóstico termina con una ventana por escrito, y sigues el avance issue por issue en un tablero compartido.' },
      ],
    },
    testimonials: { eyebrow: 'En sus palabras', title: 'Lo que dicen', titleAccent: 'los clientes' },
    now: { label: 'Ahora', live: '{n} tiendas en vivo', dev: '{n} en construcción', band: 'Tiendas entregadas', local: 'Medellín · {time} hora local' },
    statBand: { label: 'El trabajo, en números', asOf: 'Septiembre de 2026' },
    years: { eyebrow: 'Año por año', title: 'Cinco años,', titleAccent: 'una sola dirección', lead: 'De componentes React en 2022 a una flota de tiendas Shopify y la plataforma detrás. Cada línea sale de los mismos registros que el resto del sitio.', roles: 'Roles', shipped: 'Tiendas', products: 'Productos', side: 'En mi tiempo', more: '+{n} más', count: '{n} tiendas' },
    projects: { eyebrow: 'Proyectos', title: 'Lo que construyo', titleAccent: 'en mi tiempo', view: 'Ver proyecto' },
    skills: {
      eyebrow: 'Habilidades',
      title: 'Con qué',
      titleAccent: 'trabajo',
      groups: { shopify: 'Shopify', frontend: 'Frontend', backend: 'Backend', quality: 'Pruebas y CI/CD', cro: 'CRO y analítica', ai: 'Ingeniería con IA' },
      narrative: {
        shopify: 'Las tiendas y las apps salen con {skills}.',
        frontend: 'El front corre sobre {skills}.',
        backend: 'Detrás, {skills}.',
        quality: 'Nada sale al aire sin {skills}.',
        cro: 'Los números salen de {skills}.',
        ai: 'El sistema de entrega se construye con {skills}.',
      },
    },
    contact: {
      eyebrow: 'Contacto',
      title: 'Tu tienda ya recibe tráfico.',
      titleAccent: 'Convirtamos más de él en pedidos.',
      lead: 'Mándame tu tienda. En 20 minutos te muestro dónde se fuga —velocidad, ofertas, fricción en el checkout— y qué arreglar primero.',
      promise: 'Gratis y sin discurso de venta. Sales sabiendo qué arreglar primero, trabajemos juntos o no.',
      status: 'Disponible para consultoría',
      note: 'Marcas de EE. UU. y Latinoamérica. Recibes respuesta en un día hábil.',
      cta: 'Pedir la revisión gratis de 20 minutos',
      ctaSecondary: 'O escríbeme un correo',
      nextLabel: 'Qué pasa después',
      next: ['Manda la URL de tu tienda por el formulario o por correo.', 'Recibes respuesta en un día hábil.', 'Una llamada de 20 minutos: dónde se fuga la tienda y qué arreglar primero.', 'Si trabajamos juntos, primero el diagnóstico y después el arreglo.'],
      urlLabel: 'La URL de tu tienda',
      urlPlaceholder: 'tutienda.com',
      email: 'Correo',
      phone: 'Teléfono',
      location: 'Ubicación',
      elsewhere: 'También en',
    },
    explore: { eyebrow: 'Explorar', title: 'El mismo portafolio, cuatro diseños', lead: 'Elige la estética que prefieras. El contenido es idéntico.', viewing: 'Estás viendo' },
    caseStudy: { facts: 'En cifras', results: 'Resultados medidos', stack: 'Stack', visit: 'Visitar tienda', prev: 'Anterior', next: 'Siguiente', timeline: 'Ventana de construcción', commits: 'commits', sections: 'secciones propias', open: 'Caso', metrics: 'Lighthouse · móvil', perf: 'Rendimiento', a11y: 'Accesibilidad', bp: 'Buenas prácticas', seo: 'SEO', lcp: 'LCP', measured: 'Medición de laboratorio en la página de inicio, {date}, mediana de {runs} corridas de Lighthouse (móvil, red simulada).', story: 'Qué se movió', sampleBadge: 'Datos de muestra', sampleNote: 'Formas ilustrativas hasta que los números medidos las reemplacen. Indexado: antes = 100.', measuredFrom: '{source} · {period} · indexado, antes = 100', before: 'Antes', after: 'Después', metric: { cr: 'Tasa de conversión', aov: 'Ticket promedio', revenue: 'Ingresos', lcp: 'Carga en móvil (LCP)', checkout: 'Abandono en checkout', bounce: 'Tasa de rebote', bundleShare: 'Pedidos con bundle', subscribers: 'Pedidos por suscripción', reviewCoverage: 'Productos con 5+ reseñas', touchpoints: 'Puntos de contacto medidos', syncLag: 'Retraso de sincronización del catálogo', catalog: 'SKUs publicados', redirects: 'URLs migradas que resuelven', platform: 'Plataforma', design: 'Diseño de origen → tema' } },
  },
  badges: { live: 'En vivo', dev: 'En construcción', current: 'Actual', completed: 'Terminado', roles: { built: 'Construida', maintained: 'Mantenida', migrated: 'Migrada' } },
  experience: {
    'digitdeck-cto': {
      title: 'CTO y Shopify Technical Lead',
      summary: 'Fijo el estándar de ingeniería de una agencia Shopify y construyo el sistema que entrega: librerías de componentes, QA automatizado, CI/CD y herramientas de agentes de IA.',
      highlights: [
        'Estandaricé una arquitectura híbrida Liquid + islas React con una librería compartida de 33 componentes y tokens de diseño para 14 marcas.',
        'Construí una suite de apps Shopify multi-tenant sobre el stack oficial de Remix — pruebas A/B, reseñas, bundles, referidos, aviso de stock — más un motor de facturación de suscripciones con 800+ pruebas automatizadas.',
        'Entregué Shopify Functions compiladas a WASM, un Web Pixel con consentimiento y Theme App Extensions.',
        'Lideré migraciones de WooCommerce a Shopify y de staging a producción; re-plataformé un tema Liquid de 11.000 líneas a islas React con paridad visual verificada.',
        'Monté pipelines de GitHub Actions y un arnés de Playwright que prueba tiendas completas por comportamiento, con 40+ chequeos específicos de Shopify.',
        'Investigué 59 marcas DTC hasta una librería de 70 patrones de conversión y escribí la metodología bayesiana de pruebas A/B de la agencia.',
      ],
      metricLabels: { storefronts: 'Tiendas', modules: 'Módulos de app', tests: 'Pruebas automatizadas' },
    },
    ellamau: {
      title: 'Lead Shopify Developer',
      summary: 'Construcción completa de una tienda Shopify para una marca de moda de EE. UU., de la planeación al despliegue.',
      highlights: ['Secciones Liquid modulares con bloques reutilizables y schemas configurables.', '15+ plantillas responsivas, móvil primero.', 'Lighthouse por encima de 90 tras la optimización.'],
      metricLabels: { templates: 'Plantillas', lighthouse: 'Lighthouse' },
    },
    abidata: {
      title: 'Desarrollador Full Stack',
      summary: 'Plataforma interna para crear, personalizar y enviar newsletters empresariales.',
      highlights: ['Editor de correos en React que recortó ~40 % el tiempo de crear una campaña.', '10.000+ contactos y cientos de campañas activas.', 'Dueño de las APIs REST del diseño al despliegue.'],
      metricLabels: { contacts: 'Contactos', campaignTime: 'Tiempo por campaña', users: 'Usuarios internos' },
    },
    rh: {
      title: 'Desarrollador Frontend',
      summary: 'Migración de CMS empresarial de Adobe AEM a Contentful para un gran retailer de EE. UU.',
      highlights: ['25+ componentes reutilizables que hicieron posible la migración.', 'El trabajo de accesibilidad llevó Lighthouse de ~70 a 95+.', 'Recorté ~45.000 USD al año en costos de autoría de contenido.'],
      metricLabels: { components: 'Componentes', lighthouse: 'Lighthouse', savings: 'Ahorro' },
    },
    'digitdeck-fe': {
      title: 'Desarrollador Frontend (Shopify)',
      summary: 'Construí y optimicé tiendas Shopify con temas Liquid a medida.',
      highlights: ['Secciones, bloques y snippets a medida para 4+ tiendas.', 'El trabajo de UX y checkout subió la conversión 10–20 %.', 'Páginas 30–40 % más rápidas; tráfico orgánico +20 %.'],
      metricLabels: { conversion: 'Conversión', loadTime: 'Tiempo de carga', organic: 'Tráfico orgánico' },
    },
    orthofix: {
      title: 'Desarrollador Salesforce',
      summary: 'Aplicaciones internas de salud para flujos de pacientes y operaciones.',
      highlights: ['Lightning Web Components usados por 50+ usuarios internos.', 'Flujos sobre miles de registros de pacientes y dispositivos.', '~20 % menos captura manual de datos.'],
      metricLabels: { users: 'Usuarios', dataEntry: 'Captura manual' },
    },
    ibox: {
      title: 'Desarrollador Frontend React',
      summary: 'Sitio corporativo de soluciones de lockers inteligentes para EE. UU. y Latinoamérica.',
      highlights: ['20+ componentes React reutilizables y 10+ páginas responsivas.', 'Lighthouse 90+ y cargas ~35 % más rápidas.'],
      metricLabels: { components: 'Componentes', pages: 'Páginas', lighthouse: 'Lighthouse' },
    },
  },
  stores: {
    'the-gummy-box': { industry: 'Gomitas funcionales', tagline: 'Armador de kits cableado a nuestro módulo de Bundles, suscripciones y tracking propio.', description: 'La oferta del kit tenía que ser simple para el comprador e imposible de trampear: el módulo de Bundles calcula el precio del kit con una Shopify Function en el checkout, así que la escalera de 10% a 20% se aplica sola y no hay cupón que buscar. Las suscripciones corren por Treli y cada superficie reporta eventos propios, así que la marca ve qué hace cada bloque.', factLabels: { ladder: 'Descuento del kit, automático en el checkout' } },
    'nos-cafe': { industry: 'Café de especialidad', tagline: 'Diseño de Framer portado 1:1 a Liquid; armador de cajas con descuentos por escalera.', description: 'Un diseño de Framer terminado que no podía perder un píxel en el camino a Shopify. Lo porté 1:1 a Liquid y construí el armador de cajas que necesitaba el tostador: hasta cinco bolsas por caja, molienda y tamaño por bolsa, y un descuento que sube del 10% al 20% a medida que se llena.', factLabels: { ladder: 'Descuento de la caja, sube con cada bolsa' } },
    millennio: { industry: 'Perfumería', tagline: 'Port de Framer sobre islas React, 260+ elementos medidos.', description: 'La perfumería quería su diseño de Framer vivo en Shopify y quería saber qué tocan de verdad los compradores. El port corre como islas React sobre base Liquid, y cada tarjeta, carril y CTA está instrumentado: 260+ elementos medidos reportan al dashboard Optimize.', factLabels: { tracked: 'Puntos de contacto medidos' } },
    mindfuel: { industry: 'Nootrópicos', tagline: 'Port completo a React V2, promovido a producción.', description: 'La marca se reconstruyó como port React V2 sobre la plantilla Digitdeck y se promovió a producción el 20 de agosto de 2026. Home, página de producto y quiz comparten una sola librería de componentes: un cambio se despliega una vez y llega a todas partes.', factLabels: { live: 'En vivo desde' } },
    nalua: { industry: 'Cuidado de la piel', tagline: 'Ofertas de compra y escalones por cantidad, flujo contra entrega.', description: 'El riesgo aquí eran ofertas que solo parecían descuentos. Las ofertas de compra y los niveles por cantidad están cableados a descuentos automáticos reales, y el flujo contra entrega por Releasit se mantiene en sincronía oferta por oferta: 19 de 19 coinciden.', factLabels: { offers: 'Ofertas en sincronía con contra entrega' } },
    sebum: { industry: 'Cuidado de la piel', tagline: 'Reconstrucción V2 con un muro de reseñas extensible.', description: 'La reconstrucción V2 llegó con un muro de reseñas extensible e islas React en la página de producto. El repo y el tema en vivo son idénticos byte a byte (paridad 100%), así que cada cambio sale de git y nada vive solo en el editor.' },
    'valdo-cafe': { industry: 'Café', tagline: 'Transferida de una tienda de pruebas a la real y promovida.', description: 'Construida en una tienda de staging, transferida a la real y promovida al día siguiente (9 y 10 de julio de 2026). Tema pequeño, plantillas limpias, lista para que el cliente la opere sin mí.', factLabels: { transfer: 'De la transferencia al aire' } },
    'factores-2x2': { industry: 'Suplementos', tagline: 'De Framer a Liquid, pasada de calidad web hasta 95+.', description: 'Primero Framer a Liquid, después un pase de calidad web por toda la matriz de rutas. Hoy la home marca 100 en accesibilidad y 100 en SEO en Lighthouse móvil (medición de laboratorio, septiembre de 2026).', factLabels: { quality: 'Accesibilidad · SEO (Lighthouse móvil, sep 2026)' } },
    pixxiesx: { industry: 'Moda', tagline: 'Quiz de producto, PDP guiada por metaobjetos, entrega el mismo día.', description: 'Una marca de gafas que necesitaba que la página de producto respondiera antes que soporte. Un quiz de producto, una PDP movida por seis tipos de metaobjetos (beneficios, rasgos, material, FAQ, dolores, medidas) y mensajes de entrega el mismo día.' },
    'luxe-shine': { industry: 'Belleza', tagline: 'Hero de video controlado por scroll, retrofit de tracking.', description: 'El tema existente se quedó; lo que cambió es lo que reporta. Un hero de video controlado por scroll, un despliegue completo de imágenes en la PDP y un retrofit de tracking para que esta tienda alimente el mismo dashboard que las construcciones nuevas.' },
    atmosfera: { industry: 'Computadores', tagline: 'Sincronización de catálogo desde listas del proveedor, doble precio.', description: 'Un retailer de computadores cuyo catálogo cambia con las listas de precios de los proveedores. El catálogo se sincroniza desde esas listas cada 12 horas, los precios se muestran con y sin IVA, las especificaciones viven en metafields y el stock por variante se refleja.', factLabels: { pricing: 'Precios mostrados', sync: 'Catálogo actualizado cada' } },
    'saint-theory': { industry: 'Streetwear', tagline: 'Tema Liquid a medida, sigue en vivo.', description: 'Marca de streetwear con un tema Liquid a medida construido en 2023 que sigue siendo el publicado hoy.' },
    peluna: { industry: 'Mascotas', tagline: 'Rediseño sobre la plantilla Digitdeck con pruebas A/B.', description: 'Rediseño sobre la plantilla Digitdeck con pruebas A/B montadas desde el día uno y metaobjetos para los datos de producto; el tema Shrine del cliente sigue corriendo en paralelo hasta el cambio.', factLabels: { ab: 'Pruebas A/B' } },
    'en-amor-a-dos': { industry: 'Joyería', tagline: '57 secciones propias sobre islas React.', description: 'Una marca de joyería con 57 secciones a medida construidas en islas React sobre base Dawn, montadas en un tema de QA mientras la tienda en vivo del cliente sigue intacta.' },
    unik: { industry: 'Denim', tagline: 'Tienda bilingüe y de doble moneda con i18n masiva del catálogo.', description: 'Una marca de denim reconstruida como tienda bilingüe y en dos monedas, con el catálogo traducido en bloque por la Admin GraphQL API. La construcción va 389 archivos por delante del Dawn en vivo del cliente.', factLabels: { langs: 'Idiomas · monedas' } },
    'origen-vital': { industry: 'Suplementos', tagline: 'Port de Framer, quiz de producto, 302 reseñas sembradas, landings promo.', description: 'Una marca de suplementos portada desde Framer con quiz de producto, 302 reseñas sembradas con fotos (80+ por producto), un mega menú sobre cinco colecciones y landings promocionales sintetizadas a partir de 192 anuncios.', factLabels: { reviews: 'Reseñas con foto, en vivo', ads: 'Anuncios convertidos en landings' } },
    'para-machos': { industry: 'Cuidado masculino', tagline: 'Nuevo tema Digitdeck en construcción.', description: 'Una marca de cuidado masculino que recibe un tema Digitdeck nuevo en una copia DEV mientras el tema en vivo del cliente se mantiene inmutable hasta el lanzamiento.' },
    tierramont: { industry: 'Outdoor', tagline: 'Nuevo tema en construcción para la tienda real.', description: 'Una marca de ropa outdoor con un tema nuevo en construcción para la tienda real, seguido issue por issue (81 hasta ahora) en un tablero compartido que el cliente puede leer.' },
    'alma-de-aviador': { industry: 'Ropa', tagline: 'Migración de WooCommerce a Shopify con port de Framer.', description: 'Una marca de ropa de inspiración aeronáutica migrada de WooCommerce a Shopify, con el diseño de Framer componentizado en 35 secciones sobre el tema V2.', factLabels: { migration: 'Migración de plataforma' } },
    joystaz: { industry: 'Denim', tagline: 'Tema Liquid con Tailwind y backend de reseñas propio.', description: 'Marca de denim sobre un tema Liquid con Tailwind y un backend de reseñas propio (Express + Prisma) construido en 2025.' },
    'new-urban': { industry: 'Moda', tagline: 'Tienda Digitdeck temprana.', description: 'Tienda Digitdeck temprana para una marca de moda, construida en 2023.' },
    gummind: { industry: 'Bienestar', tagline: 'Tienda sobre tema skeleton.', description: 'Tienda de bienestar sobre tema skeleton, construida en 2025.' },
    rimo: { industry: 'Retail', tagline: 'Tienda Digitdeck temprana.', description: 'Tienda Digitdeck temprana, construida en 2023.' },
  },
  products: {
    'digitdeck-apps': { tagline: 'Una instalación, cinco módulos', description: 'App Shopify multi-tenant sobre el stack oficial de Remix: aviso de stock, bundles, referidos, reseñas, pruebas A/B. Dos Shopify Functions, un Web Pixel con consentimiento y una Theme App Extension.' },
    'digitdeck-platform': { tagline: 'El sistema operativo de la agencia', description: 'Monolito modular con aislamiento por tenant, registro de módulos, RBAC y una puerta de IA bring-your-own. En vivo en app.digitdeck.co.' },
    'audit-dashboard': { tagline: 'Auditorías que el cliente abre sin internet', description: 'Renderiza un dashboard HTML autocontenido a partir de datos de auditoría, tema de marca y capturas. Sin CDN, sin peticiones externas.' },
    'feedback-portal': { tagline: 'Feedback de clientes como issues de GitHub', description: 'Portal privado multi-cliente donde cada reporte se vuelve un issue estandarizado en el tablero correcto.' },
    track: { tagline: 'Eventos propios por convención', description: 'Un contrato data-dd-* que sigue cada sección, alimentando el dashboard Optimize y el módulo de pruebas A/B.' },
  },
  projects: {
    kotodama: { tagline: 'Aprende japonés como un JRPG', description: 'De cero a JLPT N1 con repetición espaciada, escucha, kanji y misiones de lectura.' },
    'autofill-plugin': { tagline: 'Autollenado para el navegador', description: 'Llena formularios repetitivos desde perfiles guardados.' },
    pagui: { tagline: 'Onboarding con OCR', description: 'Registro de identidad con OCR para clientes bancarios.' },
    scorrea: { tagline: 'Portafolio de desarrollador', description: 'Sitio en Astro para un desarrollador senior.' },
    'dr-hugo': { tagline: 'Sitio de odontólogo estético', description: 'Presencia de servicios y citas para un consultorio dental.' },
    maxfolio: { tagline: 'Este sitio', description: 'Cuatro lenguajes de diseño, un modelo de contenido, tres idiomas.' },
  },
  footer: { tagline: 'Ingeniería Shopify, medida.', services: ['Tiendas Shopify', 'Apps Shopify', 'CRO y pruebas A/B', 'Migraciones de tienda', 'Rendimiento'], servicesTitle: 'Qué hago', quickLinks: 'Enlaces rápidos', rights: 'Todos los derechos reservados.' },
  location: 'Medellín, Colombia',
}
