import type { PortfolioContent } from './types'

export const es: PortfolioContent = {
  meta: {
    title: 'Maximiliano Bustamante | CTO & Shopify Tech Lead',
    description:
      'CTO & Shopify Tech Lead en Digitdeck. 18+ tiendas Shopify, una suite de apps en producción y el sistema que las entrega. Disponible para consultoría CRO en Shopify.',
  },
  hero: {
    eyebrow: 'CTO & Shopify Tech Lead · Digitdeck',
    positioning: 'Construyo tiendas Shopify que venden — y el sistema que las entrega.',
    lead: '18+ tiendas, una suite de apps multi-tenant y un pipeline de QA que atrapa lo que un lanzamiento habría roto. Recibes ingeniería Shopify medida, no adivinada.',
    availability: 'Disponible para consultoría CRO en Shopify y cotizaciones',
    ctaContact: 'Escríbeme',
    ctaCv: 'Descargar CV',
  },
  stats: {
    storefronts: 'Tiendas Shopify',
    modules: 'Módulos de app en producción',
    functions: 'Shopify Functions (WASM)',
    standards: 'Estándares de ingeniería',
    tests: 'Pruebas automatizadas',
    brands: 'Sistemas de tokens de marca',
  },
  sections: {
    experience: { eyebrow: 'Experiencia', title: 'Dónde pasó', titleAccent: 'el trabajo', achievements: 'Qué se entregó', technologies: 'Stack', visit: 'Visitar sitio' },
    shopify: {
      eyebrow: 'Trabajo en Shopify',
      title: 'Tiendas, apps',
      titleAccent: 'y la plataforma detrás',
      lead: 'Qué es cada tienda, qué construí y sobre qué corre. Abre una para ver las cifras; las que están en vivo enlazan a la tienda real.',
      tabStores: 'Tiendas',
      tabProducts: 'Apps y plataforma',
      legacyLabel: 'Trabajo anterior',
      visit: 'Visitar tienda',
      showAll: 'Ver las {n} tiendas',
      showLess: 'Ver menos',
    },
    gallery: {
      eyebrow: 'Galería',
      title: 'El mismo marco,',
      titleAccent: 'para cada tienda',
      lead: 'Home y página de producto, escritorio y móvil — capturadas igual en todos los proyectos. Pasa el cursor por una pantalla para ver la página de producto; abre cualquier tienda para ver su caso: las cuatro tomas, las puntuaciones de Lighthouse y sobre qué corre.',
      filterAll: 'Todas',
      filterLive: 'En vivo',
      filterDev: 'En construcción',
      viewLabel: 'Vista',
      viewCarousel: 'Carrusel',
      viewDevices: 'Laptop + móvil',
      viewPhones: 'Solo móviles',
      open: 'Abrir galería',
      close: 'Cerrar',
      home: 'Home',
      pdp: 'Página de producto',
      desktop: 'Escritorio',
      mobile: 'Móvil',
    },
    projects: { eyebrow: 'Proyectos', title: 'Lo que construyo', titleAccent: 'en mi tiempo', view: 'Ver proyecto' },
    skills: {
      eyebrow: 'Habilidades',
      title: 'Con qué',
      titleAccent: 'trabajo',
      groups: { shopify: 'Shopify', frontend: 'Frontend', backend: 'Backend', quality: 'Pruebas y CI/CD', cro: 'CRO y analítica', ai: 'Ingeniería con IA' },
    },
    contact: {
      eyebrow: 'Contacto',
      title: 'Tu tienda recibe tráfico.',
      titleAccent: 'Convirtamos más de él en pedidos.',
      lead: 'Encuentro dónde se fuga tu tienda Shopify — velocidad, ofertas, fricción en el checkout — y lo arreglo con pruebas A/B que puedes leer, no con corazonadas. Primero el diagnóstico, después el arreglo.',
      status: 'Disponible para consultoría',
      note: 'Marcas de EE. UU. y Latinoamérica. Recibes respuesta en un día hábil.',
      cta: 'Enviar mensaje',
      email: 'Correo',
      phone: 'Teléfono',
      location: 'Ubicación',
    },
    explore: { eyebrow: 'Explorar', title: 'El mismo portafolio, cuatro diseños', lead: 'Elige la estética que prefieras. El contenido es idéntico.', viewing: 'Estás viendo' },
    caseStudy: { facts: 'En cifras', results: 'Resultados medidos', stack: 'Stack', visit: 'Visitar tienda', prev: 'Anterior', next: 'Siguiente', timeline: 'Ventana de construcción', commits: 'commits', sections: 'secciones propias', open: 'Caso', metrics: 'Lighthouse · móvil', perf: 'Rendimiento', a11y: 'Accesibilidad', bp: 'Buenas prácticas', seo: 'SEO', lcp: 'LCP', measured: 'Medición de laboratorio en la página de inicio, {date}, mediana de {runs} corridas de Lighthouse (móvil, red simulada).' },
  },
  badges: { live: 'En vivo', dev: 'En construcción', current: 'Actual', completed: 'Terminado', roles: { built: 'Construida', maintained: 'Mantenida', migrated: 'Migrada' } },
  experience: {
    'digitdeck-cto': {
      title: 'CTO y Shopify Technical Lead',
      summary: 'Fijo el estándar de ingeniería de una agencia Shopify y construyo el sistema que entrega: librerías de componentes, QA automatizado, CI/CD y herramientas de agentes de IA.',
      highlights: [
        'Estandaricé una arquitectura híbrida Liquid + islas React con una librería compartida de 33 componentes y tokens de diseño para 14 marcas.',
        'Construí una suite de apps Shopify multi-tenant sobre el stack oficial de Remix — pruebas A/B, reseñas, bundles, referidos, aviso de stock — más un motor de facturación de suscripciones con 800+ pruebas automatizadas.',
        'Entregué Shopify Functions compiladas a WASM, un Web Pixel con consentimiento y Theme App Extensions.',
        'Lideré migraciones de WooCommerce a Shopify y de staging a producción; re-plataformé un tema Liquid de 11.000 líneas a islas React con paridad visual verificada.',
        'Monté pipelines de GitHub Actions y un arnés de Playwright que prueba tiendas completas por comportamiento, con 40+ chequeos específicos de Shopify.',
        'Investigué 59 marcas DTC hasta una librería de 70 patrones de conversión y escribí la metodología bayesiana de pruebas A/B de la agencia.',
      ],
      metricLabels: { storefronts: 'Tiendas', modules: 'Módulos de app', tests: 'Pruebas automatizadas' },
    },
    ellamau: {
      title: 'Lead Shopify Developer',
      summary: 'Construcción completa de una tienda Shopify para una marca de moda de EE. UU., de la planeación al despliegue.',
      highlights: ['Secciones Liquid modulares con bloques reutilizables y schemas configurables.', '15+ plantillas responsivas, móvil primero.', 'Lighthouse por encima de 90 tras la optimización.'],
      metricLabels: { templates: 'Plantillas', lighthouse: 'Lighthouse' },
    },
    abidata: {
      title: 'Desarrollador Full Stack',
      summary: 'Plataforma interna para crear, personalizar y enviar newsletters empresariales.',
      highlights: ['Editor de correos en React que recortó ~40 % el tiempo de crear una campaña.', '10.000+ contactos y cientos de campañas activas.', 'Dueño de las APIs REST del diseño al despliegue.'],
      metricLabels: { contacts: 'Contactos', campaignTime: 'Tiempo por campaña', users: 'Usuarios internos' },
    },
    rh: {
      title: 'Desarrollador Frontend',
      summary: 'Migración de CMS empresarial de Adobe AEM a Contentful para un gran retailer de EE. UU.',
      highlights: ['25+ componentes reutilizables que hicieron posible la migración.', 'El trabajo de accesibilidad llevó Lighthouse de ~70 a 95+.', 'Recorté ~45.000 USD al año en costos de autoría de contenido.'],
      metricLabels: { components: 'Componentes', lighthouse: 'Lighthouse', savings: 'Ahorro' },
    },
    'digitdeck-fe': {
      title: 'Desarrollador Frontend (Shopify)',
      summary: 'Construí y optimicé tiendas Shopify con temas Liquid a medida.',
      highlights: ['Secciones, bloques y snippets a medida para 4+ tiendas.', 'El trabajo de UX y checkout subió la conversión 10–20 %.', 'Páginas 30–40 % más rápidas; tráfico orgánico +20 %.'],
      metricLabels: { conversion: 'Conversión', loadTime: 'Tiempo de carga', organic: 'Tráfico orgánico' },
    },
    orthofix: {
      title: 'Desarrollador Salesforce',
      summary: 'Aplicaciones internas de salud para flujos de pacientes y operaciones.',
      highlights: ['Lightning Web Components usados por 50+ usuarios internos.', 'Flujos sobre miles de registros de pacientes y dispositivos.', '~20 % menos captura manual de datos.'],
      metricLabels: { users: 'Usuarios', dataEntry: 'Captura manual' },
    },
    ibox: {
      title: 'Desarrollador Frontend React',
      summary: 'Sitio corporativo de soluciones de lockers inteligentes para EE. UU. y Latinoamérica.',
      highlights: ['20+ componentes React reutilizables y 10+ páginas responsivas.', 'Lighthouse 90+ y cargas ~35 % más rápidas.'],
      metricLabels: { components: 'Componentes', pages: 'Páginas', lighthouse: 'Lighthouse' },
    },
  },
  stores: {
    'the-gummy-box': { industry: 'Gomitas funcionales', tagline: 'Armador de kits cableado a nuestro módulo de Bundles, suscripciones y tracking propio.', description: 'Marca de gomitas funcionales sobre plantilla Digitdeck con un armador de kits cableado a nuestro módulo de Bundles: el descuento lo calcula una Shopify Function, no un cupón. Las suscripciones corren por Treli y cada superficie reporta eventos propios.', factLabels: { ladder: 'Escalera de descuento', modules: 'Módulos de Digitdeck conectados' } },
    'nos-cafe': { industry: 'Café de especialidad', tagline: 'Diseño de Framer portado 1:1 a Liquid; armador de cajas con descuentos por escalera.', description: 'Tostador de café de especialidad cuyo diseño de Framer se portó 1:1 a Liquid. El armador de cajas mezcla hasta cinco bolsas y el descuento sube con cada una, con molienda y tamaño por bolsa.', factLabels: { ladder: 'Escalera de descuento', bags: 'Bolsas por caja' } },
    millennio: { industry: 'Perfumería', tagline: 'Port de Framer sobre islas React, 260+ elementos medidos.', description: 'Perfumería colombiana portada de Framer a islas React sobre base Liquid. Cada tarjeta, carril y CTA está instrumentado: la tienda reporta 260+ elementos al dashboard Optimize.', factLabels: { tracked: 'Elementos medidos (data-dd-*)' } },
    mindfuel: { industry: 'Nootrópicos', tagline: 'Port completo a React V2, promovido a producción.', description: 'Marca de nootrópicos reconstruida como port React V2 sobre la plantilla Digitdeck y promovida a producción en agosto de 2026. Home, PDP y quiz comparten una librería de componentes.', factLabels: { live: 'Promovida a producción' } },
    nalua: { industry: 'Cuidado de la piel', tagline: 'Ofertas de compra y escalones por cantidad, flujo contra entrega.', description: 'Marca de cuidado de la piel sobre el tema Digitdeck con ofertas de compra y escalones por cantidad cableados a descuentos automáticos reales, y contra entrega por Releasit sincronizado oferta a oferta.', factLabels: { offers: 'Ofertas Releasit sincronizadas' } },
    sebum: { industry: 'Cuidado de la piel', tagline: 'Reconstrucción V2 con un muro de reseñas extensible.', description: 'Reconstrucción V2 de una marca de skincare con un muro de reseñas extensible e islas React en la PDP. El repo y el tema publicado son idénticos byte a byte: todo cambio sale desde git.', factLabels: { parity: 'Paridad repo ↔ live' } },
    'valdo-cafe': { industry: 'Café', tagline: 'Transferida de una tienda de pruebas a la real y promovida.', description: 'Marca de café construida en una tienda de pruebas, transferida a la real y promovida al día siguiente. Tema pequeño, plantillas limpias, lista para que el cliente la opere.', factLabels: { transfer: 'Transferencia → promovida' } },
    'factores-2x2': { industry: 'Suplementos', tagline: 'De Framer a Liquid, pasada de calidad web hasta 95+.', description: 'Marca de suplementos portada de Framer a Liquid y llevada por una pasada de calidad web en toda la matriz de rutas hasta superar 95 en rendimiento, accesibilidad y SEO.', factLabels: { quality: 'Pasada de calidad web (perf · a11y · SEO)' } },
    pixxiesx: { industry: 'Moda', tagline: 'Quiz de producto, PDP guiada por metaobjetos, entrega el mismo día.', description: 'Marca de gafas de sol con quiz de producto, PDP guiada por metaobjetos (beneficios, características, material, FAQ, dolores, medidas) y mensaje de entrega el mismo día.', factLabels: { metaobjects: 'Tipos de metaobjeto en la PDP' } },
    'luxe-shine': { industry: 'Belleza', tagline: 'Hero de video controlado por scroll, retrofit de tracking.', description: 'Marca de belleza con hero de video controlado por scroll, despliegue completo de imágenes en PDP y retrofit de tracking para que el tema existente reporte al mismo dashboard que los builds nuevos.', factLabels: { hero: 'Hero' } },
    atmosfera: { industry: 'Computadores', tagline: 'Sincronización de catálogo desde listas del proveedor, doble precio.', description: 'Tienda de computadores cuyo catálogo se sincroniza desde listas de precios del proveedor, con doble precio (con y sin IVA), metafields de especificaciones y espejo de stock por variante.', factLabels: { pricing: 'Modelo de precios', sync: 'Ciclo de reconciliación de inventario' } },
    'saint-theory': { industry: 'Streetwear', tagline: 'Tema Liquid a medida, sigue en vivo.', description: 'Marca de streetwear con un tema Liquid a medida construido en 2023 que sigue siendo el publicado hoy.' },
    peluna: { industry: 'Mascotas', tagline: 'Rediseño sobre la plantilla Digitdeck con pruebas A/B.', description: 'Marca de mascotas rediseñada sobre la plantilla Digitdeck con pruebas A/B y metaobjetos para los datos de producto; el tema Shrine del cliente se mantiene en paralelo.', factLabels: { ab: 'Marco de experimentos' } },
    'en-amor-a-dos': { industry: 'Joyería', tagline: '57 secciones propias sobre islas React.', description: 'Marca de joyería con 57 secciones propias sobre islas React en base Dawn, en un tema QA mientras el publicado del cliente no se toca.', factLabels: { custom: 'Secciones propias construidas' } },
    unik: { industry: 'Denim', tagline: 'Tienda bilingüe y de doble moneda con i18n masiva del catálogo.', description: 'Marca de denim reconstruida como tienda bilingüe y de doble moneda con i18n masiva del catálogo por la Admin GraphQL API. El build va 389 archivos por delante del Dawn del cliente.', factLabels: { langs: 'Idiomas · monedas', ahead: 'Archivos por delante del live del cliente' } },
    'origen-vital': { industry: 'Suplementos', tagline: 'Port de Framer, quiz de producto, 302 reseñas sembradas, landings promo.', description: 'Marca de suplementos portada de Framer con quiz de producto, 302 reseñas sembradas con fotos, mega menú sobre cinco colecciones y landings promo sintetizadas a partir de 192 anuncios.', factLabels: { reviews: 'Reseñas sembradas (80+ por producto)', ads: 'Anuncios sintetizados en landings', collections: 'Colecciones + mega menú' } },
    'para-machos': { industry: 'Cuidado masculino', tagline: 'Nuevo tema Digitdeck en construcción.', description: 'Marca de cuidado masculino con un tema Digitdeck nuevo en una copia DEV mientras el publicado del cliente permanece inmutable.' },
    tierramont: { industry: 'Outdoor', tagline: 'Nuevo tema en construcción para la tienda real.', description: 'Marca de ropa outdoor con un tema nuevo en construcción para la tienda real, seguido issue por issue en un tablero compartido.', factLabels: { issues: 'Issues en el tablero' } },
    'alma-de-aviador': { industry: 'Ropa', tagline: 'Migración de WooCommerce a Shopify con port de Framer.', description: 'Marca de ropa de inspiración aeronáutica migrada de WooCommerce a Shopify, con el diseño de Framer componentizado en 35 secciones sobre el tema V2.', factLabels: { framer: 'Secciones de Framer componentizadas', migration: 'Migración' } },
    joystaz: { industry: 'Denim', tagline: 'Tema Liquid con Tailwind y backend de reseñas propio.', description: 'Marca de denim sobre un tema Liquid con Tailwind y un backend de reseñas propio (Express + Prisma) construido en 2025.', factLabels: { reviews: 'Reseñas sembradas (80+ por producto)' } },
    'new-urban': { industry: 'Moda', tagline: 'Tienda Digitdeck temprana.', description: 'Tienda Digitdeck temprana para una marca de moda, construida en 2023.' },
    gummind: { industry: 'Bienestar', tagline: 'Tienda sobre tema skeleton.', description: 'Tienda de bienestar sobre tema skeleton, construida en 2025.' },
    rimo: { industry: 'Retail', tagline: 'Tienda Digitdeck temprana.', description: 'Tienda Digitdeck temprana, construida en 2023.' },
  },
  products: {
    'digitdeck-apps': { tagline: 'Una instalación, cinco módulos', description: 'App Shopify multi-tenant sobre el stack oficial de Remix: aviso de stock, bundles, referidos, reseñas, pruebas A/B. Dos Shopify Functions, un Web Pixel con consentimiento y una Theme App Extension.' },
    'digitdeck-platform': { tagline: 'El sistema operativo de la agencia', description: 'Monolito modular con aislamiento por tenant, registro de módulos, RBAC y una puerta de IA bring-your-own. En vivo en app.digitdeck.co.' },
    'audit-dashboard': { tagline: 'Auditorías que el cliente abre sin internet', description: 'Renderiza un dashboard HTML autocontenido a partir de datos de auditoría, tema de marca y capturas. Sin CDN, sin peticiones externas.' },
    'feedback-portal': { tagline: 'Feedback de clientes como issues de GitHub', description: 'Portal privado multi-cliente donde cada reporte se vuelve un issue estandarizado en el tablero correcto.' },
    track: { tagline: 'Eventos propios por convención', description: 'Un contrato data-dd-* que sigue cada sección, alimentando el dashboard Optimize y el módulo de pruebas A/B.' },
  },
  projects: {
    kotodama: { tagline: 'Aprende japonés como un JRPG', description: 'De cero a JLPT N1 con repetición espaciada, escucha, kanji y misiones de lectura.' },
    'autofill-plugin': { tagline: 'Autollenado para el navegador', description: 'Llena formularios repetitivos desde perfiles guardados.' },
    pagui: { tagline: 'Onboarding con OCR', description: 'Registro de identidad con OCR para clientes bancarios.' },
    scorrea: { tagline: 'Portafolio de desarrollador', description: 'Sitio en Astro para un desarrollador senior.' },
    'dr-hugo': { tagline: 'Sitio de odontólogo estético', description: 'Presencia de servicios y citas para un consultorio dental.' },
    maxfolio: { tagline: 'Este sitio', description: 'Cuatro lenguajes de diseño, un modelo de contenido, tres idiomas.' },
  },
  footer: { tagline: 'Ingeniería Shopify, medida.', services: ['Tiendas Shopify', 'Apps Shopify', 'CRO y pruebas A/B', 'Migraciones de tienda', 'Rendimiento'], servicesTitle: 'Qué hago', quickLinks: 'Enlaces rápidos', rights: 'Todos los derechos reservados.' },
  location: 'Medellín, Colombia',
}
