import type { PortfolioContent } from './types'

export const ja: PortfolioContent = {
  meta: {
    title: 'Maximiliano Bustamante | CTO & Shopify Tech Lead',
    description:
      'DigitdeckのCTO & Shopify Tech Lead。18以上のShopifyストア、本番稼働中のアプリ群、そしてそれらを届ける仕組み。Shopify CROコンサルティング受付中。',
  },
  hero: {
    eyebrow: 'CTO & Shopify Tech Lead · Digitdeck',
    positioning: 'アクセスはあるのに、注文につながらない。その原因を突き止めます。',
    lead: '18以上のストア、マルチテナントのアプリ群、リリース前に不具合を捕まえるQAハーネス。計測に基づくShopifyエンジニアリング：何が動き、なぜ動き、次に何をするかまで。',
    availability: 'Shopify CROコンサルティング・お見積り受付中',
    location: 'メデジン拠点、米国・中南米のブランドと協業',
    ctaContact: 'お問い合わせ',
    ctaPrimary: '無料20分のストア診断を受ける',
    ctaSecondary: '18店舗以上の実績を見る',
    ctaNote: '売り込みも契約も不要。売上が漏れている箇所と、最初に直す点だけをお伝えします。',
    ctaCv: 'CVをダウンロード',
  },
  stats: {
    storefronts: 'Shopifyストア',
    modules: '本番稼働中のアプリモジュール',
    functions: 'Shopify Functions（WASM）',
    standards: 'エンジニアリング標準',
    tests: '自動テスト',
    brands: 'ブランドのトークンシステム',
  },
  sections: {
    experience: { eyebrow: 'すべての役割を、順番通りに', title: '仕事をしてきた', titleAccent: '場所', achievements: '成果', technologies: '技術スタック', visit: 'サイトを見る' },
    shopify: {
      eyebrow: '実在するストア、実際のチェックアウト',
      title: 'ストア、アプリ、',
      titleAccent: 'そしてその裏側のプラットフォーム',
      lead: '下のどのストアを開いても、モックアップではなく実際のチェックアウトまで1クリックです。18店舗以上：Shopify Functionsで価格計算するバンドル、商品診断クイズ、レビューウォール、二通貨カタログ、FramerやWooCommerceからの移行。',
      tabStores: 'ストア',
      tabProducts: 'アプリとプラットフォーム',
      legacyLabel: '過去の実績',
      visit: 'ストアを見る',
      showAll: '{n}店舗すべてを表示',
      showLess: '表示を減らす',
      filterAll: 'すべて',
      filters: { bundles: 'バンドル', quiz: '診断クイズ', subscriptions: 'サブスク', reviews: 'レビュー', migration: '移行', islands: 'Reactアイランド', tracking: '計測', i18n: '多通貨' },
    },
    gallery: {
      eyebrow: 'お客様が手にするスマホ向けに',
      title: '売るためにつくる、',
      titleAccent: 'どの画面でも',
      lead: 'ここにあるストアはすべて同じ基準でつくっています。クリックを勝ち取るトップページと、購入を決める商品ページを、お客様が実際に使うスマホで。カーソルを合わせると商品ページに切り替わり、ストアを開くと4枚のキャプチャ、構築の経緯、技術構成が見られます。',
      filterAll: 'すべて',
      filterLive: '公開中',
      filterDev: '開発中',
      viewLabel: '表示',
      viewCarousel: 'カルーセル',
      viewDevices: 'ラップトップ＋スマホ',
      viewPhones: 'スマホのみ',
      open: 'ギャラリーを開く',
      close: '閉じる',
      home: 'トップページ',
      pdp: '商品ページ',
      desktop: 'デスクトップ',
      mobile: 'モバイル',
    },
    process: {
      eyebrow: '進め方',
      title: '5つのステップ、',
      titleAccent: '想定外なし',
      problemLabel: 'ボトルネック',
      problem: '表示速度、オファー、決済時の摩擦。売上が漏れる原因はたいていこの3つのどこかにあり、多くのチームはそこを推測で済ませています。',
      fixLabel: '解決の手順',
      fix: '毎回同じ順序の5つのチェックポイント。次に何が起き、各段階で何を受け取るかが分かります。',
      stepOf: 'ステップ {n} / {total}',
      deliverableLabel: '受け取るもの',
      steps: [
        { title: '診断', body: 'あなたのストア、数字、ボトルネック。1行も触る前にデータを読みます。', deliverable: '書面の診断：どこで売上が漏れ、何を最初に直すか。' },
        { title: 'パターンマップ', body: '各ページに計画を。どのセクション、どのオファー、どの証拠を、どの順で。', deliverable: '1行書く前に読める、ページごとの計画。' },
        { title: '構築', body: 'Digitdeckテンプレート上のLiquid + Reactアイランド。最初のコミットから計測。', deliverable: 'gitで管理されたテーマ。初日からファーストパーティのイベントを送信。' },
        { title: 'QA', body: '公開前にPlaywrightのハーネスがストア全体を振る舞いで検証します。', deliverable: 'ストア全体の振る舞いテストと、そのレポート。' },
        { title: '引き渡し', body: 'ストアはあなたのものに。設定はすべてエディタに、判断はすべてドキュメントに。', deliverable: 'エディタ、ドキュメント、数字。運用に私は不要です。' },
      ],
    },
    faq: {
      eyebrow: '先によくある質問',
      title: '初回の通話前に',
      titleAccent: 'よく聞かれること',
      items: [
        { q: 'Shopify Plusは必要ですか？', a: 'いいえ。ここにあるストアの多くは通常のShopifyで稼働しています。Shopify Functionsで価格計算するバンドル、アプリ群、計測はどちらのプランでも動きます。' },
        { q: 'すでに十分に売れている場合は？', a: 'その場合は診断で数字とともにそうお伝えし、そこで終わります。測定できる差がある場合にだけ提案します。' },
        { q: '最終的に何を受け取れますか？', a: 'gitで管理されたテーマ、初日からのファーストパーティ計測、公開前の振る舞いテスト、そして引き渡し時のエディタとドキュメント。運用に私は不要です。' },
        { q: '自社チームや代理店と一緒に進められますか？', a: 'はい。ここにあるどのストアも、クライアントがエディタとコンテンツを持ったまま公開しました。私はエンジニアリング、QAのゲート、計測を担当します。' },
        { q: '構築にはどれくらいかかりますか？', a: '範囲によります。診断の最後に期間を書面でお伝えし、進捗は共有ボードで課題ごとに追えます。' },
        { q: 'Shopifyの認定を受けていますか？', a: '現役のShopify Tech Leadです。このページにある18以上のストアそのものが実績の証明です。' },
        { q: 'このポートフォリオはAIが作ったのですか？', a: 'どのセクションもFigmaやFramerの参照から始まり、私が承認した上で手作業で構築しています。サンプルデータには必ずラベルを付けています。' },
      ],
    },
    manifesto: { label: '変わらないこと', lines: ['コードより先に、数字を読む。', 'エディタからではなく、gitから出荷する。', '1ページではなく、ストア全体をテストする。', '鍵を渡して終える。'] },
    testimonials: { eyebrow: 'お客様の声', title: 'クライアントの', titleAccent: '言葉' },
    now: { label: '現在', live: '公開中のストア {n}', dev: '構築中 {n}', band: '納品したストア', local: 'メデジン・現地時間 {time}' },
    statBand: { label: '仕事を数字で', asOf: '2026年9月時点' },
    years: { eyebrow: '1年に1ブロック、水増しなし', title: '5年間、', titleAccent: 'ひとつの方向へ', lead: '2022年のReactコンポーネントから、Shopifyストア群とその裏側のプラットフォームまで。各行はサイト全体と同じ記録から生成しています。', roles: '役割', shipped: 'ストア', work: 'クライアント案件', products: 'プロダクト', side: '個人プロジェクト', more: '+{n}件', count: 'ストア {n}', perYear: '構築がその年に及んだ納品物の数', eras: { '2022': 'ReactとSalesforce', '2023': '最初のShopifyストア', '2024': 'エンタープライズのフロント、そしてCTO', '2025': 'CTOと契約案件', '2026': 'ストア群とプラットフォーム' } },
    projects: { eyebrow: 'Shopifyの外で作っているもの', title: '個人的に', titleAccent: 'つくっているもの', view: 'プロジェクトを見る' },
    skills: {
      eyebrow: '導入済みではなく、実際に使ったもの',
      title: '使っている',
      titleAccent: '技術',
      groups: { shopify: 'Shopify', frontend: 'フロントエンド', backend: 'バックエンド', quality: 'テストとCI/CD', cro: 'CROと分析', ai: 'AIエンジニアリング' },
      usageLabel: 'ストア全体での使用',
      usageUnit: '店舗',
      usageNote: '上の索引にある{n}店舗から集計した実数です。推定ではありません。',
      usageItems: { liquid: 'Liquidテーマ', react: 'Reactアイランド', framer: 'Framer → Liquid移植', tailwind: 'Tailwind', metaobjects: 'メタオブジェクト', tracking: 'ファーストパーティ計測', bundles: 'バンドル', quiz: '商品診断クイズ', reviews: 'レビューウォール', migration: 'プラットフォーム移行' },
      narrative: {
        shopify: 'ストアとアプリは {skills} で出荷します。',
        frontend: 'フロントエンドは {skills}。',
        backend: 'その裏側には {skills}。',
        quality: '{skills} なしでは公開しません。',
        cro: '数字は {skills} から生まれます。',
        ai: '納品の仕組みは {skills} で構築しています。',
      },
    },
    contact: {
      eyebrow: 'まず診断。無料、20分。',
      title: 'ストアにアクセスはある。',
      titleAccent: 'それを、もっと注文に変えましょう。',
      lead: 'ストアのURLを送ってください。20分で、どこで売上が漏れているか（表示速度、オファー、チェックアウトの摩擦）と、最初に直すべき点をお見せします。',
      promise: '無料で、売り込みはありません。一緒に仕事をするかどうかに関わらず、最初に直すべき点が分かります。',
      status: 'コンサルティング受付中',
      note: '米国・中南米のブランド向け。1営業日以内にご返信します。',
      cta: '無料20分診断を受ける',
      ctaSecondary: 'またはメールで',
      nextLabel: 'その後の流れ',
      next: ['フォームかメールでストアのURLを送ってください。', '1営業日以内にご返信します。', '20分の通話：どこで売上が漏れているか、何を最初に直すか。', 'ご一緒する場合は、まず診断、それから修正です。'],
      urlLabel: 'ストアのURL',
      urlPlaceholder: 'yourstore.com',
      email: 'メール',
      phone: '電話',
      location: '所在地',
      elsewhere: 'その他',
    },
    explore: { eyebrow: '探索', title: '同じポートフォリオ、4つのデザイン', lead: 'お好みの美学を選んでください。内容は同じです。', viewing: '表示中' },
    caseStudy: { facts: '数字で見る', results: '計測した成果', stack: '技術スタック', visit: 'ストアを見る', prev: '前へ', next: '次へ', timeline: '構築期間', commits: 'コミット', sections: '独自セクション', open: '事例を見る', metrics: 'Lighthouse・モバイル', perf: 'パフォーマンス', a11y: 'アクセシビリティ', bp: 'ベストプラクティス', seo: 'SEO', lcp: 'LCP', measured: 'トップページのラボ計測、{date}、Lighthouse {runs}回の中央値（モバイル、回線シミュレーション）。', trail: '構築の記録', trailNote: 'ストアリポジトリのgit履歴より：{n}コミット、{range}。行数はテーマのlayout・sections・snippets・templatesで数えています。', perWeek: '週ごとのコミット数', peak: '最も多かった週：{n}コミット', codebase: 'コードベース', liquidLines: 'Liquidの行数', islandLines: 'TypeScriptの行数', sectionsCount: 'テーマのセクション数', weeks: '週', copyLink: 'リンクをコピー', copied: 'コピーしました'  },
  },
  badges: { live: '公開中', dev: '開発中', current: '現職', completed: '完了', roles: { built: '構築', maintained: '保守', migrated: '移行' } },
  experience: {
    'digitdeck-cto': {
      title: 'CTO & Shopify テクニカルリード',
      summary: 'Shopifyエージェンシーのエンジニアリング標準を定め、届ける仕組みそのもの（コンポーネントライブラリ、自動QA、CI/CD、AIエージェントのツール）を構築しています。',
      highlights: [
        'Liquid + Reactアイランドのハイブリッド構成を標準化。33コンポーネントの共有ライブラリと14ブランドにまたがるデザイントークン。',
        '公式Remixスタック上にマルチテナントのShopifyアプリ群を構築（A/Bテスト、レビュー、バンドル、紹介、再入荷通知）。加えて800以上の自動テストを備えたサブスクリプション課金エンジン。',
        'WASMにコンパイルしたShopify Functions、同意ゲート付きWeb Pixel、Theme App Extensionsをリリース。',
        'WooCommerceからShopifyへの移行やステージングから本番への移行を主導。11,000行のLiquidテーマをReactアイランドへ再構築し、見た目の一致を検証。',
        'GitHub Actionsのパイプラインと、ストア全体を振る舞いベースでテストするPlaywrightハーネス（Shopify固有のチェック40以上）を構築。',
        'DTCブランド59社を調査して70パターンのコンバージョンライブラリにまとめ、エージェンシーのベイズ流A/Bテスト手法を執筆。',
      ],
      metricLabels: { storefronts: 'ストア', modules: 'アプリモジュール', tests: '自動テスト' },
    },
    ellamau: {
      title: 'リードShopifyデベロッパー',
      summary: '米国のファッションブランド向けに、計画からデプロイまでShopifyストアをフル構築。',
      highlights: ['再利用可能なブロックと設定可能なスキーマを持つモジュール式Liquidセクション。', 'モバイルファーストのレスポンシブテンプレート15以上。', '最適化後のLighthouseスコア90以上。'],
      metricLabels: { templates: 'テンプレート', lighthouse: 'Lighthouse' },
    },
    abidata: {
      title: 'フルスタックデベロッパー',
      summary: '企業向けニュースレターを作成・カスタマイズ・配信する社内プラットフォーム。',
      highlights: ['Reactのメールエディタでキャンペーン作成時間を約40%短縮。', '10,000件以上の連絡先と数百の稼働中キャンペーン。', 'REST APIを設計からデプロイまで担当。'],
      metricLabels: { contacts: '連絡先', campaignTime: 'キャンペーン作成時間', users: '社内ユーザー' },
    },
    rh: {
      title: 'フロントエンドデベロッパー',
      summary: '米国の大手小売企業向けに、Adobe AEMからContentfulへのCMS移行。',
      highlights: ['移行を可能にした再利用可能なコンポーネント25以上。', 'アクセシビリティ改善でLighthouseを約70から95以上へ。', 'コンテンツ制作コストを年間約45,000ドル削減。'],
      metricLabels: { components: 'コンポーネント', lighthouse: 'Lighthouse', savings: '削減額' },
    },
    'digitdeck-fe': {
      title: 'フロントエンドデベロッパー（Shopify）',
      summary: 'カスタムLiquidテーマでShopifyストアを構築・最適化。',
      highlights: ['4つ以上のストア向けにカスタムセクション、ブロック、スニペット。', 'UXとチェックアウトの改善でコンバージョンを10〜20%向上。', 'ページ表示を30〜40%高速化。オーガニック流入は20%以上増加。'],
      metricLabels: { conversion: 'コンバージョン', loadTime: '表示速度', organic: 'オーガニック流入' },
    },
    orthofix: {
      title: 'Salesforceデベロッパー',
      summary: '患者と業務のワークフローを支える医療向け社内アプリケーション。',
      highlights: ['50人以上の社内ユーザーが使うLightning Web Components。', '数千件の患者・機器レコードを扱うワークフロー。', '手入力を約20%削減。'],
      metricLabels: { users: 'ユーザー', dataEntry: '手入力' },
    },
    ibox: {
      title: 'フロントエンドReactデベロッパー',
      summary: '米国・中南米市場向けスマートロッカーソリューションの企業サイト。',
      highlights: ['再利用可能なReactコンポーネント20以上、レスポンシブページ10以上。', 'Lighthouse 90以上、表示速度は約35%改善。'],
      metricLabels: { components: 'コンポーネント', pages: 'ページ', lighthouse: 'Lighthouse' },
    },
  },
  roleWork: {
    'ibox-site': 'iBox スマートロッカーのWebサイト',
    'orthofix-apps': 'Orthofix 社内医療アプリ',
    'rh-migration': 'RH のCMS移行（AEM → Contentful）',
    'abidata-newsletters': 'ABI Data ニュースレター基盤',
    'ellamau-storefront': 'Ellamau のShopifyストア',
  },
  stores: {
    'the-gummy-box': { industry: '機能性グミ', tagline: '自社Bundlesモジュールと連携したバンドルビルダー、サブスクリプション、ファーストパーティ計測。', description: 'キットのオファーは、買う人には簡単で、悪用は不可能でなければなりませんでした。Bundlesモジュールがチェックアウト時にShopify Functionでキット価格を計算するため、10%から20%の段階割引は自動で適用され、探すクーポンはありません。サブスクはTreli、全面でファーストパーティ計測。ブランドは各ブロックの働きを把握できます。', factLabels: { ladder: 'キット割引、チェックアウトで自動適用' } },
    'nos-cafe': { industry: 'スペシャルティコーヒー', tagline: 'FramerのデザインをLiquidへ1:1移植。段階割引付きのボックスビルダー。', description: '完成したFramerのデザインを、1ピクセルも失わずにShopifyへ。Liquidへ1:1で移植し、ロースターに必要なボックスビルダーをつくりました。1箱に最大5袋、袋ごとに挽き方とサイズを選べ、袋が増えるほど割引が10%から20%へ上がります。', factLabels: { ladder: 'ボックス割引、袋ごとに上昇' } },
    millennio: { industry: '香水', tagline: 'Reactアイランド上へのFramer移植。計測対象要素260以上。', description: '香水店はFramerのデザインをShopifyで動かし、買い物客が実際に何に触れるかを知りたがっていました。移植はLiquid基盤上のReactアイランドとして動き、カード・レール・CTAのすべてを計測。260以上の要素がOptimizeダッシュボードへ報告されます。', factLabels: { tracked: '計測した顧客接点' } },
    mindfuel: { industry: 'ヌートロピクス', tagline: 'React V2へフル移植し、本番公開。', description: 'DigitdeckテンプレートにReact V2として再構築し、2026年8月20日に本番公開。トップ・商品ページ・診断クイズが1つのコンポーネントライブラリを共有するため、変更は一度のリリースで全体に反映されます。', factLabels: { live: '公開日' } },
    nalua: { industry: 'スキンケア', tagline: '購入オファーと数量別の段階価格、代引きフロー。', description: 'ここでのリスクは「割引に見えるだけのオファー」でした。購入オファーと数量別価格は実際の自動割引に接続し、Releasitの代引きフローはオファー単位で同期。19件中19件が一致しています。', factLabels: { offers: '代引きと同期したオファー' } },
    sebum: { industry: 'スキンケア', tagline: '拡張可能なレビューウォールを備えたV2再構築。', description: 'V2再構築には拡張可能なレビューウォールと商品ページのReactアイランドが含まれます。リポジトリと本番テーマはバイト単位で一致（100%）し、すべての変更はgitから出荷。エディタだけに存在するものはありません。' },
    'valdo-cafe': { industry: 'コーヒー', tagline: 'ステージングストアから本番ストアへ移し、公開。', description: 'ステージングストアで構築し、本番ストアへ移して翌日に公開（2026年7月9〜10日）。小さなテーマと整ったテンプレートで、私がいなくてもクライアントが運用できる状態に。', factLabels: { transfer: '移行から公開まで' } },
    'factores-2x2': { industry: 'サプリメント', tagline: 'FramerからLiquidへ。Web品質スコアを95以上に。', description: 'まずFramerからLiquidへ、次にルート全体のウェブ品質パス。現在トップページはLighthouseモバイルでアクセシビリティ100、SEO 100（2026年9月のラボ計測）。', factLabels: { quality: 'アクセシビリティ・SEO（Lighthouseモバイル、2026年9月）' } },
    pixxiesx: { industry: 'ファッション', tagline: '商品診断クイズ、メタオブジェクト駆動の商品ページ、当日配送。', description: 'サポートより先に商品ページが疑問に答える必要があったサングラスブランド。商品診断クイズ、6種類のメタオブジェクト（ベネフィット、特徴、素材、FAQ、悩み、寸法）で動く商品ページ、当日配送の案内。' },
    'luxe-shine': { industry: 'ビューティー', tagline: 'スクロール連動のビデオヒーロー、計測の後付け。', description: '既存テーマはそのまま。変えたのは「何を報告するか」。スクロール連動のビデオヒーロー、商品ページ画像の全面展開、そして新規構築と同じダッシュボードへ送るための計測の後付け。' },
    atmosfera: { industry: 'パソコン', tagline: '仕入先リストからのカタログ同期、二重価格表示。', description: '仕入先の価格表でカタログが変わるPC小売店。カタログは価格表から12時間ごとに同期し、価格は税込・税抜の両方で表示、仕様はメタフィールドに、バリエーション在庫はミラーリング。', factLabels: { pricing: '表示価格', sync: 'カタログ更新間隔' } },
    'saint-theory': { industry: 'ストリートウェア', tagline: 'カスタムLiquidテーマ。現在も公開中。', description: 'ストリートウェアブランド。2023年に構築したカスタムLiquidテーマが、現在も本番テーマとして稼働中。' },
    peluna: { industry: 'ペットケア', tagline: 'Digitdeckテンプレート上でのリデザインとA/Bテスト。', description: 'Digitdeckテンプレート上でのリデザイン。初日からA/Bテストの環境と商品データ用メタオブジェクトを用意。切り替えまでクライアントのShrineテーマは並行して稼働。', factLabels: { ab: 'A/Bテスト' } },
    'en-amor-a-dos': { industry: 'ジュエリー', tagline: 'Reactアイランド上の独自セクション57個。', description: 'Dawn基盤上のReactアイランドで57のカスタムセクションを構築したジュエリーブランド。クライアントの本番ストアには触れず、QAテーマで準備中。' },
    unik: { industry: 'デニム', tagline: 'カタログの一括i18nを備えた二言語・二通貨ストア。', description: 'バイリンガル・2通貨のストアとして再構築したデニムブランド。カタログはAdmin GraphQL APIで一括翻訳。ビルドはクライアントの本番Dawnより389ファイル先行。', factLabels: { langs: '言語・通貨' } },
    'origen-vital': { industry: 'サプリメント', tagline: 'Framer移植、商品診断クイズ、302件のシードレビュー、プロモLP。', description: 'Framerから移植したサプリメントブランド。商品診断クイズ、写真付きの初期レビュー302件（商品あたり80件以上）、5コレクションのメガメニュー、192本の広告から合成したプロモLP。', factLabels: { reviews: '写真付きレビュー（公開中）', ads: 'LPに変換した広告' } },
    'para-machos': { industry: 'メンズグルーミング', tagline: '新しいDigitdeckテーマを開発中。', description: 'DEVコピー上で新しいDigitdeckテーマを構築中のメンズグルーミングブランド。ローンチまでクライアントの本番テーマは不変。' },
    tierramont: { industry: 'アウトドア', tagline: '本番ストア向けの新テーマを開発中。', description: '本番ストア向けに新テーマを構築中のアウトドアアパレルブランド。クライアントも読める共有ボードで課題単位（現在81件）で追跡。' },
    'alma-de-aviador': { industry: 'アパレル', tagline: 'Framer移植を伴うWooCommerceからShopifyへの移行。', description: 'WooCommerceからShopifyへ移行した航空モチーフのアパレルブランド。FramerのデザインをV2テーマ上の35セクションにコンポーネント化。', factLabels: { migration: 'プラットフォーム移行' } },
    joystaz: { industry: 'デニム', tagline: 'TailwindのLiquidテーマと独自レビューバックエンド。', description: 'デニムブランド。TailwindのLiquidテーマと独自のレビューバックエンド（Express + Prisma）。2025年構築。' },
    'new-urban': { industry: 'ファッション', tagline: '初期のDigitdeckストア。', description: 'ファッションブランド向けの初期Digitdeckストア。2023年構築。' },
    gummind: { industry: 'ウェルネス', tagline: 'スケルトンテーマ上のストア。', description: 'スケルトンテーマ上のウェルネスストア。2025年構築。' },
    rimo: { industry: '小売', tagline: '初期のDigitdeckストア。', description: '初期のDigitdeckストア。2023年構築。' },
  },
  products: {
    'digitdeck-apps': { tagline: '1回のインストールで5つのモジュール', description: '公式Remixスタック上のマルチテナントShopifyアプリ。再入荷通知、バンドル、紹介、レビュー、A/Bテスト。Shopify Functions 2つ、同意ゲート付きWeb Pixel、Theme App Extension。' },
    'digitdeck-platform': { tagline: 'エージェンシーのオペレーティングシステム', description: 'テナント分離、モジュールレジストリ、RBAC、BYO-AIゲートウェイを備えたモジュラーモノリス。app.digitdeck.coで稼働中。' },
    'audit-dashboard': { tagline: 'オフラインで開ける監査レポート', description: '監査データ、ブランドテーマ、スクリーンショットから自己完結型のHTMLダッシュボードを生成。CDNも外部リクエストもなし。' },
    'feedback-portal': { tagline: 'クライアントの要望をGitHub Issuesに', description: 'すべての報告が正しいボード上の標準化されたIssueになる、非公開のマルチクライアントポータル。' },
    track: { tagline: '規約に基づくファーストパーティイベント', description: 'すべてのセクションが従うdata-dd-*契約。OptimizeダッシュボードとA/Bテストモジュールに送られます。' },
  },
  projects: {
    kotodama: { tagline: 'JRPGで学ぶ日本語', description: '間隔反復、リスニング、漢字、読解クエストでゼロからJLPT N1へ。' },
    'autofill-plugin': { tagline: 'ブラウザの自動入力ヘルパー', description: '保存したプロフィールから繰り返しのフォームを入力。' },
    pagui: { tagline: 'OCRによるオンボーディング', description: '銀行の顧客向けにOCRで本人登録。' },
    scorrea: { tagline: 'デベロッパーのポートフォリオ', description: 'シニアソフトウェアデベロッパーのためのAstroサイト。' },
    'dr-hugo': { tagline: '審美歯科のサイト', description: '歯科クリニックのサービス紹介と予約導線。' },
    maxfolio: { tagline: 'このサイト', description: '4つのデザイン言語、1つのコンテンツモデル、3つの言語。' },
  },
  footer: { tagline: '計測に基づくShopifyエンジニアリング。', services: ['Shopifyストア', 'Shopifyアプリ', 'CROとA/Bテスト', 'ストア移行', 'パフォーマンス'], servicesTitle: '提供すること', quickLinks: 'クイックリンク', rights: 'All rights reserved.', stamp: '2026年9月に再構築 · React 19 + Vite · デスクトップでLighthouse 100/100/100/100（ローカル計測）', backToTop: 'トップへ戻る' },
  location: 'コロンビア、メデジン',
}
