import type { PortfolioContent } from './types'

export const ja: PortfolioContent = {
  meta: {
    title: 'Maximiliano Bustamante | CTO & Shopify Tech Lead',
    description:
      'DigitdeckのCTO & Shopify Tech Lead。18以上のShopifyストア、本番稼働中のアプリ群、そしてそれらを届ける仕組み。Shopify CROコンサルティング受付中。',
  },
  hero: {
    eyebrow: 'CTO & Shopify Tech Lead · Digitdeck',
    positioning: '売れるShopifyストアと、それを届ける仕組みをつくっています。',
    lead: '18以上のストア、マルチテナントのアプリ群、そしてリリース前に不具合を捕まえるQAパイプライン。勘ではなく、計測に基づいたShopifyエンジニアリングを提供します。',
    availability: 'Shopify CROコンサルティング・お見積り受付中',
    ctaContact: 'お問い合わせ',
    ctaCv: 'CVをダウンロード',
  },
  stats: {
    storefronts: 'Shopifyストア',
    modules: '本番稼働中のアプリモジュール',
    functions: 'Shopify Functions（WASM）',
    standards: 'エンジニアリング標準',
    tests: '自動テスト',
    brands: 'ブランドのトークンシステム',
  },
  sections: {
    experience: { eyebrow: '経歴', title: '仕事をしてきた', titleAccent: '場所', achievements: '成果', technologies: '技術スタック', visit: 'サイトを見る' },
    shopify: {
      eyebrow: 'Shopifyの実績',
      title: 'ストア、アプリ、',
      titleAccent: 'そしてその裏側のプラットフォーム',
      lead: '18以上のストア。Shopify Functionsで価格計算するバンドル、商品診断クイズ、レビューウォール、2通貨カタログ、FramerやWooCommerceからの移行。開くと事例が見られ、公開中のものは実際のチェックアウトへつながります。',
      tabStores: 'ストア',
      tabProducts: 'アプリとプラットフォーム',
      legacyLabel: '過去の実績',
      visit: 'ストアを見る',
      showAll: '{n}店舗すべてを表示',
      showLess: '表示を減らす',
    },
    gallery: {
      eyebrow: 'ギャラリー',
      title: '売るためにつくる、',
      titleAccent: 'どの画面でも',
      lead: 'ここにあるストアはすべて同じ基準でつくっています。クリックを勝ち取るトップページと、購入を決める商品ページを、お客様が実際に使うスマホで。カーソルを合わせると商品ページに切り替わり、ストアを開くと4枚のキャプチャ、構築の経緯、技術構成が見られます。',
      filterAll: 'すべて',
      filterLive: '公開中',
      filterDev: '開発中',
      viewLabel: '表示',
      viewCarousel: 'カルーセル',
      viewDevices: 'ラップトップ＋スマホ',
      viewPhones: 'スマホのみ',
      open: 'ギャラリーを開く',
      close: '閉じる',
      home: 'トップページ',
      pdp: '商品ページ',
      desktop: 'デスクトップ',
      mobile: 'モバイル',
    },
    projects: { eyebrow: 'プロジェクト', title: '個人的に', titleAccent: 'つくっているもの', view: 'プロジェクトを見る' },
    skills: {
      eyebrow: 'スキル',
      title: '使っている',
      titleAccent: '技術',
      groups: { shopify: 'Shopify', frontend: 'フロントエンド', backend: 'バックエンド', quality: 'テストとCI/CD', cro: 'CROと分析', ai: 'AIエンジニアリング' },
    },
    contact: {
      eyebrow: 'お問い合わせ',
      title: 'ストアにアクセスはある。',
      titleAccent: 'それを、もっと注文に変えましょう。',
      lead: 'Shopifyストアのどこで売上が漏れているか（表示速度、オファー、チェックアウトの摩擦）を見つけ、勘ではなく読み解けるA/Bテストで直します。まず診断、それから修正です。',
      status: 'コンサルティング受付中',
      note: '米国・中南米のブランド向け。1営業日以内にご返信します。',
      cta: 'メッセージを送る',
      email: 'メール',
      phone: '電話',
      location: '所在地',
    },
    explore: { eyebrow: '探索', title: '同じポートフォリオ、4つのデザイン', lead: 'お好みの美学を選んでください。内容は同じです。', viewing: '表示中' },
    caseStudy: { facts: '数字で見る', results: '計測した成果', stack: '技術スタック', visit: 'ストアを見る', prev: '前へ', next: '次へ', timeline: '構築期間', commits: 'コミット', sections: '独自セクション', open: '事例を見る', metrics: 'Lighthouse・モバイル', perf: 'パフォーマンス', a11y: 'アクセシビリティ', bp: 'ベストプラクティス', seo: 'SEO', lcp: 'LCP', measured: 'トップページのラボ計測、{date}、Lighthouse {runs}回の中央値（モバイル、回線シミュレーション）。' },
  },
  badges: { live: '公開中', dev: '開発中', current: '現職', completed: '完了', roles: { built: '構築', maintained: '保守', migrated: '移行' } },
  experience: {
    'digitdeck-cto': {
      title: 'CTO & Shopify テクニカルリード',
      summary: 'Shopifyエージェンシーのエンジニアリング標準を定め、届ける仕組みそのもの（コンポーネントライブラリ、自動QA、CI/CD、AIエージェントのツール）を構築しています。',
      highlights: [
        'Liquid + Reactアイランドのハイブリッド構成を標準化。33コンポーネントの共有ライブラリと14ブランドにまたがるデザイントークン。',
        '公式Remixスタック上にマルチテナントのShopifyアプリ群を構築（A/Bテスト、レビュー、バンドル、紹介、再入荷通知）。加えて800以上の自動テストを備えたサブスクリプション課金エンジン。',
        'WASMにコンパイルしたShopify Functions、同意ゲート付きWeb Pixel、Theme App Extensionsをリリース。',
        'WooCommerceからShopifyへの移行やステージングから本番への移行を主導。11,000行のLiquidテーマをReactアイランドへ再構築し、見た目の一致を検証。',
        'GitHub Actionsのパイプラインと、ストア全体を振る舞いベースでテストするPlaywrightハーネス（Shopify固有のチェック40以上）を構築。',
        'DTCブランド59社を調査して70パターンのコンバージョンライブラリにまとめ、エージェンシーのベイズ流A/Bテスト手法を執筆。',
      ],
      metricLabels: { storefronts: 'ストア', modules: 'アプリモジュール', tests: '自動テスト' },
    },
    ellamau: {
      title: 'リードShopifyデベロッパー',
      summary: '米国のファッションブランド向けに、計画からデプロイまでShopifyストアをフル構築。',
      highlights: ['再利用可能なブロックと設定可能なスキーマを持つモジュール式Liquidセクション。', 'モバイルファーストのレスポンシブテンプレート15以上。', '最適化後のLighthouseスコア90以上。'],
      metricLabels: { templates: 'テンプレート', lighthouse: 'Lighthouse' },
    },
    abidata: {
      title: 'フルスタックデベロッパー',
      summary: '企業向けニュースレターを作成・カスタマイズ・配信する社内プラットフォーム。',
      highlights: ['Reactのメールエディタでキャンペーン作成時間を約40%短縮。', '10,000件以上の連絡先と数百の稼働中キャンペーン。', 'REST APIを設計からデプロイまで担当。'],
      metricLabels: { contacts: '連絡先', campaignTime: 'キャンペーン作成時間', users: '社内ユーザー' },
    },
    rh: {
      title: 'フロントエンドデベロッパー',
      summary: '米国の大手小売企業向けに、Adobe AEMからContentfulへのCMS移行。',
      highlights: ['移行を可能にした再利用可能なコンポーネント25以上。', 'アクセシビリティ改善でLighthouseを約70から95以上へ。', 'コンテンツ制作コストを年間約45,000ドル削減。'],
      metricLabels: { components: 'コンポーネント', lighthouse: 'Lighthouse', savings: '削減額' },
    },
    'digitdeck-fe': {
      title: 'フロントエンドデベロッパー（Shopify）',
      summary: 'カスタムLiquidテーマでShopifyストアを構築・最適化。',
      highlights: ['4つ以上のストア向けにカスタムセクション、ブロック、スニペット。', 'UXとチェックアウトの改善でコンバージョンを10〜20%向上。', 'ページ表示を30〜40%高速化。オーガニック流入は20%以上増加。'],
      metricLabels: { conversion: 'コンバージョン', loadTime: '表示速度', organic: 'オーガニック流入' },
    },
    orthofix: {
      title: 'Salesforceデベロッパー',
      summary: '患者と業務のワークフローを支える医療向け社内アプリケーション。',
      highlights: ['50人以上の社内ユーザーが使うLightning Web Components。', '数千件の患者・機器レコードを扱うワークフロー。', '手入力を約20%削減。'],
      metricLabels: { users: 'ユーザー', dataEntry: '手入力' },
    },
    ibox: {
      title: 'フロントエンドReactデベロッパー',
      summary: '米国・中南米市場向けスマートロッカーソリューションの企業サイト。',
      highlights: ['再利用可能なReactコンポーネント20以上、レスポンシブページ10以上。', 'Lighthouse 90以上、表示速度は約35%改善。'],
      metricLabels: { components: 'コンポーネント', pages: 'ページ', lighthouse: 'Lighthouse' },
    },
  },
  stores: {
    'the-gummy-box': { industry: '機能性グミ', tagline: '自社Bundlesモジュールと連携したバンドルビルダー、サブスクリプション、ファーストパーティ計測。', description: '機能性グミのブランド。Digitdeckテンプレート上に、自社Bundlesモジュールと連携したキットビルダーを実装。割引はクーポンではなくShopify Functionが計算します。サブスクはTreli、全面でファーストパーティ計測。', factLabels: { ladder: '段階割引', modules: '連携したDigitdeckモジュール' } },
    'nos-cafe': { industry: 'スペシャルティコーヒー', tagline: 'FramerのデザインをLiquidへ1:1移植。段階割引付きのボックスビルダー。', description: 'スペシャルティコーヒーのロースター。FramerのデザインをLiquidへ1:1移植。ボックスビルダーで最大5袋を組み合わせ、袋ごとに挽き方とサイズを選べ、袋数に応じて割引が上がります。', factLabels: { ladder: '段階割引', bags: '1箱あたりの袋数' } },
    millennio: { industry: '香水', tagline: 'Reactアイランド上へのFramer移植。計測対象要素260以上。', description: 'コロンビアの香水店。Liquid基盤の上にReactアイランドとしてFramerから移植。カード・レール・CTAのすべてを計測し、260以上の要素をOptimizeダッシュボードへ送ります。', factLabels: { tracked: '計測対象要素（data-dd-*）' } },
    mindfuel: { industry: 'ヌートロピクス', tagline: 'React V2へフル移植し、本番公開。', description: 'ヌートロピクスのブランド。DigitdeckテンプレートにReact V2として再構築し、2026年8月に本番公開。トップ・商品ページ・診断クイズが1つのコンポーネントライブラリを共有。', factLabels: { live: '本番公開' } },
    nalua: { industry: 'スキンケア', tagline: '購入オファーと数量別の段階価格、代引きフロー。', description: 'スキンケアブランド。Digitdeckテーマ上で購入オファーと数量別価格を実際の自動割引に接続し、Releasitの代引きをオファー単位で同期。', factLabels: { offers: '同期したReleasitオファー' } },
    sebum: { industry: 'スキンケア', tagline: '拡張可能なレビューウォールを備えたV2再構築。', description: 'スキンケアのV2再構築。拡張可能なレビューウォールと商品ページのReactアイランド。リポジトリと本番テーマはバイト単位で一致し、すべての変更はgitから出荷。', factLabels: { parity: 'リポジトリ ↔ 本番の一致率' } },
    'valdo-cafe': { industry: 'コーヒー', tagline: 'ステージングストアから本番ストアへ移し、公開。', description: 'コーヒーブランド。ステージングストアで構築し、本番ストアへ移して翌日に公開。小さなテーマと整ったテンプレートで、クライアントが自走できる状態に。', factLabels: { transfer: 'ストア移行 → 公開' } },
    'factores-2x2': { industry: 'サプリメント', tagline: 'FramerからLiquidへ。Web品質スコアを95以上に。', description: 'サプリメントブランド。FramerからLiquidへ移植し、全ルートでWeb品質の改善を重ねて、速度・アクセシビリティ・SEOを95以上に。', factLabels: { quality: 'Web品質（速度・a11y・SEO）' } },
    pixxiesx: { industry: 'ファッション', tagline: '商品診断クイズ、メタオブジェクト駆動の商品ページ、当日配送。', description: 'サングラスブランド。商品診断クイズ、メタオブジェクト駆動の商品ページ（効能・特徴・素材・FAQ・悩み・サイズ）、当日配送の訴求。', factLabels: { metaobjects: '商品ページのメタオブジェクト種別' } },
    'luxe-shine': { industry: 'ビューティー', tagline: 'スクロール連動のビデオヒーロー、計測の後付け。', description: 'ビューティーブランド。スクロール連動のビデオヒーロー、商品ページ画像の全面展開、既存テーマに計測を後付けして新規ビルドと同じダッシュボードへ。', factLabels: { hero: 'ヒーロー' } },
    atmosfera: { industry: 'パソコン', tagline: '仕入先リストからのカタログ同期、二重価格表示。', description: 'パソコン販売店。仕入先の価格表からカタログを同期し、二重価格（税込・税抜）、仕様メタフィールド、バリアント単位の在庫ミラーを実装。', factLabels: { pricing: '価格モデル', sync: '在庫の再同期サイクル' } },
    'saint-theory': { industry: 'ストリートウェア', tagline: 'カスタムLiquidテーマ。現在も公開中。', description: 'ストリートウェアブランド。2023年に構築したカスタムLiquidテーマが、現在も本番テーマとして稼働中。' },
    peluna: { industry: 'ペットケア', tagline: 'Digitdeckテンプレート上でのリデザインとA/Bテスト。', description: 'ペットケアブランド。Digitdeckテンプレート上でリデザインし、A/Bテスト基盤と商品データのメタオブジェクトを整備。クライアントのShrineテーマも並行して保守。', factLabels: { ab: '実験基盤' } },
    'en-amor-a-dos': { industry: 'ジュエリー', tagline: 'Reactアイランド上の独自セクション57個。', description: 'ジュエリーブランド。Dawn基盤の上にReactアイランドで57の独自セクションを構築。クライアントの本番はそのままに、QAテーマで段階的に展開。', factLabels: { custom: '独自セクション数' } },
    unik: { industry: 'デニム', tagline: 'カタログの一括i18nを備えた二言語・二通貨ストア。', description: 'デニムブランド。Admin GraphQL APIによるカタログの一括i18nで、二言語・二通貨のストアとして再構築。ビルドはクライアント本番のDawnより389ファイル先行。', factLabels: { langs: '言語 · 通貨', ahead: 'クライアント本番より先行するファイル数' } },
    'origen-vital': { industry: 'サプリメント', tagline: 'Framer移植、商品診断クイズ、302件のシードレビュー、プロモLP。', description: 'サプリメントブランド。Framerから移植し、商品診断クイズ、写真付きの302件のシードレビュー、5コレクションのメガメニュー、192本の広告から集約したプロモLPを実装。', factLabels: { reviews: 'シードしたレビュー（商品あたり80以上）', ads: 'プロモLPに集約した広告数', collections: 'コレクション + メガメニュー' } },
    'para-machos': { industry: 'メンズグルーミング', tagline: '新しいDigitdeckテーマを開発中。', description: 'メンズグルーミングブランド。クライアントの本番テーマには触れず、DEVコピー上で新しいDigitdeckテーマを開発中。' },
    tierramont: { industry: 'アウトドア', tagline: '本番ストア向けの新テーマを開発中。', description: 'アウトドアアパレルブランド。本番ストア向けの新テーマを開発中。共有ボードでIssue単位に進行を管理。', factLabels: { issues: 'ボード上のIssue数' } },
    'alma-de-aviador': { industry: 'アパレル', tagline: 'Framer移植を伴うWooCommerceからShopifyへの移行。', description: '航空をテーマにしたアパレルブランド。WooCommerceからShopifyへ移行し、Framerのデザインを35セクションにコンポーネント化してV2テーマへ。', factLabels: { framer: 'コンポーネント化したFramerセクション', migration: '移行' } },
    joystaz: { industry: 'デニム', tagline: 'TailwindのLiquidテーマと独自レビューバックエンド。', description: 'デニムブランド。TailwindのLiquidテーマと独自のレビューバックエンド（Express + Prisma）。2025年構築。', factLabels: { reviews: 'シードしたレビュー（商品あたり80以上）' } },
    'new-urban': { industry: 'ファッション', tagline: '初期のDigitdeckストア。', description: 'ファッションブランド向けの初期Digitdeckストア。2023年構築。' },
    gummind: { industry: 'ウェルネス', tagline: 'スケルトンテーマ上のストア。', description: 'スケルトンテーマ上のウェルネスストア。2025年構築。' },
    rimo: { industry: '小売', tagline: '初期のDigitdeckストア。', description: '初期のDigitdeckストア。2023年構築。' },
  },
  products: {
    'digitdeck-apps': { tagline: '1回のインストールで5つのモジュール', description: '公式Remixスタック上のマルチテナントShopifyアプリ。再入荷通知、バンドル、紹介、レビュー、A/Bテスト。Shopify Functions 2つ、同意ゲート付きWeb Pixel、Theme App Extension。' },
    'digitdeck-platform': { tagline: 'エージェンシーのオペレーティングシステム', description: 'テナント分離、モジュールレジストリ、RBAC、BYO-AIゲートウェイを備えたモジュラーモノリス。app.digitdeck.coで稼働中。' },
    'audit-dashboard': { tagline: 'オフラインで開ける監査レポート', description: '監査データ、ブランドテーマ、スクリーンショットから自己完結型のHTMLダッシュボードを生成。CDNも外部リクエストもなし。' },
    'feedback-portal': { tagline: 'クライアントの要望をGitHub Issuesに', description: 'すべての報告が正しいボード上の標準化されたIssueになる、非公開のマルチクライアントポータル。' },
    track: { tagline: '規約に基づくファーストパーティイベント', description: 'すべてのセクションが従うdata-dd-*契約。OptimizeダッシュボードとA/Bテストモジュールに送られます。' },
  },
  projects: {
    kotodama: { tagline: 'JRPGで学ぶ日本語', description: '間隔反復、リスニング、漢字、読解クエストでゼロからJLPT N1へ。' },
    'autofill-plugin': { tagline: 'ブラウザの自動入力ヘルパー', description: '保存したプロフィールから繰り返しのフォームを入力。' },
    pagui: { tagline: 'OCRによるオンボーディング', description: '銀行の顧客向けにOCRで本人登録。' },
    scorrea: { tagline: 'デベロッパーのポートフォリオ', description: 'シニアソフトウェアデベロッパーのためのAstroサイト。' },
    'dr-hugo': { tagline: '審美歯科のサイト', description: '歯科クリニックのサービス紹介と予約導線。' },
    maxfolio: { tagline: 'このサイト', description: '4つのデザイン言語、1つのコンテンツモデル、3つの言語。' },
  },
  footer: { tagline: '計測に基づくShopifyエンジニアリング。', services: ['Shopifyストア', 'Shopifyアプリ', 'CROとA/Bテスト', 'ストア移行', 'パフォーマンス'], servicesTitle: '提供すること', quickLinks: 'クイックリンク', rights: 'All rights reserved.' },
  location: 'コロンビア、メデジン',
}
