import type { PortfolioContent } from './types'

export const ja: PortfolioContent = {
  meta: {
    title: 'Maximiliano Bustamante | CTO & Shopify Tech Lead',
    description:
      'DigitdeckのCTO & Shopify Tech Lead。18以上のShopifyストア、本番稼働中のアプリ群、そしてそれらを届ける仕組み。Shopify CROコンサルティング受付中。',
  },
  hero: {
    eyebrow: 'CTO & Shopify Tech Lead · Digitdeck',
    positioning: '売れるShopifyストアと、それを届ける仕組みをつくっています。',
    lead: '18以上のストア、マルチテナントのアプリ群、そしてリリース前に不具合を捕まえるQAパイプライン。勘ではなく、計測に基づいたShopifyエンジニアリングを提供します。',
    availability: 'Shopify CROコンサルティング・お見積り受付中',
    ctaContact: 'お問い合わせ',
    ctaCv: 'CVをダウンロード',
  },
  stats: {
    storefronts: 'Shopifyストア',
    modules: '本番稼働中のアプリモジュール',
    functions: 'Shopify Functions（WASM）',
    standards: 'エンジニアリング標準',
    tests: '自動テスト',
    brands: 'ブランドのトークンシステム',
  },
  sections: {
    experience: { eyebrow: '経歴', title: '仕事をしてきた', titleAccent: '場所', achievements: '成果', technologies: '技術スタック', visit: 'サイトを見る' },
    shopify: {
      eyebrow: 'Shopifyの実績',
      title: 'ストア、アプリ、',
      titleAccent: 'そしてその裏側のプラットフォーム',
      lead: '以下のストアはすべて、私が書いたかレビューしたコードで動いています。公開中のものは実際のストアへリンクし、残りはクライアント側で進行中のビルドです。',
      tabStores: 'ストア',
      tabProducts: 'アプリとプラットフォーム',
      legacyLabel: '過去の実績',
      visit: 'ストアを見る',
    },
    gallery: {
      eyebrow: 'ギャラリー',
      title: '同じフレームで、',
      titleAccent: 'すべてのストアを',
      lead: 'トップページと商品ページ、デスクトップとモバイル。すべてのプロジェクトを同じ方法で撮影しているので、公平に比較できます。',
      filterAll: 'すべて',
      filterLive: '公開中',
      filterDev: '開発中',
      open: 'ギャラリーを開く',
      close: '閉じる',
      home: 'トップページ',
      pdp: '商品ページ',
      desktop: 'デスクトップ',
      mobile: 'モバイル',
    },
    projects: { eyebrow: 'プロジェクト', title: '個人的に', titleAccent: 'つくっているもの', view: 'プロジェクトを見る' },
    skills: {
      eyebrow: 'スキル',
      title: '使っている',
      titleAccent: '技術',
      groups: { shopify: 'Shopify', frontend: 'フロントエンド', backend: 'バックエンド', quality: 'テストとCI/CD', cro: 'CROと分析', ai: 'AIエンジニアリング' },
    },
    contact: {
      eyebrow: 'お問い合わせ',
      title: 'ストアにアクセスはある。',
      titleAccent: 'それを、もっと注文に変えましょう。',
      lead: 'Shopifyストアのどこで売上が漏れているか（表示速度、オファー、チェックアウトの摩擦）を見つけ、勘ではなく読み解けるA/Bテストで直します。まず診断、それから修正です。',
      status: 'コンサルティング受付中',
      note: '米国・中南米のブランド向け。1営業日以内にご返信します。',
      cta: 'メッセージを送る',
      email: 'メール',
      phone: '電話',
      location: '所在地',
    },
    explore: { eyebrow: '探索', title: '同じポートフォリオ、4つのデザイン', lead: 'お好みの美学を選んでください。内容は同じです。', viewing: '表示中' },
  },
  badges: { live: '公開中', dev: '開発中', current: '現職', completed: '完了', roles: { built: '構築', maintained: '保守', migrated: '移行' } },
  experience: {
    'digitdeck-cto': {
      title: 'CTO & Shopify テクニカルリード',
      summary: 'Shopifyエージェンシーのエンジニアリング標準を定め、届ける仕組みそのもの（コンポーネントライブラリ、自動QA、CI/CD、AIエージェントのツール）を構築しています。',
      highlights: [
        'Liquid + Reactアイランドのハイブリッド構成を標準化。33コンポーネントの共有ライブラリと14ブランドにまたがるデザイントークン。',
        '公式Remixスタック上にマルチテナントのShopifyアプリ群を構築（A/Bテスト、レビュー、バンドル、紹介、再入荷通知）。加えて800以上の自動テストを備えたサブスクリプション課金エンジン。',
        'WASMにコンパイルしたShopify Functions、同意ゲート付きWeb Pixel、Theme App Extensionsをリリース。',
        'WooCommerceからShopifyへの移行やステージングから本番への移行を主導。11,000行のLiquidテーマをReactアイランドへ再構築し、見た目の一致を検証。',
        'GitHub Actionsのパイプラインと、ストア全体を振る舞いベースでテストするPlaywrightハーネス（Shopify固有のチェック40以上）を構築。',
        'DTCブランド59社を調査して70パターンのコンバージョンライブラリにまとめ、エージェンシーのベイズ流A/Bテスト手法を執筆。',
      ],
      metricLabels: { storefronts: 'ストア', modules: 'アプリモジュール', tests: '自動テスト' },
    },
    ellamau: {
      title: 'リードShopifyデベロッパー',
      summary: '米国のファッションブランド向けに、計画からデプロイまでShopifyストアをフル構築。',
      highlights: ['再利用可能なブロックと設定可能なスキーマを持つモジュール式Liquidセクション。', 'モバイルファーストのレスポンシブテンプレート15以上。', '最適化後のLighthouseスコア90以上。'],
      metricLabels: { templates: 'テンプレート', lighthouse: 'Lighthouse' },
    },
    abidata: {
      title: 'フルスタックデベロッパー',
      summary: '企業向けニュースレターを作成・カスタマイズ・配信する社内プラットフォーム。',
      highlights: ['Reactのメールエディタでキャンペーン作成時間を約40%短縮。', '10,000件以上の連絡先と数百の稼働中キャンペーン。', 'REST APIを設計からデプロイまで担当。'],
      metricLabels: { contacts: '連絡先', campaignTime: 'キャンペーン作成時間', users: '社内ユーザー' },
    },
    rh: {
      title: 'フロントエンドデベロッパー',
      summary: '米国の大手小売企業向けに、Adobe AEMからContentfulへのCMS移行。',
      highlights: ['移行を可能にした再利用可能なコンポーネント25以上。', 'アクセシビリティ改善でLighthouseを約70から95以上へ。', 'コンテンツ制作コストを年間約45,000ドル削減。'],
      metricLabels: { components: 'コンポーネント', lighthouse: 'Lighthouse', savings: '削減額' },
    },
    'digitdeck-fe': {
      title: 'フロントエンドデベロッパー（Shopify）',
      summary: 'カスタムLiquidテーマでShopifyストアを構築・最適化。',
      highlights: ['4つ以上のストア向けにカスタムセクション、ブロック、スニペット。', 'UXとチェックアウトの改善でコンバージョンを10〜20%向上。', 'ページ表示を30〜40%高速化。オーガニック流入は20%以上増加。'],
      metricLabels: { conversion: 'コンバージョン', loadTime: '表示速度', organic: 'オーガニック流入' },
    },
    orthofix: {
      title: 'Salesforceデベロッパー',
      summary: '患者と業務のワークフローを支える医療向け社内アプリケーション。',
      highlights: ['50人以上の社内ユーザーが使うLightning Web Components。', '数千件の患者・機器レコードを扱うワークフロー。', '手入力を約20%削減。'],
      metricLabels: { users: 'ユーザー', dataEntry: '手入力' },
    },
    ibox: {
      title: 'フロントエンドReactデベロッパー',
      summary: '米国・中南米市場向けスマートロッカーソリューションの企業サイト。',
      highlights: ['再利用可能なReactコンポーネント20以上、レスポンシブページ10以上。', 'Lighthouse 90以上、表示速度は約35%改善。'],
      metricLabels: { components: 'コンポーネント', pages: 'ページ', lighthouse: 'Lighthouse' },
    },
  },
  stores: {
    'the-gummy-box': { industry: '機能性グミ', tagline: '自社Bundlesモジュールと連携したバンドルビルダー、サブスクリプション、ファーストパーティ計測。' },
    'nos-cafe': { industry: 'スペシャルティコーヒー', tagline: 'FramerのデザインをLiquidへ1:1移植。段階割引付きのボックスビルダー。' },
    millennio: { industry: '香水', tagline: 'Reactアイランド上へのFramer移植。計測対象要素260以上。' },
    mindfuel: { industry: 'ヌートロピクス', tagline: 'React V2へフル移植し、本番公開。' },
    nalua: { industry: 'スキンケア', tagline: '購入オファーと数量別の段階価格、代引きフロー。' },
    sebum: { industry: 'スキンケア', tagline: '拡張可能なレビューウォールを備えたV2再構築。' },
    'valdo-cafe': { industry: 'コーヒー', tagline: 'ステージングストアから本番ストアへ移し、公開。' },
    'factores-2x2': { industry: 'サプリメント', tagline: 'FramerからLiquidへ。Web品質スコアを95以上に。' },
    pixxiesx: { industry: 'ファッション', tagline: '商品診断クイズ、メタオブジェクト駆動の商品ページ、当日配送。' },
    'luxe-shine': { industry: 'ビューティー', tagline: 'スクロール連動のビデオヒーロー、計測の後付け。' },
    atmosfera: { industry: 'パソコン', tagline: '仕入先リストからのカタログ同期、二重価格表示。' },
    'saint-theory': { industry: 'ストリートウェア', tagline: 'カスタムLiquidテーマ。現在も公開中。' },
    peluna: { industry: 'ペットケア', tagline: 'Digitdeckテンプレート上でのリデザインとA/Bテスト。' },
    'en-amor-a-dos': { industry: 'ジュエリー', tagline: 'Reactアイランド上の独自セクション57個。' },
    unik: { industry: 'デニム', tagline: 'カタログの一括i18nを備えた二言語・二通貨ストア。' },
    'origen-vital': { industry: 'サプリメント', tagline: 'Framer移植、商品診断クイズ、302件のシードレビュー、プロモLP。' },
    'para-machos': { industry: 'メンズグルーミング', tagline: '新しいDigitdeckテーマを開発中。' },
    tierramont: { industry: 'アウトドア', tagline: '本番ストア向けの新テーマを開発中。' },
    'alma-de-aviador': { industry: 'アパレル', tagline: 'Framer移植を伴うWooCommerceからShopifyへの移行。' },
    joystaz: { industry: 'デニム', tagline: 'TailwindのLiquidテーマと独自レビューバックエンド。' },
    'new-urban': { industry: 'ファッション', tagline: '初期のDigitdeckストア。' },
    gummind: { industry: 'ウェルネス', tagline: 'スケルトンテーマ上のストア。' },
    rimo: { industry: '小売', tagline: '初期のDigitdeckストア。' },
  },
  products: {
    'digitdeck-apps': { tagline: '1回のインストールで5つのモジュール', description: '公式Remixスタック上のマルチテナントShopifyアプリ。再入荷通知、バンドル、紹介、レビュー、A/Bテスト。Shopify Functions 2つ、同意ゲート付きWeb Pixel、Theme App Extension。' },
    'digitdeck-platform': { tagline: 'エージェンシーのオペレーティングシステム', description: 'テナント分離、モジュールレジストリ、RBAC、BYO-AIゲートウェイを備えたモジュラーモノリス。app.digitdeck.coで稼働中。' },
    'audit-dashboard': { tagline: 'オフラインで開ける監査レポート', description: '監査データ、ブランドテーマ、スクリーンショットから自己完結型のHTMLダッシュボードを生成。CDNも外部リクエストもなし。' },
    'feedback-portal': { tagline: 'クライアントの要望をGitHub Issuesに', description: 'すべての報告が正しいボード上の標準化されたIssueになる、非公開のマルチクライアントポータル。' },
    track: { tagline: '規約に基づくファーストパーティイベント', description: 'すべてのセクションが従うdata-dd-*契約。OptimizeダッシュボードとA/Bテストモジュールに送られます。' },
  },
  projects: {
    kotodama: { tagline: 'JRPGで学ぶ日本語', description: '間隔反復、リスニング、漢字、読解クエストでゼロからJLPT N1へ。' },
    peptidos: { tagline: 'ヘッドレスコマース、クリニカルなデザイン', description: '研究用ペプチドブランド向けの、ガラスとグレースケールのミニマルなストア。' },
    'will-you': { tagline: '小さなイエス・ノーのサイト', description: '週末につくったもの。' },
    'fast-resoluciones': { tagline: 'PDFからExcelへ、自動で', description: '決議書PDFからユーザーとIDを抽出し、スプレッドシートに入力。' },
    'autofill-plugin': { tagline: 'ブラウザの自動入力ヘルパー', description: '保存したプロフィールから繰り返しのフォームを入力。' },
    pagui: { tagline: 'OCRによるオンボーディング', description: '銀行の顧客向けにOCRで本人登録。' },
    scorrea: { tagline: 'デベロッパーのポートフォリオ', description: 'シニアソフトウェアデベロッパーのためのAstroサイト。' },
    'dr-hugo': { tagline: '審美歯科のサイト', description: '歯科クリニックのサービス紹介と予約導線。' },
    maxfolio: { tagline: 'このサイト', description: '4つのデザイン言語、1つのコンテンツモデル、3つの言語。' },
  },
  footer: { tagline: '計測に基づくShopifyエンジニアリング。', services: ['Shopifyストア', 'Shopifyアプリ', 'CROとA/Bテスト', 'ストア移行', 'パフォーマンス'], servicesTitle: '提供すること', quickLinks: 'クイックリンク', rights: 'All rights reserved.' },
  location: 'コロンビア、メデジン',
}
