import { useLanguage } from '../../context/LanguageContext'
import type { ObraKind } from '../data'
import { MOTIVOS, type Motivo } from '../shared/contacto'

// Etiquetas de interfaz de la dirección Maison (es · en · ja). Los textos de contenido (cargos, cifras, FAQ, proceso) vienen de
// useV5(); aquí vive la interfaz y UNA frase por pieza escrita en los términos del dueño de la tienda (`pies`), armada solo con lo
// que la descripción del registro ya afirma: ni cifras nuevas, ni plazos, ni medios de pago, ni garantías. El asunto del correo
// que llega a Max va siempre en inglés.
const motivos = (l: 'es' | 'en') => Object.fromEntries(Object.entries(MOTIVOS).map(([k, v]) => [k, v[l]])) as Record<Motivo, string>

const es = {
  saltar: 'Saltar al contenido',
  principal: 'Principal',
  nav: { inicio: 'Inicio', obra: 'Obra', trayectoria: 'Trayectoria', contacto: 'Contacto' },
  idioma: 'Idioma',
  menu: { abrir: 'Menú', cerrar: 'Cerrar' },
  escribeme: 'Escríbeme',
  cv: 'Descargar CV',
  marca: 'Maximiliano Bustamante',
  tiendasConstruidas: (n: string) => `${n} tiendas construidas`,
  verObra: 'Ver toda la obra',
  verFicha: 'Ver la ficha',
  verTrayectoria: 'Ver la trayectoria',
  inicio: {
    dipticoSr: 'Obra reciente',
    obraEtq: 'Obra destacada',
    obraTit: 'Obra reciente',
    coleccionesEtq: 'Colecciones',
    coleccionesTit: 'Un rubro, una colección',
    de: 'de',
    casaEtq: 'La casa',
    recibesEtq: 'Lo que recibes',
    recibesTit: 'Tres cosas que quedan en tus manos',
    casoEtq: 'Un caso, completo',
  },
  obra: {
    h1: 'Obra',
    lead: 'Tiendas, productos y proyectos, cada pieza con su historia.',
    secciones: 'Secciones de la obra',
    tiendas: 'Tiendas',
    mas: 'Más trabajo',
    masNota: 'Productos propios y proyectos personales.',
    anterior: 'Trabajo anterior',
    colecciones: { bienestar: 'Bienestar y suplementos', cafe: 'Café', moda: 'Moda y denim', belleza: 'Belleza y cuidado', joyeria: 'Perfumería y joyería', otros: 'Mascotas y tecnología' },
    coleccion: 'Colección',
    cuenta: (n: number) => `${n} ${n === 1 ? 'pieza' : 'piezas'}`,
  },
  kinds: { store: 'Tienda', product: 'Producto', role: 'Entregable', personal: 'Proyecto personal' } satisfies Record<ObraKind, string>,
  ficha: {
    volver: 'Obra',
    visitar: 'Visitar el sitio',
    verCodigo: 'Ver el código',
    tabs: 'Secciones de la ficha',
    historia: 'Historia',
    hechos: 'Hechos',
    oficio: 'Oficio',
    encargo: 'El encargo',
    construi: 'Lo que construí',
    alcance: 'Alcance',
    fuente: 'Fuente: el proyecto.',
    enConstruccion: 'En construcción',
    home: 'Inicio',
    pdp: 'Producto',
    rubro: 'Rubro',
    rol: 'Rol',
    anio: 'Año',
    periodo: 'Periodo',
    empleo: 'Empleo',
    pila: 'Pila',
    catalogo: 'Catálogo',
    catalogoNota: (f: string) => `Catálogo público de la tienda, ${f}.`,
    codigo: 'Código',
    movil: 'móvil',
    escritorio: 'escritorio',
    medidasMovil: (m: string, e: string, f: string) => `Lighthouse (rendimiento · accesibilidad · SEO): móvil ${m}, escritorio ${e}. Medición local de ${f}.`,
    medidasGit: (c: number, s: number, f: string) => `Repositorio: ${c} commits y ${s} secciones propias, ${f}.`,
    capturas: 'Las pantallas',
    capturasNota: 'Capturas reales de la tienda, sin retoque.',
    siguiente: 'Siguiente pieza',
    noExiste: 'Esa obra no existe',
    volverObra: 'Volver a la obra',
    sinCaptura: 'Sin capturas públicas',
    pantalla: (v: string, vp: string) => `${v}, ${vp}`,
  },
  tray: {
    h1: 'Trayectoria',
    temporadas: 'Año por año',
    eyebrow: (n: number, desde: string) => `${n} cargos · desde ${desde}`,
    cv: 'Descargar el CV en PDF',
    empleoTipo: { 'full-time': 'Tiempo completo', 'part-time': 'Medio tiempo', contract: 'Por contrato' } as Record<string, string>,
    mas: 'Y más en la obra',
    cargosDelAnio: 'Cargos',
    verTodo: 'Ver el cargo completo',
    verMenos: 'Ver menos',
    entregables: 'Entregables',
  },
  contacto: {
    h1: 'Contacto',
    form: 'Pedir la revisión',
    motivo: 'Cómo quieres empezar',
    tienda: 'La URL de tu tienda',
    tiendaEj: 'tutienda.com',
    correo: 'Tu correo',
    correoEj: 'tu@tienda.com',
    motivos: motivos('es'),
    enviar: { revision: 'Pedir la revisión', proyecto: 'Contar el proyecto', continuo: 'Hablar del trabajo continuo', empleo: 'Escribir por la vacante' },
    enviando: 'Enviando',
    ok: 'Recibido. Te escribiré al correo que dejaste.',
    error: 'No se pudo enviar. Se abrió tu correo con el mensaje listo.',
    falta: 'Escribe un correo válido.',
    faltaTienda: 'Escribe la URL de tu tienda.',
    canales: 'Canales',
    canalCorreo: 'Correo',
    copiar: 'Copiar',
    copiado: 'Copiado',
    whatsapp: 'WhatsApp',
    waTexto: 'Hola Max, quiero la revisión gratis de 20 minutos de mi tienda.',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    cvCanal: 'CV en PDF',
    faq: 'Antes de escribir',
  },
  pie: {
    nav: 'Pie de página',
    frase: 'Ingeniería Shopify, medida.',
    medellin: 'Medellín, Colombia',
    hora: (h: string) => `${h} hora local`,
    arriba: 'Volver arriba',
    derechos: '© 2026 Maximiliano Bustamante',
  },
  pies: {
    'the-gummy-box': 'Armador de kits con descuento del 10 % al 20 % que se aplica solo.',
    'nos-cafe': 'Armador de cajas: el descuento sube del 10 % al 20 % al llenarla.',
    millennio: 'El diseño de Framer, vivo en Shopify y con 260+ elementos medidos.',
    mindfuel: 'Home, producto y quiz en una sola librería de componentes.',
    nalua: 'Ofertas y niveles por cantidad ligados a descuentos reales.',
    sebum: 'Un muro de reseñas extensible en la página de producto.',
    'valdo-cafe': 'Del staging a la tienda real, lista para que el cliente la opere.',
    'factores-2x2': 'Del diseño de Framer a Liquid, con pasada de calidad web.',
    pixxiesx: 'Quiz de producto y página de producto guiada por metaobjetos.',
    'luxe-shine': 'Hero de video con el scroll y tracking para medir la tienda.',
    atmosfera: 'Catálogo que se actualiza solo desde las listas del proveedor.',
    'saint-theory': 'Tema Liquid a medida de 2023, todavía el publicado hoy.',
    peluna: 'Rediseño con pruebas A/B desde el primer día.',
    'en-amor-a-dos': '57 secciones a medida para una marca de joyería.',
    unik: 'Tienda bilingüe, en dos monedas y con catálogo traducido en bloque.',
    'origen-vital': 'Port de Framer con quiz, mega menú y landings de promoción.',
    'para-machos': 'Tema nuevo en construcción; la tienda en vivo sigue intacta.',
    tierramont: 'Tema nuevo para la tienda real, seguido issue por issue.',
    'alma-de-aviador': 'De WooCommerce a Shopify, con el diseño de Framer en 35 secciones.',
  } as Record<string, string>,
}

const en: typeof es = {
  saltar: 'Skip to content',
  principal: 'Main',
  nav: { inicio: 'Home', obra: 'Work', trayectoria: 'Career', contacto: 'Contact' },
  idioma: 'Language',
  menu: { abrir: 'Menu', cerrar: 'Close' },
  escribeme: 'Write to me',
  cv: 'Download CV',
  marca: 'Maximiliano Bustamante',
  tiendasConstruidas: (n: string) => `${n} stores built`,
  verObra: 'See all the work',
  verFicha: 'See the piece',
  verTrayectoria: 'See the career',
  inicio: {
    dipticoSr: 'Recent work',
    obraEtq: 'Featured work',
    obraTit: 'Recent work',
    coleccionesEtq: 'Collections',
    coleccionesTit: 'One sector, one collection',
    de: 'of',
    casaEtq: 'The house',
    recibesEtq: 'What you get',
    recibesTit: 'Three things that stay in your hands',
    casoEtq: 'One case, complete',
  },
  obra: {
    h1: 'Work',
    lead: 'Stores, products and projects, every piece with its story.',
    secciones: 'Work sections',
    tiendas: 'Stores',
    mas: 'More work',
    masNota: 'Own products and personal projects.',
    anterior: 'Earlier work',
    colecciones: { bienestar: 'Wellness and supplements', cafe: 'Coffee', moda: 'Fashion and denim', belleza: 'Beauty and care', joyeria: 'Perfume and jewelry', otros: 'Pets and technology' },
    coleccion: 'Collection',
    cuenta: (n: number) => `${n} ${n === 1 ? 'piece' : 'pieces'}`,
  },
  kinds: { store: 'Store', product: 'Product', role: 'Deliverable', personal: 'Personal project' },
  ficha: {
    volver: 'Work',
    visitar: 'Visit the site',
    verCodigo: 'See the code',
    tabs: 'Piece sections',
    historia: 'Story',
    hechos: 'Facts',
    oficio: 'Craft',
    encargo: 'The brief',
    construi: 'What I built',
    alcance: 'Scope',
    fuente: 'Source: the project.',
    enConstruccion: 'In development',
    home: 'Home',
    pdp: 'Product',
    rubro: 'Industry',
    rol: 'Role',
    anio: 'Year',
    periodo: 'Period',
    empleo: 'Employer',
    pila: 'Stack',
    catalogo: 'Catalog',
    catalogoNota: (f: string) => `Public store catalog, ${f}.`,
    codigo: 'Code',
    movil: 'mobile',
    escritorio: 'desktop',
    medidasMovil: (m: string, e: string, f: string) => `Lighthouse (performance · accessibility · SEO): mobile ${m}, desktop ${e}. Local run, ${f}.`,
    medidasGit: (c: number, s: number, f: string) => `Repository: ${c} commits and ${s} custom sections, ${f}.`,
    capturas: 'The screens',
    capturasNota: 'Real captures of the store, unretouched.',
    siguiente: 'Next piece',
    noExiste: 'That piece does not exist',
    volverObra: 'Back to the work',
    sinCaptura: 'No public captures',
    pantalla: (v: string, vp: string) => `${v}, ${vp}`,
  },
  tray: {
    h1: 'Career',
    temporadas: 'Year by year',
    eyebrow: (n: number, desde: string) => `${n} roles · since ${desde}`,
    cv: 'Download the CV as a PDF',
    empleoTipo: { 'full-time': 'Full time', 'part-time': 'Part time', contract: 'Contract' } as Record<string, string>,
    mas: 'And more in the work',
    cargosDelAnio: 'Roles',
    verTodo: 'See the full role',
    verMenos: 'See less',
    entregables: 'Deliverables',
  },
  contacto: {
    h1: 'Contact',
    form: 'Ask for the review',
    motivo: 'How you want to start',
    tienda: 'Your store URL',
    tiendaEj: 'yourstore.com',
    correo: 'Your email',
    correoEj: 'you@store.com',
    motivos: motivos('en'),
    enviar: { revision: 'Ask for the review', proyecto: 'Tell me about the project', continuo: 'Talk about ongoing work', empleo: 'Write about the role' },
    enviando: 'Sending',
    ok: "Received. I'll write back to the email you left.",
    error: "It couldn't be sent. Your email app opened with the message ready.",
    falta: 'Enter a valid email.',
    faltaTienda: 'Enter your store URL.',
    canales: 'Channels',
    canalCorreo: 'Email',
    copiar: 'Copy',
    copiado: 'Copied',
    whatsapp: 'WhatsApp',
    waTexto: "Hi Max, I'd like the free 20-minute review of my store.",
    linkedin: 'LinkedIn',
    github: 'GitHub',
    cvCanal: 'CV as PDF',
    faq: 'Before you write',
  },
  pie: {
    nav: 'Footer',
    frase: 'Shopify engineering, measured.',
    medellin: 'Medellín, Colombia',
    hora: (h: string) => `${h} local time`,
    arriba: 'Back to top',
    derechos: '© 2026 Maximiliano Bustamante',
  },
  pies: {
    'the-gummy-box': 'A kit builder whose 10% to 20% discount applies itself.',
    'nos-cafe': 'Box builder: the discount climbs from 10% to 20% as it fills.',
    millennio: 'The Framer design, live on Shopify, with 260+ measured elements.',
    mindfuel: 'Home, product and quiz on one component library.',
    nalua: 'Offers and quantity tiers tied to real automatic discounts.',
    sebum: 'An extensible review wall on the product page.',
    'valdo-cafe': 'From staging to the real store, ready for the client to run.',
    'factores-2x2': 'From Framer design to Liquid, plus a web-quality pass.',
    pixxiesx: 'A product quiz and a metaobject-driven product page.',
    'luxe-shine': 'A scroll-driven video hero, and tracking to measure the store.',
    atmosfera: 'A catalog that updates itself from the supplier price lists.',
    'saint-theory': 'A custom Liquid theme from 2023, still the published one.',
    peluna: 'A redesign with A/B tests from day one.',
    'en-amor-a-dos': '57 custom sections for a jewelry brand.',
    unik: 'A bilingual, two-currency store with the catalog translated in bulk.',
    'origen-vital': 'Framer port with a quiz, mega menu and promo landings.',
    'para-machos': 'A new theme in progress; the live store stays untouched.',
    tierramont: 'A new theme for the real store, tracked issue by issue.',
    'alma-de-aviador': 'WooCommerce to Shopify, with the Framer design in 35 sections.',
  },
}

/**
 * Japonés: la interfaz corta (navegación, botones, pestañas, pie) y las frases por pieza están traducidas; las frases largas de
 * interfaz caen al inglés. Los textos de contenido (cargos, cifras, FAQ, proceso) sí llegan en japonés desde useV5().
 */
const ja: typeof es = {
  ...en,
  saltar: 'メインコンテンツへ',
  nav: { inicio: 'ホーム', obra: '実績', trayectoria: '経歴', contacto: 'お問い合わせ' },
  menu: { abrir: 'メニュー', cerrar: '閉じる' },
  idioma: '言語',
  escribeme: '連絡する',
  cv: 'CVをダウンロード',
  tiendasConstruidas: (n: string) => `${n}のストアを構築`,
  verObra: 'すべての実績を見る',
  verFicha: '詳細を見る',
  verTrayectoria: '経歴を見る',
  inicio: { ...en.inicio, dipticoSr: '最近の実績', obraEtq: '注目の実績', obraTit: '最近の実績', coleccionesEtq: 'コレクション', coleccionesTit: '1つの業種に、1つのコレクション', de: '/', casaEtq: 'ハウス', recibesEtq: '受け取るもの', recibesTit: '手元に残る3つのもの', casoEtq: 'ひとつの事例を最後まで' },
  obra: {
    h1: '実績', lead: 'ストア、プロダクト、プロジェクト。それぞれの背景つき。', secciones: '実績のセクション', tiendas: 'ストア', mas: 'その他の実績', masNota: '自社プロダクトと個人プロジェクト。', anterior: 'これまでの実績',
    colecciones: { bienestar: 'ウェルネス・サプリメント', cafe: 'コーヒー', moda: 'ファッション・デニム', belleza: 'ビューティー・ケア', joyeria: '香水・ジュエリー', otros: 'ペット・テクノロジー' },
    coleccion: 'コレクション', cuenta: (n: number) => `${n}件`,
  },
  kinds: { store: 'ストア', product: 'プロダクト', role: '成果物', personal: '個人プロジェクト' },
  ficha: {
    ...en.ficha, volver: '実績', visitar: 'サイトを見る', verCodigo: 'コードを見る', tabs: '詳細のセクション', historia: '経緯', hechos: '事実', oficio: '技術',
    encargo: '依頼内容', construi: '作ったもの', alcance: '範囲', fuente: '出典：プロジェクト。', enConstruccion: '構築中', home: 'ホーム', pdp: '商品',
    rubro: '業種', rol: '役割', anio: '年', periodo: '期間', empleo: '勤務先', pila: '技術スタック', catalogo: 'カタログ', catalogoNota: (f: string) => `ストアの公開カタログ（${f}）。`,
    codigo: 'コード', movil: 'モバイル', escritorio: 'デスクトップ',
    medidasMovil: (m: string, e: string, f: string) => `Lighthouse（パフォーマンス・アクセシビリティ・SEO）：モバイル ${m}、デスクトップ ${e}、${f}のローカル計測。`,
    medidasGit: (c: number, s: number, f: string) => `リポジトリ：${c}コミット、独自セクション${s}件（${f}）。`,
    capturas: '画面', capturasNota: 'ストアの実際のキャプチャ（加工なし）。', siguiente: '次の作品',
    noExiste: 'その作品は見つかりません', volverObra: '実績へ戻る', sinCaptura: '公開キャプチャなし', pantalla: (v: string, vp: string) => `${v}・${vp}`,
  },
  tray: { ...en.tray, h1: '経歴', eyebrow: (n: number, desde: string) => `${n}つの役割・${desde}年から`, temporadas: '年ごと', cv: 'CVをPDFでダウンロード', mas: '実績にもっと', cargosDelAnio: '役割', verTodo: '役割の全体を見る', verMenos: '閉じる', entregables: '成果物' },
  contacto: {
    ...en.contacto, h1: 'お問い合わせ', form: '無料レビューを依頼', motivo: '始め方', tienda: 'ストアのURL', correo: 'メールアドレス',
    enviar: { revision: '無料レビューを依頼', proyecto: 'プロジェクトを相談', continuo: '継続的な支援を相談', empleo: '採用について連絡' },
    enviando: '送信中', ok: '受け取りました。ご記入のメールアドレスに返信します。', falta: '有効なメールアドレスを入力してください。', faltaTienda: 'ストアのURLを入力してください。',
    canales: 'チャンネル', canalCorreo: 'メール', copiar: 'コピー', copiado: 'コピーしました', cvCanal: 'CV（PDF）', faq: 'ご質問の前に',
  },
  pie: { ...en.pie, nav: 'フッター', frase: '計測にもとづくShopifyエンジニアリング。', arriba: '上へ戻る', medellin: 'コロンビア、メデジン', hora: (h: string) => `現地時間 ${h}` },
  pies: {
    'the-gummy-box': 'チェックアウトで自動適用される10%→20%割引のキットビルダー。',
    'nos-cafe': '箱詰めビルダー。袋が増えるほど割引が10%から20%へ。',
    millennio: 'FramerのデザインをShopifyで稼働。260+の要素を計測。',
    mindfuel: 'ホーム・商品・クイズを1つのコンポーネントライブラリに。',
    nalua: '購入オファーと数量ティアを、実際の自動割引に接続。',
    sebum: '商品ページに拡張できるレビューウォール。',
    'valdo-cafe': 'テストストアから本番へ。クライアントがそのまま運用可能。',
    'factores-2x2': 'FramerからLiquidへ。Webクオリティの総点検つき。',
    pixxiesx: '商品クイズと、メタオブジェクトで動く商品ページ。',
    'luxe-shine': 'スクロール連動の動画ヒーローと、ストア計測のためのトラッキング。',
    atmosfera: 'サプライヤーの価格表から自動更新されるカタログ。',
    'saint-theory': '2023年に作ったカスタムLiquidテーマ。今も公開中。',
    peluna: '初日からA/Bテストを組み込んだリデザイン。',
    'en-amor-a-dos': 'ジュエリーブランドのための57のオリジナルセクション。',
    unik: 'バイリンガル・2通貨。カタログは一括翻訳。',
    'origen-vital': 'Framerから移植。クイズ、メガメニュー、プロモLP。',
    'para-machos': '新テーマを構築中。公開中のストアはそのまま。',
    tierramont: '実店舗向けの新テーマ。進捗はissue単位で管理。',
    'alma-de-aviador': 'WooCommerceからShopifyへ。Framerのデザインを35セクションに。',
  },
}

/** Interfaz en el idioma activo. */
export function useCopy() {
  const { locale } = useLanguage()
  return locale === 'es' ? es : locale === 'ja' ? ja : en
}
