// Generates the structured-data (JSON-LD) block shipped in index.html, plus a standalone
// public/jsonld.json for offline validation. Reads facts only from src/data/registry.ts (the
// same untranslated-facts source the rest of the site reads from) — never types a storefront
// name/URL by hand here, so this can't drift from what the Shopify Work section actually lists.
// Usage: node scripts/build-jsonld.mjs   (wired as the repo's "prebuild" script)
import fs from 'node:fs'
import path from 'node:path'

const ROOT = path.resolve(import.meta.dirname, '..')
const REGISTRY = path.join(ROOT, 'src/data/registry.ts')
const INDEX_HTML = path.join(ROOT, 'index.html')
const OUT_JSON = path.join(ROOT, 'public/jsonld.json')

const registrySrc = fs.readFileSync(REGISTRY, 'utf8')

// The `stores` array is one object literal per line (see registry.ts) — pull out the four
// fields this block needs with a scoped regex per entry rather than a full parser, matching the
// convention scripts/store-telemetry.mjs already uses for the same file.
const storesBlockMatch = registrySrc.match(/export const stores: StoreEntry\[\] = \[([\s\S]*?)\n\]/)
if (!storesBlockMatch) throw new Error('Could not find `stores` array in registry.ts')
const storeLines = storesBlockMatch[1].split('\n').filter((l) => l.trim().startsWith('{'))

const stores = storeLines.map((line) => {
  const slug = line.match(/slug: '([^']*)'/)?.[1] ?? ''
  const name = line.match(/name: '([^']*)'/)?.[1] ?? ''
  const url = line.match(/url: '([^']*)'/)?.[1] ?? ''
  const status = line.match(/status: '([^']*)'/)?.[1] ?? ''
  return { slug, name, url, status }
})

const liveStorefronts = stores.filter((s) => s.status === 'live' && s.url)
if (liveStorefronts.length === 0) throw new Error('No live storefronts with a public URL found — refusing to emit an empty ItemList')

const SITE = 'https://www.maxfolio.dev'
const today = new Date().toISOString().slice(0, 10)

const profilePage = {
  '@context': 'https://schema.org',
  '@type': 'ProfilePage',
  url: SITE,
  name: 'Maxfolio',
  inLanguage: ['en', 'es', 'ja'],
  dateModified: today,
  mainEntity: {
    '@type': 'Person',
    name: 'Maximiliano Bustamante',
    url: SITE,
    image: `${SITE}/og-image.png`,
    jobTitle: 'CTO & Shopify Tech Lead',
    hasOccupation: {
      '@type': 'Occupation',
      name: 'CTO & Shopify Tech Lead',
      occupationLocation: { '@type': 'City', name: 'Medellín' },
    },
    worksFor: { '@type': 'Organization', name: 'Digitdeck', url: 'https://digitdeck.co' },
    address: { '@type': 'PostalAddress', addressLocality: 'Medellín', addressCountry: 'Colombia' },
    email: 'maxbustamanteg@gmail.com',
    knowsAbout: ['Shopify', 'Liquid', 'Shopify Functions', 'Shopify Apps', 'React', 'Remix', 'TypeScript', 'Conversion Rate Optimization', 'A/B Testing', 'E-commerce'],
    alumniOf: { '@type': 'EducationalOrganization', name: 'EAFIT University' },
    sameAs: ['https://www.linkedin.com/in/maximiliano-bustamante-998b77173/', 'https://github.com/Max-Bustamante69'],
  },
}

const storefrontsList = {
  '@context': 'https://schema.org',
  '@type': 'ItemList',
  name: 'Shopify storefronts built by Maximiliano Bustamante',
  numberOfItems: liveStorefronts.length,
  itemListElement: liveStorefronts.map((s, i) => ({
    '@type': 'ListItem',
    position: i + 1,
    item: {
      '@type': 'CreativeWork',
      name: s.name,
      url: s.url,
      creator: { '@type': 'Person', name: 'Maximiliano Bustamante' },
    },
  })),
}

fs.writeFileSync(OUT_JSON, JSON.stringify({ profilePage, storefronts: storefrontsList }, null, 2) + '\n')

const blockHtml = [
  '    <script type="application/ld+json">',
  JSON.stringify(profilePage, null, 2)
    .split('\n')
    .map((l) => '    ' + l)
    .join('\n'),
  '    </script>',
  '',
  '    <script type="application/ld+json">',
  JSON.stringify(storefrontsList, null, 2)
    .split('\n')
    .map((l) => '    ' + l)
    .join('\n'),
  '    </script>',
].join('\n')

const html = fs.readFileSync(INDEX_HTML, 'utf8')
const START = '<!-- JSON-LD:START (generated by scripts/build-jsonld.mjs from src/data/registry.ts — edit there, not here) -->'
const END = '<!-- JSON-LD:END -->'
const startIdx = html.indexOf(START)
const endIdx = html.indexOf(END)
if (startIdx === -1 || endIdx === -1) throw new Error(`index.html is missing the ${START} / ${END} markers`)
const next = html.slice(0, startIdx + START.length) + '\n' + blockHtml + '\n    ' + html.slice(endIdx)
fs.writeFileSync(INDEX_HTML, next)

console.log(`jsonld: wrote public/jsonld.json and refreshed index.html with ${liveStorefronts.length} live storefronts (${liveStorefronts.map((s) => s.slug).join(', ')})`)
