import { useLanguage } from '../../context/LanguageContext'
import type { ObraKind } from '../data'
import { MOTIVOS, type Motivo } from '../shared/contacto'

// Etiquetas de interfaz de Plató. Los textos de contenido (hero, cifras, cargos, proceso, FAQ, obra) vienen de useV5();
// aquí solo vive la interfaz, en español e inglés (japonés usa el inglés). El asunto del correo que llega a Max va siempre
// en inglés (shared/contacto).
const motivos = (l: 'es' | 'en') => Object.fromEntries(Object.entries(MOTIVOS).map(([k, v]) => [k, v[l]])) as Record<Motivo, string>

const es = {
  saltar: 'Saltar al contenido',
  principal: 'Principal',
  nav: { inicio: 'Inicio', obra: 'Obra', trayectoria: 'Trayectoria', contacto: 'Contacto' },
  idioma: 'Idioma',
  menu: 'Menú',
  cerrar: 'Cerrar',
  revision: 'Revisión gratis',
  modo: { aLista: 'Ver como lista', a3d: 'Entrar al plató en 3D', grupo: 'Cómo ver la obra', etq3d: '3D', etqLista: 'Lista' },
  logo: 'Max Bustamante, inicio',
  cv: 'Descargar CV',
  inicio: {
    scroll: 'Scroll para entrar al plató',
    entrar: 'Recorrer la obra',
    verObra: 'Ver la obra',
    declaracion: 'Lo que hago siempre',
    cifrasNota: 'Resultados de mis cargos, cada uno con su empresa y su periodo. No son mediciones de laboratorio ni se pueden reproducir.',
    verCargo: 'Ver el cargo',
    verObraCifra: 'Ver la obra',
    destacada: 'Obra destacada',
    destacadaLead: 'Cuatro tiendas, una cifra cada una. El caso completo está en su ficha.',
    encargo: 'Qué se pidió',
    cambio: 'Qué cambió',
    medido: 'Qué se midió',
    verTodo: 'Ver toda la obra',
    cargosKicker: 'Cargo por cargo',
    cargosTitulo: 'Lo que dejó cada cargo',
    cargosLead: 'La cifra de cada puesto, con su empresa y su periodo.',
    verTrayectoria: 'Ver la trayectoria completa',
    cierreKicker: 'Cómo trabajo',
    pasosLink: 'Ver los cinco pasos y lo que recibes en cada uno',
    tiendasConstruidas: (n: string) => `${n} tiendas construidas`,
    lighthouseCorto: 'Lighthouse',
    nombre: 'Max Bustamante',
    ctaCorto: 'Pide tu revisión gratis',
    local: (h: string) => `${h} · hora local`,
  },
  obra: {
    h1: 'Obra',
    lead: 'Tiendas, productos y proyectos, cada uno con su historia.',
    lote: 'Lote',
    de: 'de',
    abrir: 'Abrir el caso',
    siguiente: 'Siguiente lote',
    anterior: 'Lote anterior',
    rubro: 'Rubro',
    tipos: { todo: 'Todo', store: 'Tiendas', product: 'Productos', personal: 'Propios', role: 'En los cargos' },
    filtrar: 'Filtrar por tipo',
    tiendas: 'Tiendas',
    tiendasAntes: 'Trabajo anterior',
    productos: 'Productos',
    propios: 'Proyectos propios',
    entregables: 'Entregables dentro de los cargos',
    sinCaptura: 'Sin captura pública',
    plato: 'Plató',
    recorrido: 'Recorrido por las tiendas',
    desliza: 'Desliza',
    tiendasN: (n: number) => `${n} tiendas`,
    masObra: 'Más allá de las tiendas',
    masObraLead: 'Las apps, la plataforma y los proyectos propios, cada uno con su historia.',
    verRestantes: (n: number) => `Ver los ${n} restantes`,
    verMenos: 'Ver menos',
  },
  kinds: { store: 'Tienda', product: 'Producto', role: 'Entregable', personal: 'Proyecto propio' } satisfies Record<ObraKind, string>,
  ficha: {
    volver: 'Obra',
    fachada: 'Fachada',
    visitar: 'Visitar la tienda',
    visitarSitio: 'Visitar el sitio',
    caso: 'El caso',
    capturas: 'Capturas reales',
    home: 'Home',
    pdp: 'Producto',
    vista: 'Vista',
    datos: 'Datos',
    rubro: 'Rubro',
    rol: 'Rol',
    anio: 'Año',
    periodo: 'Ventana',
    empleo: 'Empleo',
    pila: 'Pila',
    catalogo: 'Catálogo',
    catalogoNota: (f: string) => `Catálogo público, a ${f}.`,
    repo: 'Código',
    medido: 'Medido',
    lighthouse: 'Lighthouse',
    movil: 'Móvil',
    escritorio: 'Escritorio',
    rend: 'Rendimiento',
    acc: 'Accesibilidad',
    seo: 'SEO',
    lhNota: (f: string) => `Medición local del ${f}, mejor de 3.`,
    siguiente: 'Siguiente',
    anterior: 'Anterior',
    noExiste: 'Esa obra no existe',
    volverObra: 'Volver a la obra',
    sinCaptura: 'Esta obra no tiene captura pública; aquí va su historia.',
    encargo: 'Encargo',
    construi: 'Qué construí',
    medida: 'Cómo se mide',
    hoja: 'Hoja técnica',
    medidoTitulo: 'Lo que se midió',
    capturasDe: (f: string) => `Capturas del ${f}`,
    escritorioLbl: 'Escritorio',
    movilLbl: 'Móvil',
    plano: 'Sin captura pública',
    pidio: 'Qué se pidió',
    cambio: 'Qué cambió',
    midio: 'Qué se midió',
    estado: 'Estado',
    estadoVal: { live: 'En vivo', dev: 'En construcción' },
    historial: 'Historial',
    historialVal: (commits: number, f: string) => `${commits} commits en git, a ${f}`,
    zonaTel: 'Pantalla del teléfono: la rueda, el arrastre o las flechas recorren la tienda',
    baja: 'Baja: la pantalla recorre la tienda',
    recorridoDe: (f: string) => `Home móvil completa, capturada el ${f}`,
    telefonoCss: 'Home de la tienda en un teléfono; se desplaza con el dedo',
    marcoTel: 'Marco de teléfono con la tienda',
    ver3d: 'Ver en 3D',
    visor: 'El teléfono en 3D',
    arrastra: 'Arrastra para girarlo',
    recorrer: 'Recorrer la tienda',
    cerrarVisor: 'Cerrar el visor',
  },
  tray: {
    h1: 'Trayectoria',
    hoy: 'Hoy',
    cargo: 'Cargo',
    logros: 'Qué se entregó',
    pila: 'Stack',
    visitar: 'Visitar sitio',
    anios: 'Cinco años, una sola dirección',
    habilidades: 'Con qué trabajo',
    verObra: 'Ver el trabajo de este cargo',
    verLogros: (n: number) => `Ver los ${n} restantes`,
    menosLogros: 'Ver menos',
  },
  contacto: {
    tienda: 'La URL de tu tienda',
    tiendaEj: 'tutienda.com',
    correo: 'Tu correo',
    correoEj: 'tu@tienda.com',
    motivos: motivos('es'),
    motivo: 'Motivo',
    enviar: { revision: 'Pedir la revisión', proyecto: 'Contar el proyecto', continuo: 'Hablar del trabajo continuo', empleo: 'Escribir por la vacante' },
    enviando: 'Enviando',
    ok: 'Recibido. Te escribiré al correo que dejaste.',
    error: 'No se pudo enviar. Se abrió tu correo con el mensaje listo.',
    falta: 'Escribe un correo válido.',
    faltaTienda: 'Escribe la URL de tu tienda.',
    elegir: 'Elegir este modelo',
    canales: 'Canales directos',
    canalCorreo: 'Correo',
    copiar: 'Copiar',
    copiado: 'Copiado',
    whatsapp: 'WhatsApp',
    waTexto: 'Hola Max, quiero la revisión gratis de 20 minutos de mi tienda.',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    cvCanal: 'CV en PDF',
    faq: 'Antes de escribir',
    veinte: {
      kicker: 'Qué pasa en los 20 minutos',
      titulo: 'Tres puntos, en este orden',
      items: [
        { k: 'Velocidad', t: 'Cómo carga hoy tu tienda y qué la frena.' },
        { k: 'Ofertas', t: 'Si el descuento llega solo al carrito o depende de que el comprador lo encuentre.' },
        { k: 'Checkout', t: 'Dónde se frena el comprador entre el carrito y el pago.' },
      ],
      prueba: 'Lo que ya medí',
    },
    ofertaFuente: 'The Gummy Box, 2026',
  },
  pie: { medellin: 'Medellín, Colombia', arriba: 'Volver arriba', derechos: '© 2026 Maximiliano Bustamante', redes: 'Redes', escribir: 'Escribir' },
}

const en: typeof es = {
  saltar: 'Skip to content',
  principal: 'Main',
  nav: { inicio: 'Home', obra: 'Work', trayectoria: 'Career', contacto: 'Contact' },
  idioma: 'Language',
  menu: 'Menu',
  cerrar: 'Close',
  revision: 'Free review',
  modo: { aLista: 'View as list', a3d: 'Enter the set in 3D', grupo: 'How to view the work', etq3d: '3D', etqLista: 'List' },
  logo: 'Max Bustamante, home',
  cv: 'Download CV',
  inicio: {
    scroll: 'Scroll to enter the set',
    entrar: 'Walk the work',
    verObra: 'See the work',
    declaracion: 'What I always do',
    cifrasNota: 'Results from my roles, each with its company and period. They are not lab measurements and cannot be reproduced.',
    verCargo: 'See the role',
    verObraCifra: 'See the work',
    destacada: 'Featured work',
    destacadaLead: 'Four stores, one figure each. The full case is on its page.',
    encargo: 'What was asked',
    cambio: 'What changed',
    medido: 'What was measured',
    verTodo: 'See all the work',
    cargosKicker: 'Role by role',
    cargosTitulo: 'What each role delivered',
    cargosLead: 'The figure from every position, with its company and period.',
    verTrayectoria: 'See the full career',
    cierreKicker: 'How I work',
    pasosLink: 'See the five steps and what you receive in each',
    tiendasConstruidas: (n: string) => `${n} stores built`,
    lighthouseCorto: 'Lighthouse',
    nombre: 'Max Bustamante',
    ctaCorto: 'Get your free review',
    local: (h: string) => `${h} · local time`,
  },
  obra: {
    h1: 'Work',
    lead: 'Stores, products and projects, each with its story.',
    lote: 'Lot',
    de: 'of',
    abrir: 'Open the case',
    siguiente: 'Next lot',
    anterior: 'Previous lot',
    rubro: 'Industry',
    tipos: { todo: 'All', store: 'Stores', product: 'Products', personal: 'Own', role: 'In the roles' },
    filtrar: 'Filter by type',
    tiendas: 'Stores',
    tiendasAntes: 'Earlier work',
    productos: 'Products',
    propios: 'Own projects',
    entregables: 'Deliverables inside the roles',
    sinCaptura: 'No public capture',
    plato: 'Set',
    recorrido: 'Walk through the stores',
    desliza: 'Swipe',
    tiendasN: (n: number) => `${n} stores`,
    masObra: 'Beyond the stores',
    masObraLead: 'The apps, the platform and the own projects, each with its story.',
    verRestantes: (n: number) => `See the remaining ${n}`,
    verMenos: 'See less',
  },
  kinds: { store: 'Store', product: 'Product', role: 'Deliverable', personal: 'Own project' },
  ficha: {
    volver: 'Work',
    fachada: 'Facade',
    visitar: 'Visit the store',
    visitarSitio: 'Visit the site',
    caso: 'The case',
    capturas: 'Real captures',
    home: 'Home',
    pdp: 'Product',
    vista: 'View',
    datos: 'Data',
    rubro: 'Industry',
    rol: 'Role',
    anio: 'Year',
    periodo: 'Build window',
    empleo: 'Employer',
    pila: 'Stack',
    catalogo: 'Catalog',
    catalogoNota: (f: string) => `Public catalog, as of ${f}.`,
    repo: 'Code',
    medido: 'Measured',
    lighthouse: 'Lighthouse',
    movil: 'Mobile',
    escritorio: 'Desktop',
    rend: 'Performance',
    acc: 'Accessibility',
    seo: 'SEO',
    lhNota: (f: string) => `Local measurement from ${f}, best of 3.`,
    siguiente: 'Next',
    anterior: 'Previous',
    noExiste: 'That work does not exist',
    volverObra: 'Back to the work',
    sinCaptura: 'This work has no public capture; its story goes here.',
    encargo: 'The brief',
    construi: 'What I built',
    medida: 'How it is measured',
    hoja: 'Technical sheet',
    medidoTitulo: 'What was measured',
    capturasDe: (f: string) => `Captures from ${f}`,
    escritorioLbl: 'Desktop',
    movilLbl: 'Mobile',
    plano: 'No public capture',
    pidio: 'The brief',
    cambio: 'What changed',
    midio: 'What was measured',
    estado: 'Status',
    estadoVal: { live: 'Live', dev: 'In progress' },
    historial: 'History',
    historialVal: (commits: number, f: string) => `${commits} commits in git, as of ${f}`,
    zonaTel: 'Phone screen: the wheel, dragging or the arrow keys scroll through the store',
    baja: 'Scroll: the screen walks the store',
    recorridoDe: (f: string) => `Full mobile home, captured ${f}`,
    telefonoCss: 'The store home on a phone; scroll it with your finger',
    marcoTel: 'Phone frame with the store',
    ver3d: 'View in 3D',
    visor: 'The phone in 3D',
    arrastra: 'Drag to turn it',
    recorrer: 'Walk the store',
    cerrarVisor: 'Close the viewer',
  },
  tray: {
    h1: 'Career',
    hoy: 'Today',
    cargo: 'Role',
    logros: 'What was delivered',
    pila: 'Stack',
    visitar: 'Visit site',
    anios: 'Five years, one direction',
    habilidades: 'What I work with',
    verObra: 'See the work from this role',
    verLogros: (n: number) => `See the remaining ${n}`,
    menosLogros: 'See less',
  },
  contacto: {
    tienda: 'Your store URL',
    tiendaEj: 'yourstore.com',
    correo: 'Your email',
    correoEj: 'you@store.com',
    motivos: motivos('en'),
    motivo: 'Reason',
    enviar: { revision: 'Request the review', proyecto: 'Tell me about the project', continuo: 'Talk about ongoing work', empleo: 'Write about the role' },
    enviando: 'Sending',
    ok: "Received. I'll write to the email you left.",
    error: 'It could not be sent. Your email app opened with the message ready.',
    falta: 'Enter a valid email.',
    faltaTienda: 'Enter your store URL.',
    elegir: 'Choose this model',
    canales: 'Direct channels',
    canalCorreo: 'Email',
    copiar: 'Copy',
    copiado: 'Copied',
    whatsapp: 'WhatsApp',
    waTexto: "Hi Max, I'd like the free 20-minute review of my store.",
    linkedin: 'LinkedIn',
    github: 'GitHub',
    cvCanal: 'CV as PDF',
    faq: 'Before you write',
    veinte: {
      kicker: 'What happens in the 20 minutes',
      titulo: 'Three points, in this order',
      items: [
        { k: 'Speed', t: 'How your store loads today and what slows it down.' },
        { k: 'Offers', t: 'Whether the discount reaches the cart on its own or depends on the buyer finding it.' },
        { k: 'Checkout', t: 'Where the buyer stalls between the cart and the payment.' },
      ],
      prueba: 'What I already measured',
    },
    ofertaFuente: 'The Gummy Box, 2026',
  },
  pie: { medellin: 'Medellín, Colombia', arriba: 'Back to top', derechos: '© 2026 Maximiliano Bustamante', redes: 'Elsewhere', escribir: 'Write' },
}

export type Copy = typeof es
export const copyFor = (l: string): Copy => (l === 'es' ? es : en)
export const useCopy = (): Copy => copyFor(useLanguage().locale)
